Repository owncloud/web, pull requests merged in 2018-11, with the labels that each got.

#324 WorkInProgress - Remove UIKit & cleanup files
  apps/files/.babelrc
  apps/files/package.json
  apps/files/src/components/File-Details.vue
  apps/files/src/components/FileactionsTab.vue
  apps/files/src/components/Files-App.vue
  apps/files/src/default.js
  apps/files/src/mixins.js
  apps/files/src/store.js
  apps/files/webpack.common.js
  apps/files/yarn.lock
  package.json
  src/Phoenix.vue
  src/components/Menu.vue
  src/components/NotificationBar.vue
  src/components/Top-Bar.vue
  src/default.js
  src/pages/error.vue
  src/pages/login.vue
  src/router/index.js
  src/store/app.js
  src/store/index.js
  src/store/user.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/loginContext.js
  webpack.common.js
  yarn.lock
Labels: Developing

#339 Deploy on every master push
  .drone.yml
  apps/demo/yarn-error.log
  apps/files/yarn-error.log
Labels: To Review

#356 File Actions (open/edit) for apps with custom file extension support
  .gitignore
  apps/demo/src/app.js
  apps/files/docs/extensionpoints.adoc
  apps/files/src/components/FileactionsTab.vue
  apps/files/src/components/Files-App.vue
  apps/files/src/default.js
  apps/markdown-editor/package.json
  apps/markdown-editor/src/MarkdownEditor.vue
  apps/markdown-editor/src/app.js
  apps/markdown-editor/webpack.config.js
  apps/markdown-editor/yarn.lock
  apps/servstat/src/app.js
  package.json
  src/components/Menu.vue
  src/default.js
  src/store/apps.js
  src/store/index.js
  static/fonts/ocft/css/ocft.css
  static/fonts/ocft/font/ocft.eot
  static/fonts/ocft/font/ocft.svg
  static/fonts/ocft/font/ocft.ttf
  static/fonts/ocft/font/ocft.woff
  static/fonts/ocft/font/ocft.woff2
  static/fonts/ocft/icons/README.txt
  webpack.common.js
  yarn.lock
Labels: To Review, enhancement, requirement
