Repository owncloud/web, pull requests merged in 2018-12, with the labels that each got.

#380 Set max version to 10 for Semver
  appinfo/info.xml
Labels: To Review

#381 Feature/yarn cleanup
  .editorconfig
  .eslintrc.json
  Makefile
  apps/files/package.json
  package.json
  src/Phoenix.vue
  src/components/Menu.vue
  src/default.js
  webpack.common.js
  yarn.lock
Labels: To Review

#406 refs #267 add filetype icons from static mapping
  apps/files/src/components/DirTable.vue
  apps/files/src/fileTypeIconMappings.json
  apps/files/src/store.js
  apps/files/yarn.lock
Labels: Implementation Task, design, enhancement, requirement

#411 Improve security by detecting expired oauth token in vue-authenticate wrapper
  src/pages/login.vue
  src/services/auth.js
  src/store/index.js
  src/store/user.js
Labels: bug, enhancement

#412 Feature/fix logo and themes
  Makefile.release
  README.md
  src/components/Top-Bar.vue
  src/pages/login.vue
  themes/example.json
  themes/example/logo-icon.svg
  themes/owncloud.json
  themes/owncloud/cloud-logo-invert.svg
Labels: To Review

#382 Feature/alternative file list
  apps/files/package.json
  apps/files/src/components/DirTable.vue
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FileUpload.vue
  apps/files/src/components/FileUploadProgress.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/ocDialogPrompt.vue
  apps/files/src/fileTypeIconMappings.json
  apps/files/src/mixins.js
  apps/files/src/store.js
  src/components/Menu.vue
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/loginContext.js
  themes/owncloud.json
Labels: To Review

#416 Demo and serverstat app are removed now
  apps/demo/package.json
  apps/demo/src/ButtonRowItem.vue
  apps/demo/src/DemoShowConfig.vue
  apps/demo/src/app.js
  apps/demo/webpack.config.js
  apps/demo/yarn.lock
  apps/servstat/package.json
  apps/servstat/src/Indicator.vue
  apps/servstat/src/app.js
  apps/servstat/webpack.config.js
  apps/servstat/yarn.lock
Labels: To Review

#418 Feature/gradient login screen
  src/Phoenix.vue
  src/components/Top-Bar.vue
  src/default.js
  src/pages/error.vue
  src/pages/login.vue
Labels: To Review

#420 Add htaccess to define caching in browsers
  .htaccess
  Makefile.release
Labels: To Review

#421 Bugfix/some low hanging fruits
  apps/files/src/components/FileUploadProgress.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/ocDialogPrompt.vue
  src/components/Menu.vue
  src/store/user.js
Labels: bug

#427 [files] Allow sidebars to register a quick access button to the file …
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
Labels: To Review

#430 [files] Fix error handling on upload and success handling in sub folder
  apps/files/src/FileUpload.js
  apps/files/src/components/FilesApp.vue
Labels: To Review

#437 close #415 scope app routes with their id
  apps/files/src/default.js
  apps/markdown-editor/src/app.js
  src/default.js
Labels: bug, enhancement
