Repository owncloud/web, pull requests merged in 2019-02, with the labels that each got.

#582 add conflict handling for existing files
  apps/files/src/components/FileUpload.vue
Labels: 3 - To Review, enhancement

#589 bump all npm dependencies
  apps/files/package.json
  apps/files/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: PM prio 3, Waiting On Review/Feedback, dependencies

#591 Add translations to markdown-editor and pdf-viewer
  apps/markdown-editor/src/MarkdownEditor.vue
  l10n/Makefile
Labels: 3 - To Review

#622 bump all npm dependencies
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review, dependencies

#632 bump dependencies
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: dependencies

#623 Fixed topbar and named routes
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesTopBar.vue
  apps/files/src/default.js
  apps/markdown-editor/package.json
  apps/markdown-editor/src/MarkdownEditor.vue
  apps/markdown-editor/src/MarkdownEditorTopbar.vue
  apps/markdown-editor/src/app.js
  apps/markdown-editor/src/store.js
  apps/markdown-editor/webpack.config.js
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/src/PdfViewer.vue
  apps/pdf-viewer/src/PdfViewerTopbar.vue
  apps/pdf-viewer/src/app.js
  apps/pdf-viewer/src/store.js
  apps/pdf-viewer/webpack.common.js
  index.html
  src/Phoenix.vue
  src/components/Menu.vue
  src/components/OcAppTopBar.vue
  src/components/Top-Bar.vue
  src/router/index.js
Labels: design, enhancement

#638 bump dependencies
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: dependencies

#645 img folder is missing on the release
  Makefile.release
Labels: 4 - To release

#658 bump dependencies
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review, dependencies

#659 Feature/easy development
  .drone.yml
  .gitignore
  Dockerfile
  Makefile.release
  build.js
  build/run-for-all.js
  package.json
  update.js
  yarn.lock
Labels: 3 - To Review

#660 Respect readonly status of folders and files
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesTopBar.vue
  apps/files/src/store.js
Labels: 3 - To Review

#669 adopt README to new run script names
  README.md
Labels: 3 - To Review, Waiting On Review/Feedback, bug-solved, documentation

#663 Introduce OcAppSidebar, OcAppNavbar and OcAppContent
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileInfoSidebar.vue
  apps/files/src/components/FilesApp.vue
  src/Phoenix.vue
  src/components/OcAppContent.vue
  src/components/OcAppNavBar.vue
  src/components/OcAppSideBar.vue
Labels: 3 - To Review, design, enhancement

#668 Show upload spinner
  apps/files/src/components/FilesTopBar.vue
Labels: 3 - To Review

#670 introduce file versions
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileInfoVersions.vue
  apps/files/src/components/FileactionsTab.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/default.js
  apps/files/src/store.js
  src/Phoenix.vue
  src/components/OcAppContent.vue
  src/components/OcList.vue
Labels: 3 - To Review, enhancement

#671 Remove header from upload menu
  apps/files/src/components/FilesTopBar.vue
Labels: 3 - To Review

#673 Add getter getToken to file action tab to fix download
  apps/files/src/components/FileactionsTab.vue
Labels: 3 - To Review

#666 global & local file search
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesTopBar.vue
  apps/files/src/mixins.js
  apps/files/src/store.js
  nightwatch.conf.js
  src/components/form/SearchBar.vue
  tests/acceptance/stepDefinitions/loginContext.js
Labels: 3 - To Review, design, discussion, enhancement, feature:files

#699 lint-fix webpack files
  apps/files/webpack.common.js
  apps/files/webpack.dev.js
  apps/markdown-editor/src/app.js
  apps/markdown-editor/webpack.config.js
  apps/pdf-viewer/webpack.common.js
  apps/pdf-viewer/webpack.dev.js
  nightwatch.conf.js
  src/default.js
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: 3 - To Review, bug-solved

#698 bump all npm dependencies
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review, Waiting On Review/Feedback, dependencies

#702 fix lint and lint-errors
  apps/markdown-editor/src/MarkdownEditor.vue
  apps/markdown-editor/src/MarkdownEditorTopbar.vue
  package.json
Labels: 3 - To Review

#718 bump dependencies
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: dependencies

#726 bump dependencies
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: dependencies

#696 close #665 fix file filters
  apps/files/src/components/FileFilterMenu.vue
  apps/files/src/components/FilesTopBar.vue
  apps/files/src/fileFilters.js
  apps/files/src/store.js
Labels: 3 - To Review, bug-solved

#701 fix sidebar behavior on smaller screens
  apps/files/src/components/FileInfoSidebar.vue
  apps/files/src/components/FileInfoVersions.vue
  apps/files/src/store.js
  src/Phoenix.vue
  src/components/OcAppSideBar.vue
  src/components/OcAppTopBar.vue
  src/components/OcList.vue
Labels: 3 - To Review

#679 Create CODEOWNERS
  .github/CODEOWNERS
Labels: 3 - To Review

#729 Allow theming of top bar
  src/components/Top-Bar.vue
Labels: 3 - To Review

#741 Use 500px width on sidebar
  src/Phoenix.vue
  src/components/OcAppSideBar.vue
Labels: 3 - To Review
