Repository owncloud/web, pull requests merged in 2019-04, with the labels that each got.

#873 Create folder edge cases
  tests/acceptance/features/webUIFiles/createFolderEdgeCases.feature
  tests/acceptance/pageObjects/filesPage.js
Labels: 3 - To Review, Acceptance tests, QA-team

#874 click on folder item to navigate in tests
  tests/acceptance/pageObjects/filesPage.js
Labels: 3 - To Review, Acceptance tests, QA-team

#882 Update all dependencies
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review

#879 [acceptance tests] Create hidden folder
  nightwatch.conf.js
  tests/acceptance/customCommands/initAjaxCounters.js
  tests/acceptance/customCommands/waitForAjaxCallsToStartAndFinish.js
  tests/acceptance/customCommands/waitForOutstandingAjaxCalls.js
  tests/acceptance/features/webUIFiles/hiddenFile.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#857 Files: use app-layout and sidebar tabs
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileInfoSidebar.vue
  apps/files/src/components/FileInfoVersions.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/default.js
  apps/markdown-editor/src/app.js
  src/components/OcAppSideBar.vue
  src/components/OcList.vue
  src/pages/oidcCallback.vue
  src/store/apps.js
Labels: 3 - To Review

#876 Fixed opening of pdf viewer and wrong components names
  apps/files/src/components/FilesApp.vue
  apps/pdf-viewer/src/PdfViewer.vue
  apps/pdf-viewer/src/PdfViewerTopbar.vue
  apps/pdf-viewer/src/app.js
Labels: 3 - To Review

#884 use oc-app-side-bar from ods
  apps/files/src/components/FileDetails.vue
  src/components/OcAppSideBar.vue
Labels: 3 - To Review

#887 Add ods from npmjs.com
  README.md
  package.json
  webpack.common.js
  yarn.lock
Labels: 3 - To Review

#886 Fixed checking all boxes when using checkbox in top bar
  apps/files/src/components/FileList.vue
  src/components/Avatar.vue
  src/store/user.js
Labels: 3 - To Review

#890 Fix CI
  .drone.yml
Labels: 3 - To Review

#892 Fixed progress bar
  apps/files/src/components/FilesTopBar.vue
Labels: 3 - To Review

#893 Update deps 20190405
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review

#894 Bugfix/file-icons
  apps/files/src/components/FileList.vue
Labels: 3 - To Review, bug-solved

#904 Removed value of search and added condition for loading
  apps/files/src/components/FilesTopBar.vue
Labels: 3 - To Review, bug-solved

#910 fix CI
  .drone.yml
  apps/files/src/components/FilesTopBar.vue
  apps/markdown-editor/src/app.js
  tests/acceptance/features/webUIFiles/hiddenFile.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#914 Fixed links in breadcrumbs
  apps/files/src/components/FilesTopBar.vue
Labels: 3 - To Review, bug-solved

#915 Fixed file upload
  apps/files/src/FileUpload.js
Labels: 3 - To Review, bug

#922 use tr as fileRow instead of the link
  tests/acceptance/pageObjects/filesPage.js
Labels: 3 - To Review, Acceptance tests, QA-team

#920 allow to specify external selenium host
  nightwatch.conf.js
Labels: 3 - To Review, Acceptance tests, QA-team

#925 Fixed file size in file upload menu
  apps/files/src/components/FileList.vue
  apps/files/src/mixins.js
Labels: 2 - Developing, bug-solved

#927 Update translations from transifex
  apps/files/l10n/translations.json
  apps/files/src/components/FileList.vue
Labels: 3 - To Review

#932 Create folder with existing name tests
  .drone.yml
  tests/acceptance/features/webUIFiles/createFolders.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#926 Bring back file versions
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileInfoVersions.vue
  apps/files/src/components/FileList.vue
  apps/files/src/mixins.js
  apps/files/src/store.js
Labels: 3 - To Review

#935 feature descriptions for renaming files and folders
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#905 Bugfix/menu alignment
  apps/files/src/components/FileUpload.vue
  apps/files/src/components/FilesTopBar.vue
Labels: 3 - To Review, bug-solved

#923 tests to delete files
  apps/files/src/components/FileList.vue
  tests/acceptance/customCommands/initAjaxCounters.js
  tests/acceptance/customCommands/waitForAnimationToFinish.js
  tests/acceptance/customCommands/waitForOutstandingAjaxCalls.js
  tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/webdavContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#945 descriptions for the versions feature
  tests/acceptance/features/webUIFiles/versions.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#944 descriptions for the search feature
  tests/acceptance/features/webUIFiles/search.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#943 descriptions for browse-directly-to-tab feature
  tests/acceptance/features/webUIFiles/browseDirectlyToDetailsTab.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#942 feature descriptions for favorites
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#941 feature descriptions for comments
  tests/acceptance/features/webUIComments/comments.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#947 descriptions for the moving feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#949 descriptions of various sharing restriction features
  tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#951 descriptions of the tags feature
  tests/acceptance/features/webUITags/createTags.feature
  tests/acceptance/features/webUITags/tagsSuggestion.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#953 descriptions of webdav lock feature
  tests/acceptance/features/webUIWebdavLockProtection/delete.feature
  tests/acceptance/features/webUIWebdavLockProtection/move.feature
  tests/acceptance/features/webUIWebdavLockProtection/upload.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#952 descriptions of the trashbin feature
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
  tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#950 descriptions of various sharing features
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingNotifications/notificationLink.feature
  tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature
  tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#954 descriptions of the upload feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#955 do not run all tests locally
  README.md
  package.json
Labels: 3 - To Review, Acceptance tests, QA-team

#948 Split files vuex into multiple files for better maintainability
  apps/files/src/default.js
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/index.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
Labels: 3 - To Review

#966 rename file and folders tests
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#957 Use new application menu design
  package.json
  src/components/Menu.vue
  yarn.lock
Labels: 3 - To Review

#933 Added upload menu component
  apps/files/src/components/FilesTopBar.vue
Labels: 3 - To Review, bug-solved

#956 Start to support more languages: es, cs, fr, it
  apps/files/l10n/translations.json
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileInfoSidebar.vue
  apps/files/src/components/FileInfoVersions.vue
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/default.js
  apps/markdown-editor/l10n/translations.json
  apps/pdf-viewer/l10n/translations.json
  l10n/Makefile
  l10n/translations.json
  src/phoenix.js
Labels: 3 - To Review

#968 update documentation about running tests
  README.md
Labels: 3 - To Review, Acceptance tests, QA-team

#972 Fixed map import
  apps/files/src/store/actions.js
Labels: 3 - To Review, bug-solved

#970 Bugfix/934
  README.md
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesTopBar.vue
  apps/files/src/store/actions.js
  apps/files/src/store/mutations.js
  apps/markdown-editor/src/MarkdownEditorTopbar.vue
  apps/pdf-viewer/src/PdfViewerTopbar.vue
  src/components/Top-Bar.vue
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
Labels: 3 - To Review

#973 No need to createObjectURL if the request failed
  src/components/Avatar.vue
Labels: 3 - To Review

#981 improve documentation about running acceptance tests
  README.md
Labels: 3 - To Review, Acceptance tests, QA-team

#982 Search tests
  tests/acceptance/features/webUIFiles/search.feature
  tests/acceptance/helpers/httpHelper.js
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/acceptance/stepDefinitions/searchContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#983 Use owncloud-sdk from npmjs.com
  apps/files/src/components/FilesApp.vue
  apps/markdown-editor/src/MarkdownEditor.vue
  apps/markdown-editor/src/MarkdownEditorTopbar.vue
  apps/markdown-editor/src/store.js
  package.json
  src/phoenix.js
  yarn.lock
Labels: 3 - To Review

#1004 Fixed display of special characters in delete dialog
  apps/files/src/components/FileList.vue
Labels: 3 - To Review, bug-solved

#1005 Display error if user tries to rename file with a slash
  apps/files/src/mixins.js
Labels: 3 - To Review, bug-solved

#1009 Add support for Galician - THX translators - nice job :+1:
  apps/files/l10n/translations.json
  apps/markdown-editor/l10n/translations.json
  apps/pdf-viewer/l10n/translations.json
  l10n/Makefile
  l10n/translations.json
  src/phoenix.js
Labels: 3 - To Review

#1003 Use elipsis character instead of 3 dots
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesTopBar.vue
  apps/pdf-viewer/src/PdfViewer.vue
  src/pages/oidcSilentRedirect.vue
  src/phoenix.js
  src/store/user.js
  tests/acceptance/features/webUIFiles/createFolders.feature
Labels: 3 - To Review

#1000 Added filters functionality
  apps/files/src/components/FileFilterMenu.vue
  apps/files/src/components/FileUpload.vue
  apps/files/src/components/FilesTopBar.vue
  tests/acceptance/features/webUIFiles/hiddenFile.feature
  tests/acceptance/pageObjects/filesPage.js
  yarn.lock
Labels: 3 - To Review, bug-solved

#1015 Clean search after navigating into a folder
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesTopBar.vue
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
Labels: 3 - To Review

#991 Added drag and drop
  apps/files/package.json
  apps/files/src/components/FileDrop.vue
  apps/files/src/components/FileUpload.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesTopBar.vue
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  apps/files/yarn.lock
Labels: 3 - To Review

#1038 Remove skips from tests that are passing
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
Labels: 3 - To Review, QA-team

#1018 add .dockerignore
  .dockerignore
Labels: 3 - To Review

#1039 Add description feature files for adminSettings page tests
  tests/acceptance/features/webUIAdminSettings/adminAppsSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
  tests/acceptance/features/webUIAdminSettings/helpAndTips.feature
Labels: 3 - To Review, QA-team

#1041 Don't watch test files for full page reload
  webpack.dev.js
Labels: 3 - To Review, QA-team

#1043 tag test that is skiped because of #965
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
Labels: 3 - To Review, Acceptance tests

#1019 allow folders to be named <home>
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesTopBar.vue
  apps/files/src/default.js
  apps/pdf-viewer/src/PdfViewer.vue
  apps/pdf-viewer/src/PdfViewerTopbar.vue
  tests/acceptance/features/webUIFiles/createFolderEdgeCases.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/pageObjects/filesPage.js
Labels: 3 - To Review

#1040 Update deps 20190429
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review

#1048 test to rename to names containing a '/'
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/pageObjects/phoenixPage.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1051 Reused login components at redirection
  src/pages/oidcCallback.vue
Labels: 3 - To Review, enhancement
