Repository owncloud/web, pull requests merged in 2019-07, with the labels that each got.

#1205 Created notifications panel and store
  .drone.yml
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
  apps/pdf-viewer/src/PdfViewer.vue
  src/Phoenix.vue
  src/components/MessageBar.vue
  src/components/Notifications.vue
  src/components/Top-Bar.vue
  src/store/app.js
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/stepDefinitions/generalContext.js
  tests/acceptance/stepDefinitions/notificationsContext.js
Labels: 2 - Developing

#1363 Add acceptance test for deleting share
  apps/files/src/components/FileSharingSidebar.vue
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1370 Hide drop in files list if dialog is opened
  apps/files/src/components/FileList.vue
Labels: 3 - To Review, bug-solved

#1382 Added trashbin
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/Trashbin.vue
  apps/files/src/default.js
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  package.json
  src/Phoenix.vue
  src/store/config.js
  src/store/user.js
  yarn.lock
Labels: 2 - Developing, enhancement

#1401 Update dependencies 20190702
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review

#1402 Allow change of root folder
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/default.js
  src/store/config.js
  tests/drone/config.json
Labels: 3 - To Review, enhancement

#1387 Adjusted width of sidebar and allowed scroll in it
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FilesApp.vue
Labels: 3 - To Review

#1408 add protocol to LOCAL_LAUNCH_URL if its not given
  nightwatch.conf.js
Labels: Acceptance tests, QA-team

#1420 Fix account page
  src/router/index.js
Labels: 3 - To Review

#1422 Fix dropdown in file list actions
  apps/files/src/components/FileList.vue
Labels: 3 - To Review, bug-solved

#1421 Fix favoritesPage test failure due to sidebar sliding slow.
  tests/acceptance/pageObjects/phoenixPage.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1424 Fixed name of alerts in store
  src/store/app.js
Labels: 3 - To Review, bug-solved

#1407 Acceptance test for favorites page
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFiles/createFolderEdgeCases.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/helpers/xpath.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1409 Add simple auth image loader
  src/mixins/imageSrc.js
  src/phoenix.js
Labels: 3 - To Review, enhancement

#1373 Check if the name ends with whitespace
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/mixins.js
Labels: 3 - To Review, bug-solved

#1235 Enable sharing sidebar only if sharing is enabled
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileList.vue
  apps/files/src/default.js
  src/Phoenix.vue
  src/components/Menu.vue
  src/store/user.js
Labels: 3 - To Review

#1447 Autofocus in oc-dialog
  apps/files/src/components/ocDialogPrompt.vue
Labels: 3 - To Review

#1444 Fix creation and upload of files in root folder
  apps/files/src/components/FilesAppBar.vue
Labels: 3 - To Review, bug-solved

#1456 Fixed height of app content
  apps/files/src/components/FilesApp.vue
Labels: 3 - To Review, bug-solved

#1454 Adding version, git hash and build time to menu
  .gitignore
  package.json
  src/components/Menu.vue
  src/version.ejs
  webpack.common.js
  yarn.lock
Labels: 3 - To Review

#1406 Feature/implement trashbin acceptance tests
  .drone.yml
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/Trashbin.vue
  apps/files/src/store/actions.js
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/trashbinPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/loginContext.js
Labels: 3 - To Review

#1470 Update dependencies 20190709
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review

#1478 Use the same messages - less work for translators then
  apps/files/src/mixins.js
Labels: 3 - To Review

#1490 Remove webpack-phoenix-integration - left over which is no longer needed
  apps/files/webpack.common.js
  apps/pdf-viewer/webpack.common.js
  webpack-phoenix-integration.js
Labels: 3 - To Review

#1489 Do not import root config in files app - this bundles not properly tr…
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/default.js
  src/store/config.js
Labels: 3 - To Review

#1493 Support deleting multiple files in files app
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/yarn.lock
  yarn.lock
Labels: 3 - To Review

#1477 remember created users
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/helpers/httpHelper.js
  tests/acceptance/helpers/userSettings.js
  tests/acceptance/stepDefinitions/loginContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1451 Unfavourite files with same names in favourites page
  apps/files/src/store/mutations.js
Labels: 3 - To Review, bug-solved

#1498 Set disableHostCheck: true to allow any host in requests - helps to t…
  webpack.dev.js
Labels: 3 - To Review

#1494 Feature/open sidebar on row select
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileInfoSidebar.vue
  apps/files/src/components/FileInfoVersions.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/ocDialogPrompt.vue
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
Labels: 3 - To Review

#1452 Test for renaming to existing name and closing alert
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/stepDefinitions/messagesContext.js
  yarn.lock
Labels: 3 - To Review, Acceptance tests

#1501 Allow overwrite in file upload in case the file already exists
  apps/files/src/FileUpload.js
  apps/files/src/components/FileDrop.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
Labels: 2 - Developing

#1506 Stop loading if search failed
  apps/files/src/components/FilesAppBar.vue
Labels: 3 - To Review, bug-solved

#1499 use MySQL for acceptance tests
  .drone.yml
Labels: Acceptance tests, QA-team

#1515 Use oids from git because of latest bugfix
  package.json
  yarn.lock
Labels: 3 - To Review

#1521 Skip failing trashbin test due to file lock issue
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#1514 Add tests for deleting multiple files/folder at once
  apps/files/src/components/FileList.vue
  tests/acceptance/customCommands/toggleCheckbox.js
  tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1423 Moved load folder methods into related components
  apps/files/src/components/FileFilterMenu.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/Trashbin.vue
  tests/acceptance/pageObjects/phoenixPage.js
Labels: 3 - To Review, technical debt

#1519 Reimplementation for renaming a file to "." and ".."
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
Labels: 3 - To Review, QA-team

#1513 improve sharing autocomplete tests
  tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
  tests/acceptance/helpers/userSettings.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: Acceptance tests, QA-team

#1520 Add trashbin related tests
  package.json
  tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/webdavContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1503 adding password, displayname, email in given step where users are created but not initialized
  tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 2 - Developing, Acceptance tests, QA-team

#1534 Update deps 20190716
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review

#1264 Feature/private link
  apps/files/package.json
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/PrivateLink.vue
  apps/files/src/default.js
  apps/files/src/store/actions.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  package.json
  src/phoenix.js
  src/router/index.js
  yarn.lock
Labels: 3 - To Review

#1518 Added limit for messages and transition
  src/components/MessageBar.vue
Labels: 3 - To Review, enhancement

#1572 Removed item from files-list in navItems
  apps/files/src/components/FileList.vue
  apps/files/src/default.js
Labels: 3 - To Review, bug-solved

#1389 Collaborators
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/default.js
  apps/files/src/store/actions.js
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
  yarn.lock
Labels: 3 - To Review, enhancement

#1584 Change title of rename dialog
  apps/files/src/components/FileList.vue
  apps/files/src/mixins.js
Labels: 3 - To Review, enhancement

#1581 Fixed cancel action of overwrite dialog
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/ocDialogPrompt.vue
  apps/files/src/mixins.js
Labels: 3 - To Review, bug-solved

#1580 Check if file already exists
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/ocDialogPrompt.vue
  tests/acceptance/features/webUIFiles/createFolders.feature
Labels: 3 - To Review, enhancement

#1517 Allow alerts to be stacked under each other
  src/store/app.js
Labels: 3 - To Review, enhancement

#1565 trashbin features
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
  tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team

#1588 Fixed opening group accordion in collaborators
  apps/files/src/components/FileSharingSidebar.vue
Labels: 3 - To Review, bug-solved

#1530 Mediaviewer app
  .gitignore
  Makefile
  apps/media-viewer/l10n/.tx/config
  apps/media-viewer/l10n/translations.json
  apps/media-viewer/package.json
  apps/media-viewer/src/Mediaviewer.vue
  apps/media-viewer/src/app.js
  apps/media-viewer/webpack.common.js
  apps/media-viewer/webpack.dev.js
  apps/media-viewer/yarn.lock
  l10n/Makefile
  src/mixins/imageSrc.js
  src/phoenix.js
  src/plugins/mediaSource.js
Labels: 3 - To Review

#1597 Build requires the git folder to determine the commit hash
  .dockerignore
Labels: 3 - To Review

#1599 No eslint in apps
  apps/files/package.json
  apps/files/webpack.common.js
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/media-viewer/package.json
  apps/media-viewer/webpack.common.js
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/webpack.common.js
  apps/pdf-viewer/yarn.lock
Labels: 3 - To Review

#1596 Disable caching for all Phoenix deliverables
  .htaccess
Labels: 3 - To Review

#1590 Test deleting collaborators
  apps/files/src/components/Collaborators/Collaborator.vue
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1618 Fixed error about missing variable MediaSource
  src/plugins/mediaSource.js
Labels: 3 - To Review, bug-solved

#1622 Use https://github.com/DeepDiver1975/oidc-client-js which has properl…
  package.json
  yarn.lock
Labels: 3 - To Review

#1625 Upgrade dependencies 20190725
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/yarn.lock
  yarn.lock
Labels: 3 - To Review

#1624 Load media-viewer
  tests/drone/config.json
Labels: 3 - To Review

#1619 Allow to set the oidc log level via config.json
  src/services/auth.js
Labels: 3 - To Review

#1582 Make name errors consistent
  apps/files/src/components/FileList.vue
  apps/files/src/components/ocDialogPrompt.vue
  apps/files/src/mixins.js
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
Labels: 3 - To Review, technical debt

#1627 Added missing config page
  src/pages/missingConfig.vue
  src/phoenix.js
  webpack.common.js
Labels: 3 - To Review

#1628 Properly set token in download request
  apps/media-viewer/src/Mediaviewer.vue
Labels: 3 - To Review

#1626 Re-init owncloud-sdk on token refresh
  src/store/user.js
Labels: 3 - To Review

#1566 Allow 4 concurrent delete operations
  .drone.yml
  apps/files/package.json
  apps/files/src/components/Trashbin.vue
  apps/files/yarn.lock
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
  yarn.lock
Labels: 3 - To Review

#1615 Added custom role
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/Collaborators/mixins.js
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
Labels: 3 - To Review

#1639 Select multiple users/groups in collaborators
  apps/files/src/components/FileSharingSidebar.vue
Labels: 3 - To Review, enhancement

#1631 Fixed translations warning in rename title
  apps/files/src/mixins.js
Labels: 3 - To Review, bug-solved

#1659 Hide resharerer
  apps/files/src/components/Collaborators/Collaborator.vue
Labels: 3 - To Review, bug-solved

#1600 Search collaborators also by id
  apps/files/src/components/FileSharingSidebar.vue
  tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, bug-solved

#1662 Don't show items in autocomplete if they already exist
  apps/files/src/components/FileSharingSidebar.vue
Labels: 3 - To Review, bug-solved

#1664 Updated config.json.sample
  config.json.sample
Labels: 3 - To Review, technical debt

#1661 Allow save after clicking on permissions
  apps/files/src/components/Collaborators/mixins.js
Labels: 3 - To Review, bug-solved

#1668 Added getter for token into mixins
  apps/files/src/mixins.js
Labels: 3 - To Review, bug-solved

#1669 Switch to master-qa tar ball for the server
  .drone.yml
Labels: 3 - To Review
