Repository owncloud/web, pull requests merged in 2019-12, with the labels that each got.

#2580 Acceptance test: check for the tabs displayed in details of public share page
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 4 - To release, QA-team

#2570 Upgrade all libs
  apps/draw-io/yarn.lock
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 2 - Developing, Drone, QA-p1, QA-team

#2595 Update: run acceptance test with newer nodejs version
  .drone.starlark
  .drone.yml
Labels: 3 - To Review, QA-team

#2530 Selecting breadcrumb and reloading inside problematic folder
  tests/acceptance/features/webUIFiles/breadcrumb.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
Labels: 3 - To Review, dev:acceptance-tests

#2577 Refactoring files-page page object for assertion management
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, QA-team, refactoring

#2612 Retry clicking on delete immediately popup in trashbin
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
Labels: 3 - To Review, QA-team

#2578 Refactoring publicLinksDialog page-object for assertion management
  tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
Labels: 3 - To Review, QA-team, refactoring

#2621 Refactor ownCloudLoginPage for assertion management
  tests/acceptance/pageObjects/ownCloudLoginPage.js
  tests/acceptance/stepDefinitions/loginContext.js
Labels: 3 - To Review, QA-team, refactoring

#2647 correct step wording
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 4 - To release, QA-team, dev:acceptance-tests

#2502 Add acceptance tests for federation sharing
  .drone.starlark
  .drone.yml
  nightwatch.conf.js
  tests/acceptance/customCommands/setValueBySingleKeys.js
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/helpers/backendHelper.js
  tests/acceptance/helpers/occHelper.js
  tests/acceptance/helpers/userSettings.js
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/stepDefinitions/generalContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
  tests/acceptance/stepDefinitions/webdavContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#2287 Responsive trashbin table
  apps/files/src/components/Trashbin.vue
Labels: 3 - To Review

#2652 Hide quota on external storage
  apps/files/src/components/AllFilesList.vue
Labels: 3 - To Review, enhancement

#2619 Refactor filesPage page-object for assertion management
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team, refactoring

#2592 Add acceptance test to filter files and folders using keyword in the files page
  tests/acceptance/features/webUIFiles/filter.feature
  tests/acceptance/helpers/filesFoldersHelper.js
  tests/acceptance/helpers/path.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#2680 Bugfix/no checkbox label in files list
  apps/files/src/components/FileList.vue
  apps/files/src/components/Trashbin.vue
  package.json
  yarn.lock
Labels: 3 - To Review, p1-urgent

#2584 Files sidebars can now be loaded as Web Components via the config file
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileSidebarWebComponent.vue
  apps/files/src/default.js
  package.json
  src/phoenix.js
Labels: 3 - To Review

#2707 pin selenium container version to 3.141.59-xenon
  .drone.starlark
  .drone.yml
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#2696 Updated ODS + related bugfixes
  apps/files/src/components/Collaborators/AdditionalPermissions.vue
  apps/files/src/components/FileFilterMenu.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/Trashbin.vue
  apps/files/src/components/ocDialogPrompt.vue
  package.json
  src/components/Avatar.vue
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/phoenixPage.js
  yarn.lock
Labels: 3 - To Review

#2671 Refactor publicLinkPasswordPage for assertion management
  tests/acceptance/pageObjects/publicLinkPasswordPage.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
Labels: 3 - To Review, QA-team, refactoring

#2542 Add focus management for uploads
  apps/files/src/components/FileUpload.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/UploadProgress.vue
  apps/files/src/mixins.js
Labels: 3 - To Review, Accessibility

#2617 Filter trashbin files folders using keyword
  tests/acceptance/features/webUITrashbin/trashbinFilter.feature
  tests/acceptance/helpers/filesFoldersHelper.js
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#2622 Fix aspects of share flow accessibility
  apps/files/src/components/Collaborators/NewCollaborator.vue
  apps/files/src/components/FileSharingSidebar.vue
Labels: 3 - To Review, Accessibility

#2651 File actions can be defined using config settings
  apps/files/src/components/FileOpenActions.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/default.js
  apps/files/src/fileactions.js
  src/store/apps.js
Labels: 3 - To Review

#2708 Filter shared with others resources using keyword
  tests/acceptance/features/webUISharingNotifications/sharedWithMeFilter.feature
  tests/acceptance/features/webUISharingNotifications/sharedWithOthersFilter.feature
  tests/acceptance/helpers/filesFoldersHelper.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#2280 Files table virtual scroller
  apps/files/package.json
  apps/files/src/components/AllFilesList.vue
  apps/files/src/components/Collaborators/SharedFilesList.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesLists/RowActionsDropdown.vue
  apps/files/src/components/Trashbin.vue
  apps/files/src/store/actions.js
  apps/files/src/store/mutations.js
  apps/files/webpack.common.js
  apps/files/yarn.lock
  tests/acceptance/features/webUIFiles/breadcrumb.feature
  tests/acceptance/features/webUIFiles/fileDetails.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/sharedWithMePage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/privateLinksContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
  tests/acceptance/stepDefinitions/webdavContext.js
Labels: 3 - To Review, enhancement

#2725 Remove empty parentheses in shared with others list
  apps/files/src/components/Collaborators/SharedFilesList.vue
Labels: bug-solved

#2724 Fixed existing collaborators in autocomplete
  apps/files/src/components/Collaborators/NewCollaborator.vue
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroupsEdgeCases.feature
Labels: 3 - To Review, bug-solved

#2670 Refactor phoenixPage for assertion management
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/stepDefinitions/notificationsContext.js
Labels: 3 - To Review, QA-team, refactoring

#2618 Refactoring sharingDialog page-object for assertion management
  tests/acceptance/helpers/sharingHelper.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, QA-team, refactoring

#2672 Assertion refactor shared with me page
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
  tests/acceptance/pageObjects/sharedWithMePage.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, QA-team, refactoring

#2704 Edit the methods used in the acceptance tests to filter the resources using keyword
  tests/acceptance/helpers/filesFoldersHelper.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#2722 Remove duplicate methods to create new file in the acceptance test
  tests/acceptance/features/webUIFiles/createFile.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#2740 Test: unify configurations
  .drone.starlark
  .drone.yml
  nightwatch.conf.js
  package.json
  tests/acceptance/helpers/config.js
  tests/acceptance/helpers/occHelper.js
  tests/acceptance/setup-drone.js
  tests/acceptance/setup-local.js
  tests/acceptance/setup.js
Labels: 3 - To Review, QA-team, refactoring

#2721 Acceptance test to filter resources using keyword in the favourites page
  tests/acceptance/features/webUIFavorites/favoritesFilter.feature
  tests/acceptance/helpers/filesFoldersHelper.js
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#2669 Separate app switcher from app navigation sidebar
  config.json.dist
  config.json.sample
  src/Phoenix.vue
  src/components/ApplicationsMenu.vue
  src/components/Avatar.vue
  src/components/Menu.vue
  src/components/MessageBar.vue
  src/components/Top-Bar.vue
  src/components/UserMenu.vue
  src/phoenix.js
  src/store/app.js
  src/store/config.js
  tests/acceptance/helpers/loginHelper.js
  tests/acceptance/pageObjects/phoenixPage.js
Labels: 3 - To Review

#2742 Setup log for federated server in drone
  .drone.starlark
  .drone.yml
Labels: 3 - To Review, Drone, QA-team

#2751 Create enum like reference for file actions
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
Labels: 3 - To Review, QA-team

#2720 Implement all (except one) federation sharing tests
  .drone.starlark
  .drone.yml
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
  tests/acceptance/helpers/backendHelper.js
  tests/acceptance/helpers/sharingHelper.js
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
  tests/acceptance/stepDefinitions/notificationsContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
  tests/acceptance/stepDefinitions/webdavContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#2752 Timeouts async script
  tests/acceptance/setup.js
Labels: QA-team, dev:acceptance-tests

#2753 allow to set the selenium host by env. variable when running on saucelabs
  .drone.starlark
  .drone.yml
  nightwatch.conf.js
Labels: QA-team, dev:acceptance-tests

#2755 Fix typo of suite webUISharingPermissionMultipleUsers
  .drone.starlark
  .drone.yml
  tests/acceptance/features/webUISharingPermissionMultipleUsers/shareWithMultipleUsers.feature
Labels: 3 - To Review, Drone, QA-team

#2744 Use path join methods in fetch
  tests/acceptance/helpers/occHelper.js
  tests/acceptance/helpers/sharingHelper.js
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/pageObjects/accountPage.js
  tests/acceptance/pageObjects/favoritesPage.js
  tests/acceptance/pageObjects/filesDropPage.js
  tests/acceptance/pageObjects/loginPage.js
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/pageObjects/publicLinkFilesPage.js
  tests/acceptance/pageObjects/sharedWithMePage.js
  tests/acceptance/pageObjects/sharedWithOthersPage.js
  tests/acceptance/pageObjects/trashbinPage.js
  tests/acceptance/stepDefinitions/generalContext.js
  tests/acceptance/stepDefinitions/notificationsContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#2757 do not run IE11 tests
  .drone.starlark
  .drone.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#2788 Refactor test scenarios written for filter feature
  tests/acceptance/features/webUIFavorites/favoritesFilter.feature
  tests/acceptance/features/webUIFiles/filter.feature
  tests/acceptance/features/webUISharingNotifications/sharedWithMeFilter.feature
  tests/acceptance/features/webUISharingNotifications/sharedWithOthersFilter.feature
  tests/acceptance/features/webUITrashbin/trashbinFilter.feature
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests
