Repository owncloud/web, pull requests merged in 2019-05, with the labels that each got.

#1054 first upload tests
  nightwatch.conf.js
  package.json
  tests/acceptance/customCommands/uploadLocalFile.js
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/filesForUpload/'single'quotes.txt
  tests/acceptance/filesForUpload/data.tar.gz
  tests/acceptance/filesForUpload/data.zip
  tests/acceptance/filesForUpload/davtest.txt
  tests/acceptance/filesForUpload/file_to_overwrite.txt
  tests/acceptance/filesForUpload/lorem-big.txt
  tests/acceptance/filesForUpload/lorem.txt
  tests/acceptance/filesForUpload/new-'single'quotes.txt
  tests/acceptance/filesForUpload/new-data.tar.gz
  tests/acceptance/filesForUpload/new-data.zip
  tests/acceptance/filesForUpload/new-lorem-big.txt
  tests/acceptance/filesForUpload/new-lorem.txt
  tests/acceptance/filesForUpload/new-strängé filename (duplicate #2 &).txt
  tests/acceptance/filesForUpload/simple.odt
  tests/acceptance/filesForUpload/simple.pdf
  tests/acceptance/filesForUpload/strängé filename (duplicate #2 &).txt
  tests/acceptance/filesForUpload/testavatar.jpg
  tests/acceptance/filesForUpload/testavatar.png
  tests/acceptance/filesForUpload/textfile.txt
  tests/acceptance/filesForUpload/zzzz-must-be-last-file-in-folder.txt
  tests/acceptance/filesForUpload/zzzz-zzzz-will-be-at-the-end-of-the-folder-when-uploaded.txt
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
  tests/acceptance/stepDefinitions/webdavContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1020 Apply basic sorting to file list
  apps/files/src/store/getters.js
Labels: 3 - To Review

#1055 upload test for edge cases and big files
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/generalContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1058 Used oc-nav-item component
  apps/files/src/components/FileUpload.vue
Labels: 3 - To Review, bug-solved

#928 Add some more information about a file in the side bar header
  apps/files/src/components/FileDetails.vue
Labels: 3 - To Review

#1050 Add tests for file/folder filter
  tests/acceptance/customCommands/toggleCheckbox.js
  tests/acceptance/features/webUIFiles/filter.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team

#1061 Use jsDoc string in test code functions
  tests/acceptance/customCommands/toggleCheckbox.js
  tests/acceptance/customCommands/uploadLocalFile.js
  tests/acceptance/helpers/httpHelper.js
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/phoenixPage.js
Labels: 3 - To Review, Acceptance tests, QA-team

#633 Use If-Not-Match: * to prevent overwrite of new uploaded file
  apps/files/src/components/FilesTopBar.vue
Labels: 3 - To Review

#1066 Add tests for file/folder favorite
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team

#1067 Fixed notifications status prop
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesTopBar.vue
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
  apps/pdf-viewer/src/PdfViewer.vue
Labels: 3 - To Review, bug-solved

#1042 Feature/add sharing sidebar
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  src/phoenix.js
Labels: 3 - To Review

#1079 Only run build docker image on merge
  .drone.yml
Labels: 3 - To Review, QA-team

#1068 Add drone matrix to run tests in parallel
  .drone.yml
  package.json
Labels: 3 - To Review, QA-team

#1083 Add missing matrix for run build-docker-image only after job
  .drone.yml
Labels: 3 - To Review, QA-team

#1060 tests for upload that would exceed the quota
  tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
  tests/acceptance/helpers/httpHelper.js
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1084 Fix auth url in config.json sample
  config.json.dist
  config.json.sample
Labels: 3 - To Review, QA-team

#1085 Upgraded dependencies
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review, dependencies

#1089 Bugfix/collapse screenshots on GitHub
  .drone.yml
Labels: 3 - To Review

#1093 Tech dept/modules cleanup
  package.json
  static/config.default.json
  static/fonts/ocft/css/ocft.css
  static/fonts/ocft/font/ocft.eot
  static/fonts/ocft/font/ocft.svg
  static/fonts/ocft/font/ocft.ttf
  static/fonts/ocft/font/ocft.woff
  static/fonts/ocft/font/ocft.woff2
  static/fonts/ocft/icons/README.txt
  webpack.common.js
  yarn.lock
Labels: 3 - To Review

#1088 Fix usage of interpolated strings in gettext
  apps/files/src/components/FileList.vue
  apps/files/src/mixins.js
Labels: 3 - To Review

#1092 Moved strings inside of components
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/components/ocDialogPrompt.vue
  src/components/Menu.vue
  src/pages/login.vue
  tests/acceptance/pageObjects/filesPage.js
Labels: 3 - To Review, bug-solved

#1087 Use OAuth/OpenIDConnect redirect uri without fragment
  .drone.yml
  oidc-callback.html
  oidc-silent-redirect.html
  src/services/auth.js
  webpack.prod.js
Labels: 3 - To Review

#1100 Update deps 20190509
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review

#1101 Added vue2-dropzone package
  package.json
  yarn.lock
Labels: 3 - To Review, bug-solved

#1080 Refactor
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesTopBar.vue
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
Labels: 3 - To Review

#1105 Fix drone error on creating folder
  tests/acceptance/pageObjects/filesPage.js
Labels: 3 - To Review, QA-team

#1110 index.html needs to be cut from the url when building the redirect uri
  src/services/auth.js
Labels: 3 - To Review

#1086 Added error description
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesTopBar.vue
  src/components/NotificationBar.vue
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/phoenixPage.js
  yarn.lock
Labels: 3 - To Review, bug-solved

#1069 Prevent rename to existing name
  apps/files/src/mixins.js
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
Labels: 3 - To Review, bug-solved

#1091 gradually hide fileList elements as width shrinks
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
Labels: 3 - To Review, design

#1120 Redirect uri need to point to absolute paths and need to include inde…
  oidc-callback.html
  oidc-silent-redirect.html
Labels: 3 - To Review

#1128 Removed lodash
  apps/files/package.json
  apps/files/src/components/FileInfoSidebar.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
  apps/files/src/store/mutations.js
  package.json
  src/mixins/pluginHelper.js
  src/phoenix.js
  src/store/app.js
  src/store/apps.js
  yarn.lock
Labels: 3 - To Review

#1124 Added scroll to apps and removed stickiness
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesTopBar.vue
  src/Phoenix.vue
  src/components/Top-Bar.vue
Labels: 3 - To Review, enhancement

#1130 Upgraded dependencies
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review, dependencies

#1102 Add group sharing
  .gitignore
  apps/files/src/components/FileList.vue
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/default.js
  apps/files/src/store/actions.js
  src/services/auth.js
  tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/loginContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review

#1149 Set String types instead of null values in config store
  src/store/config.js
Labels: 3 - To Review

#1166 Add tests for sharing
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/loginContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, QA-team

#1178 Upgraded dependencies
  package.json
  yarn.lock
Labels: 3 - To Review, dependencies

#1148 Created favorites page
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesTopBar.vue
  apps/files/src/default.js
  apps/files/src/store/actions.js
  src/components/Menu.vue
Labels: 3 - To Review, enhancement, feature:files

#1190 acceptance-test/implement default user creation
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/helpers/httpHelper.js
  tests/acceptance/helpers/userSettings.js
  tests/acceptance/stepDefinitions/loginContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: 3 - To Review, QA-team

#1167 Replaced remove with splice to close notifications
  src/components/NotificationBar.vue
  src/store/app.js
Labels: 3 - To Review, bug-solved

#1196 more tests for favorites feature
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/pageObjects/favoritesPage.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/loginContext.js
  tests/acceptance/stepDefinitions/webdavContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1195 Personal settings
  src/components/Menu.vue
  src/components/Top-Bar.vue
  src/pages/account.vue
  src/router/index.js
Labels: 3 - To Review, enhancement

#1108 Validate folder names
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesTopBar.vue
  apps/files/src/components/ocDialogPrompt.vue
  tests/acceptance/features/webUIFiles/createFolders.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
Labels: 3 - To Review

#1202 Moved dropzone trigger into files list wrapper
  apps/files/src/components/FilesApp.vue
Labels: 3 - To Review, bug-solved

#1203 Close menu after change of route
  src/components/Menu.vue
Labels: 3 - To Review, bug-solved
