Repository owncloud/web, pull requests merged in 2019-01, with the labels that each got.

#452 allow custom credentials in acceptance-tests
  README.md
  tests/acceptance/stepDefinitions/loginContext.js
Labels: To Review, enhancement

#445 Improve webpack to build to /dist folder instead of /build
  .drone.yml
  .gitignore
  Makefile
  Makefile.release
  README.md
  apps/files/package.json
  apps/files/webpack.common.js
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/webpack.config.js
  apps/markdown-editor/yarn.lock
  build.js
  index.html
  package.json
  src/default.js
  themes/owncloud/favicon.jpg
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: To Review, dependencies, enhancement, help wanted, requirement

#478 bump all core npm dependencies
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  package.json
  yarn.lock
Labels: dependencies

#489 bump webpack as core dependency
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  package.json
  yarn.lock
Labels: dependencies

#503 Fix totalSize showing 0 bytes on FileInfoSidebar
  apps/files/src/components/FileInfoSidebar.vue
Labels: To Review, bug

#504 hide upload details and show correct progress
  apps/files/src/FileUpload.js
  apps/files/src/components/FileUpload.vue
  apps/files/src/components/FileUploadProgress.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/store.js
Labels: To Review, design, enhancement, requirement

#510 bumped pdf-viwer dependencies
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
Labels: To Review, dependencies

#512 bump vuex as core dependencies
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  package.json
  yarn.lock
Labels: dependencies

#527 Apply eslint to tests as well
  package.json
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/loginPage.js
  tests/acceptance/pageObjects/ownCloudAuthorizePage.js
  tests/acceptance/pageObjects/ownCloudLoginPage.js
  tests/acceptance/setup-drone.js
  tests/acceptance/setup-local.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/loginContext.js
Labels: 3 - To Review

#521 fix whitescreen of death
  src/components/Top-Bar.vue
  src/default.js
  src/pages/login.vue
  src/store/config.js
  static/config.default.json
  themes/owncloud.json
  webpack.common.js
Labels: bug-solved, tested

#528 Use docker plugin to build the image
  .drone.yml
Labels: 3 - To Review

#541 remove less and sass loader
  Dockerfile
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  webpack.common.js
  yarn.lock
Labels: enhancement

#550 Fix missing Top Menu in Markdown-Editor
  apps/markdown-editor/src/MarkdownEditor.vue
Labels: bug-solved

#502 Add feature file for createFolders tests
  package.json
  tests/acceptance/features/webUIFiles/createFolders.feature
  tests/acceptance/features/webUILogin/login.feature
Labels: 3 - To Review

#505 Add feature files for filesApp tests
  tests/acceptance/features/webUIFiles/createFolderEdgeCases.feature
  tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
  tests/acceptance/features/webUIFiles/fileDetails.feature
  tests/acceptance/features/webUIFiles/hiddenFile.feature
  tests/acceptance/features/webUIFiles/scrollMenuIntoView.feature
Labels: 3 - To Review

#562 bump vue-loader
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: dependencies

#525 Switch OAuth/OpenId Connect library
  .drone.yml
  package.json
  src/default.js
  src/pages/oidcCallback.vue
  src/pages/oidcSilentRedirect.vue
  src/router/index.js
  src/services/auth.js
  src/store/config.js
  src/store/user.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/loginContext.js
  webpack.common.js
  yarn.lock
Labels: 3 - To Review

#570 remove race condition in acceptance tests
  tests/acceptance/features/webUILogin/login.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/loginContext.js
Labels: bug-analysis

#571 fix typo in github repo url
  .github/settings.yml
Labels: bug-solved

#572 remove encoded slash from file uri & allow directory deep links
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
  src/store/user.js
Labels: bug-solved

#581 Set link to open Phoenix right away ...
  .github/settings.yml
Labels: 3 - To Review
