Repository owncloud/web, pull requests merged in 2019-06, with the labels that each got.

#753 Feature/support ie11
  .babelrc
  .browserslistrc
  apps/files/.babelrc
  apps/files/package.json
  apps/files/src/FileUpload.js
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileDrop.vue
  apps/files/src/default.js
  apps/files/src/mixins.js
  apps/files/webpack.common.js
  apps/files/yarn.lock
  apps/markdown-editor/.babelrc
  apps/markdown-editor/webpack.config.js
  apps/pdf-viewer/.babelrc
  apps/pdf-viewer/webpack.common.js
  babel.config.js
  index.html
  package.json
  src/pages/error.vue
  src/phoenix.js
  src/store/app.js
  src/store/apps.js
  src/store/config.js
  src/store/index.js
  src/store/user.js
  webpack-phoenix-integration.js
  webpack.common.js
  yarn.lock
Labels: 3 - To Review

#1211 Update dependencies 20190603
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review

#1204 Fixed link for files list
  apps/files/src/default.js
Labels: 3 - To Review, bug-solved

#1253 Made sidebar wider and added padding
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FilesApp.vue
Labels: 3 - To Review

#1260 use pre-latests selenium
  .drone.yml
Labels: 3 - To Review, Acceptance tests, QA-team

#1261 Update deps 20190606
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review

#1256 Fixes #1250 - fix download of a file version
  apps/files/src/components/FileInfoVersions.vue
Labels: 3 - To Review

#1255 Fixes #1232 - use item.type instead of item.extension to determine th…
  apps/files/src/components/FileList.vue
Labels: 3 - To Review

#1245 Fixes #1238 - no detailed files and proper naming of side bar if mult…
  apps/files/src/components/FileDetails.vue
  apps/files/src/default.js
Labels: 3 - To Review

#1244 properly encode the path in breadcrumbs
  apps/files/src/components/FilesTopBar.vue
Labels: 3 - To Review

#1263 Fixes #1259 - break text in prompt dialog
  apps/files/src/components/ocDialogPrompt.vue
Labels: 3 - To Review

#1265 Added actions for small resolution
  apps/files/src/components/FileList.vue
Labels: 3 - To Review

#1266 Added automatic lint after commit
  package.json
  yarn.lock
Labels: 3 - To Review

#1272 Skip rename when user didn't change the file/folder name
  apps/files/src/mixins.js
Labels: 3 - To Review

#1207 retry failing acceptance tests
  package.json
Labels: 3 - To Review, Acceptance tests, QA-team

#1286 Add test step to assert the number of files/folders in webUI
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team

#1287 run UI tests in chrome 75
  .drone.yml
  nightwatch.conf.js
  tests/acceptance/stepDefinitions/loginContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1293 Check for quota
  apps/files/src/components/FilesTopBar.vue
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
Labels: 3 - To Review

#1295 On logout trigger OAuth/OpenIdConnect sign-out-url
  src/services/auth.js
  src/store/user.js
Labels: 3 - To Review

#1305 Update deps 20190613
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review

#1311 Disable confirm event if oc dialog input value is empty
  apps/files/src/components/ocDialogPrompt.vue
Labels: 3 - To Review

#1309 Fix loading of file versions
  apps/files/src/components/FilesApp.vue
Labels: 3 - To Review, bug-solved

#1310 Fixed markdown app topbar offset
  apps/markdown-editor/src/MarkdownEditorTopbar.vue
Labels: 3 - To Review

#1308 fix phoenix build
  Dockerfile
Labels: 3 - To Review, bug

#1313 Fix callback page
  src/store/user.js
Labels: 3 - To Review, bug-solved

#1275 Load favorite page without items
  apps/files/src/store/actions.js
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
Labels: 3 - To Review

#1332 parse viewer role properly
  apps/files/src/store/actions.js
Labels: 3 - To Review, bug

#1340 improve test stability
  nightwatch.conf.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/pageObjects/favoritesPage.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/loginContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1331 Feature/app top bar
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/default.js
  apps/markdown-editor/src/MarkdownEditor.vue
  apps/markdown-editor/src/MarkdownEditorAppBar.vue
  apps/markdown-editor/src/MarkdownEditorTopbar.vue
  apps/markdown-editor/src/app.js
  apps/pdf-viewer/src/PdfViewer.vue
  apps/pdf-viewer/src/PdfViewerAppBar.vue
  apps/pdf-viewer/src/app.js
  package.json
  src/Phoenix.vue
  src/router/index.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/phoenixPage.js
  themes/example.json
  themes/owncloud.json
  yarn.lock
Labels: 3 - To Review, enhancement, feature:files, feature:markdown-editor, feature:pdf-viewer

#1341 show link to drone job when tests failed
  .drone.yml
Labels: 3 - To Review, 4 - To release, Acceptance tests, QA-team

#1346 Upgraded dependencies
  package.json
  yarn.lock
Labels: 3 - To Review, dependencies

#1345 unskip tests that were skipped because of #1270
  tests/acceptance/features/webUIFiles/hiddenFile.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
  tests/acceptance/pageObjects/phoenixPage.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1349 Added error handling
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/store/actions.js
Labels: 3 - To Review

#1364 Updated deps
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review, dependencies

#1314 Added parent folder before name of favorite files
  apps/files/src/components/FileList.vue
Labels: 3 - To Review, enhancement

#1371 Add tests for going back to files page
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1372 delete unneeded code
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: Acceptance tests, QA-team

#1374 Check if the name is equal to . or ..
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/mixins.js
Labels: 3 - To Review, bug-solved
