Repository owncloud/web, pull requests merged in 2019-08, with the labels that each got.

#1663 Search by email
  apps/files/src/components/FileSharingSidebar.vue
Labels: 3 - To Review, enhancement

#1670 Add public link display
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileInfoVersions.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/PublicLinks/PublicLink.vue
  apps/files/src/default.js
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/media-viewer/src/Mediaviewer.vue
  apps/media-viewer/src/app.js
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/yarn.lock
  package.json
  src/components/Top-Bar.vue
  src/phoenix.js
  src/plugins/mediaSource.js
  src/plugins/phoenix.js
  src/router/index.js
  yarn.lock
Labels: 2 - Developing

#1682 Fix process of collaborators
  apps/files/src/components/Collaborators/AutocompleteItem.vue
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/Collaborators/NewCollaborator.vue
  apps/files/src/components/Collaborators/mixins.js
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  package.json
Labels: 3 - To Review

#1690 Current folder in breadcrumbs leads to reload
  apps/files/src/components/FilesAppBar.vue
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/yarn.lock
  yarn.lock
Labels: 3 - To Review

#1691 FileList: clicking on a disabled button shall not open the sidebar
  apps/files/src/components/FileList.vue
Labels: 3 - To Review

#1694 Use vue-meta to set the page title to the name on the theme and to se…
  index.html
  package.json
  src/Phoenix.vue
  src/phoenix.js
  src/store/config.js
  themes/owncloud.json
  themes/owncloud/background.jpg
  themes/owncloud/cloud-logo-invert.svg
  webpack.common.js
  yarn.lock
Labels: 3 - To Review

#1695 Added icons as placeholders for collaborators
  apps/files/src/components/Collaborators/AutocompleteItem.vue
  apps/files/src/components/Collaborators/mixins.js
  package.json
  yarn.lock
Labels: 3 - To Review

#1696 PublicLinks: allow upload and creation of files and folders
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
  package.json
  yarn.lock
Labels: 3 - To Review

#1701 Fixed actions in notifications
  src/components/Notifications.vue
Labels: 3 - To Review

#1711 Feature/fav breadcrumb
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/default.js
  apps/files/src/store/actions.js
  src/phoenix.js
  yarn.lock
Labels: 3 - To Review

#1729 convert .drone.yml to drone 1.0
  .drone.yml
Labels: Acceptance tests, QA-team

#1737 Renamed perms key to permissions
  apps/files/src/components/Collaborators/NewCollaborator.vue
  apps/files/src/store/actions.js
Labels: 3 - To Review, bug-solved

#1755 Block more then one click when deleting
  apps/files/src/components/ocDialogPrompt.vue
Labels: 3 - To Review

#1759 Block more then one click
  apps/files/src/components/ocDialogPrompt.vue
Labels: 3 - To Review

#1765 Change icon in sidebar after selecting different item
  apps/files/src/components/FileDetails.vue
Labels: 3 - To Review, bug-solved

#1764 Hide versions tab for folders
  apps/files/src/components/FileDetails.vue
  apps/files/src/default.js
Labels: 3 - To Review, bug-solved

#1776 user MySQL server as database
  .drone.yml
Labels: 3 - To Review, Acceptance tests, QA-team

#1778 Define active tab by name instead of key
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileList.vue
Labels: 3 - To Review, bug-solved

#1739 Respect folder structure when uploading
  apps/files/src/components/FileDrop.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/FolderUpload.vue
  apps/files/src/mixins.js
Labels: 3 - To Review

#1702 Shared with others list
  apps/files/src/components/Collaborators/SharedFilesList.vue
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/default.js
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
Labels: 3 - To Review, enhancement

#1773 test the files side-bar when clicking the file row
  apps/files/src/components/FileInfoVersions.vue
  tests/acceptance/features/webUIFiles/fileDetails.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#1654 Added params to the end of the list
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
Labels: 3 - To Review, enhancement

#1660 Show additional info
  apps/files/src/components/Collaborators/AutocompleteItem.vue
  apps/files/src/components/Collaborators/Collaborator.vue
Labels: 3 - To Review, enhancement

#1655 Feature / Links
  apps/files/src/components/FileLink.vue
  apps/files/src/components/FileLinkForm.vue
  apps/files/src/default.js
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  package.json
  tests/acceptance/features/webUIFiles/fileDetails.feature
  tests/acceptance/pageObjects/filesPage.js
  yarn.lock
Labels: 3 - To Review

#1735 Support translations of nav items and file actions
  apps/files/l10n/translations.json
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/Trashbin.vue
  apps/files/src/default.js
  apps/files/src/store/actions.js
  l10n/translations.json
  src/components/Menu.vue
Labels: 3 - To Review

#1797 delete unneeded steps for trashbin tests
  tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#1799 Bugfix/show images media viewer
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/yarn.lock
  src/plugins/mediaSource.js
  src/plugins/phoenix.js
  yarn.lock
Labels: 3 - To Review

#1777 Fix babel transpiling issues
  apps/files/webpack.common.js
Labels: 3 - To Review, bug

#1800 Check file id instead of share id in shared with others list
  apps/files/src/store/actions.js
Labels: 3 - To Review, bug-solved

#1761 check collaborators permissions
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/helpers/loginHelper.js
  tests/acceptance/helpers/sharingHelper.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/loginContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: QA-team

#1736 Reload versions after revert or selecting different file
  apps/files/src/components/FileInfoVersions.vue
Labels: 3 - To Review, bug-solved

#1784 Feature/file drop
  apps/files/src/components/PublicLinks/FilesDrop.vue
  apps/files/src/components/PublicLinks/PublicLink.vue
  apps/files/src/default.js
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/yarn.lock
  yarn.lock
Labels: 3 - To Review

#1809 Fixed download in Firefox
  src/plugins/phoenix.js
Labels: 3 - To Review

#1803 Shared with me list
  apps/files/src/components/Collaborators/SharedFilesList.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/default.js
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
Labels: 3 - To Review, enhancement

#1807 Close sidebar after delete action
  apps/files/src/mixins.js
Labels: 3 - To Review, bug-solved

#1810 Prevent scroll of file row actions
  apps/files/src/components/FileList.vue
  apps/files/src/mixins.js
Labels: 3 - To Review, bug-solved

#1811 Added avatars to collaborators list
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/Collaborators/mixins.js
  apps/files/src/components/FileSharingSidebar.vue
Labels: 3 - To Review, enhancement

#1826 Load groups in store
  src/store/user.js
Labels: 3 - To Review

#1830 Bugifx/no notification on copy private link
  apps/files/src/components/FileDetails.vue
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/yarn.lock
  yarn.lock
Labels: 3 - To Review

#1832 Introduce accedd-denied page and use it when login is failing
  src/pages/accessDenied.vue
  src/pages/error.vue
  src/router/index.js
  src/store/config.js
  src/store/user.js
Labels: 3 - To Review

#1834 Update messages on access denied page
  src/pages/accessDenied.vue
Labels: 3 - To Review

#1813 Trigger collaborator edit only after change
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/Collaborators/mixins.js
Labels: 3 - To Review, bug-solved

#1812 Add default selected role for new collaborators
  apps/files/src/components/Collaborators/NewCollaborator.vue
Labels: 3 - To Review, bug-solved

#1814 Move file action component to phoenix - remove UiKit javascript usage…
  apps/files/src/components/FileActions.vue
  apps/files/src/components/FilesApp.vue
Labels: 3 - To Review

#1754 Encode upload path
  apps/files/src/FileUpload.js
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/mixins.js
Labels: 3 - To Review

#1839 Unblock unfinished sharing input
  apps/files/src/components/FileSharingSidebar.vue
Labels: 3 - To Review

#1806 Fixed permissions of editor
  apps/files/src/components/Collaborators/NewCollaborator.vue
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
Labels: 3 - To Review, bug-solved

#1850 Focus search input when clicking search drop on mobile views
  apps/files/src/components/FilesAppBar.vue
Labels: 3 - To Review

#1847 Added no permission for reshare message
  apps/files/src/components/FileSharingSidebar.vue
Labels: 3 - To Review

#1846 tests for changing collaborators roles
  apps/files/src/components/Collaborators/Collaborator.vue
  tests/acceptance/customCommands/angryClick.js
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 4 - To release, Acceptance tests, QA-team

#1848 Update ODS dependency
  package.json
  yarn.lock
Labels: 3 - To Review

#1869 Ignore quota in external storage
  apps/files/src/components/FilesAppBar.vue
Labels: 3 - To Review

#1849 Upgraded deps and fixed lint issues
  apps/files/package.json
  apps/files/src/components/Collaborators/AutocompleteItem.vue
  apps/files/src/components/Collaborators/NewCollaborator.vue
  apps/files/src/components/PublicLinks/FilesDrop.vue
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/media-viewer/src/app.js
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/src/app.js
  apps/pdf-viewer/yarn.lock
  package.json
  src/mixins/pluginHelper.js
  src/store/user.js
  tests/acceptance/customCommands/waitForAjaxCallsToStartAndFinish.js
  tests/acceptance/customCommands/waitForOutstandingAjaxCalls.js
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
  yarn.lock
Labels: 3 - To Review, dependencies

#1870 Update README.md
  README.md
Labels: 3 - To Review, documentation

#1868 Allow sharing with remote users
  apps/files/src/components/Collaborators/AutocompleteItem.vue
  apps/files/src/components/Collaborators/NewCollaborator.vue
  apps/files/src/components/Collaborators/mixins.js
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/store/actions.js
Labels: 3 - To Review, enhancement

#1827 Extend link functionality
  apps/files/src/components/FileLink.vue
  apps/files/src/components/FileLinkForm.vue
  apps/files/src/store/actions.js
  package.json
  yarn.lock
Labels: 2 - Developing
