Repository owncloud/web, pull requests merged in 2019-09, with the labels that each got.

#1885 "update" permission changed to "change" permission to make it consistent with the webui
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/helpers/sharingHelper.js
Labels: 3 - To Review, QA-team

#1881 Added fixed width to alert messages
  src/components/MessageBar.vue
Labels: 3 - To Review

#1893 Enable click on search button on mobile
  apps/files/src/components/FilesAppBar.vue
Labels: 3 - To Review, bug-solved

#1898 Add setup about tech preview APIs in server core
  README.md
Labels: 3 - To Review

#1895 Add download feedback
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesAppBar.vue
  src/plugins/phoenix.js
Labels: 3 - To Review, enhancement

#1921 Adjusted version and changelog for 0.2.1 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To Review

#1922 add dav.enable.tech_preview to CI runs
  .drone.yml
Labels: Acceptance tests, QA-team

#1937 Upgraded deps
  apps/files/package.json
  apps/files/yarn.lock
  apps/markdown-editor/package.json
  apps/markdown-editor/yarn.lock
  apps/media-viewer/package.json
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/package.json
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review, dependencies

#1838 collaborators tests added
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, QA-team

#1940 Adjusted access denied template
  src/pages/accessDenied.vue
Labels: 3 - To Review

#1939 Fix redirect to access denied page
  src/store/user.js
Labels: 3 - To Review, bug-solved

#1946 Render full file path in trashbin
  apps/files/src/components/Trashbin.vue
Labels: 3 - To Review

#1945 Notifications now fully visible on small screens
  src/components/Notifications.vue
Labels: 3 - To Review

#1949 Add bookmarks to nav menu
  src/components/Menu.vue
  src/phoenix.js
Labels: 3 - To Review

#1968 Adjust changelog and version for the new release
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 3 - To Review

#1886 acceptance tests for public links
  apps/files/src/components/FileLinkForm.vue
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/helpers/sharingHelper.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/pageObjects/publicLinkFilesPage.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, QA-team

#1984 Set X-Requested-With header - required ownCloud 10.3
  src/store/user.js
Labels: 3 - To Review

#1981 test sharing a file via public link
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#1985 Fix public link permissions mix up
  apps/files/src/components/FileLinkForm.vue
  apps/files/src/store/actions.js
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
Labels: 3 - To Review

#1994 Add acceptance tests for shared with me and shared with others page
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/sharedWithMePage.js
  tests/acceptance/pageObjects/sharedWithOthersPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/loginContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2007 Downgrade vuex-persist to 2.0.1 to fix IE11 issues
  package.json
  yarn.lock
Labels: 3 - To Review

#2011 Handle OAuth/OpenIdConnect error in callback request query string
  src/pages/oidcCallback.vue
Labels: 3 - To Review

#1986 Enable loading apps from external sites
  package.json
  src/phoenix.js
  src/store/apps.js
Labels: 3 - To Review

#2015 Adjusted changelog and version for 0.2.3
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 3 - To Review

#2071 Use sharetype keys that are human readable instead of number
  tests/acceptance/helpers/sharingHelper.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2072 In case of error in the auth flow no logout is performed automaticall…
  src/store/user.js
Labels: 3 - To Review

#2073 Hide comma before mdate if size is in pending state
  apps/files/src/components/FileDetails.vue
Labels: 3 - To Review, bug-solved

#2079 In case of auth errors (access denied, invalid token or cannot refres…
  src/services/auth.js
  src/store/user.js
Labels: 3 - To Review

#2009 Add a private link for the current folder to the app bar
  apps/files/src/components/FilesAppBar.vue
  tests/acceptance/customCommands/getClipBoardContent.js
  tests/acceptance/features/webUIFiles/copyPrivateLinks.feature
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review

#2096 Fix files drop when link password is set
  apps/files/src/components/PublicLinks/FilesDrop.vue
Labels: 3 - To Review

#2097 Fix detection of public pages despite existing auth
  src/plugins/phoenix.js
Labels: 3 - To Review, p2-high

#2086 IE11 support for media-viewer
  apps/media-viewer/webpack.common.js
Labels: 3 - To Review

#2091 Fix typos
  .github/issue_template.md
Labels: 3 - To Review
