Repository owncloud/web, pull requests merged in 2019-10, with the labels that each got.

#2089 run phoenix on apache for UI tests
  .drone.yml
  nightwatch.conf.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2105 Remove unused password arg from webdav.propfind
  tests/acceptance/helpers/webdavHelper.js
Labels: 3 - To Review, Acceptance tests

#2083 Feature/drawio integration
  .gitignore
  apps/draw-io/.gitignore
  apps/draw-io/l10n/.tx/config
  apps/draw-io/l10n/translations.json
  apps/draw-io/package.json
  apps/draw-io/src/DrawIoEditor.vue
  apps/draw-io/src/app.js
  apps/draw-io/webpack.common.js
  apps/draw-io/webpack.dev.js
  apps/draw-io/yarn.lock
  apps/files/src/components/FilesApp.vue
  src/store/apps.js
  tests/drone/config.json
Labels: 3 - To Review

#2100 Added logout step for acceptance tests
  src/components/Menu.vue
  tests/acceptance/features/webUILogin/login.feature
  tests/acceptance/helpers/loginHelper.js
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/stepDefinitions/loginContext.js
Labels: 3 - To Review

#2109 Refactor login helper into respective page objects
  tests/acceptance/helpers/loginHelper.js
  tests/acceptance/pageObjects/loginPage.js
  tests/acceptance/pageObjects/ownCloudAuthorizePage.js
  tests/acceptance/pageObjects/ownCloudLoginPage.js
  tests/acceptance/stepDefinitions/loginContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2099 Upgrade deps
  apps/files/src/default.js
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/yarn.lock
  yarn.lock
Labels: 3 - To Review, dependencies

#2116 Properly reset capabilities on logout
  src/store/index.js
Labels: 3 - To Review

#2093 Await trashbin deletion requests
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2081 Test multiple collaborators on share on a single share
  package.json
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2098 check required permissions are displayed for files
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, QA-team

#2128 Disable drag and drop for ie11
  apps/files/src/components/FilesAppBar.vue
Labels: 3 - To Review

#2129 Rename and delete will be disallowed in case the parent folder has no…
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/mixins.js
Labels: 3 - To Review

#2014 Add acceptance tests for checking files sidebar in shared with me page
  tests/acceptance/features/webUIFiles/fileDetails.feature
  tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2141 Test: Reject promise if invalid response during permalink check
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2145 Remove unused env variables from .drone.yml
  .drone.yml
Labels: 4 - To release, Drone, QA-team

#1798 run tests again that were failing because of #1502
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#2049 Fix redirection to private link after authorisation
  .drone.yml
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  package.json
  src/phoenix.js
  src/router/index.js
  src/store/index.js
  src/store/links.js
  src/store/user.js
  tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature
  tests/acceptance/helpers/loginHelper.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/privateLinksContext.js
  yarn.lock
Labels: 3 - To Review

#2151 Shared pages tests
  tests/acceptance/features/webUIFiles/fileDetails.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 4 - To release, Acceptance tests, QA-team

#2156 Run webUISharingPublic acceptance test suite on drone
  .drone.yml
Labels: 4 - To release, Drone, QA-team

#2154 Adjust 'the user' steps
  tests/acceptance/customCommands/waitForAjaxCallsToStartAndFinish.js
  tests/acceptance/features/webUIFiles/fileDetails.feature
  tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
  tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/stepDefinitions/generalContext.js
  tests/acceptance/stepDefinitions/notificationsContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 4 - To release, Acceptance tests, QA-team

#2112 drone starlark
  .drone.starlark
  .drone.yml
Labels: 4 - To release, Drone, QA-team

#2170 Feature/private link on external storage
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/store/actions.js
  src/router/index.js
  src/store/index.js
  src/store/links.js
  src/store/router.js
  src/store/user.js
Labels: 3 - To Review

#2161 Add more close options to file actions menu
  apps/files/src/components/FileActions.vue
Labels: 3 - To Review

#2176 Added progress bar for upload
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/UploadMenu.vue
  apps/files/src/components/UploadProgress.vue
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  tests/acceptance/pageObjects/filesPage.js
Labels: 3 - To Review

#2178 Bugfix/logout on access denied page
  src/pages/accessDenied.vue
Labels: 3 - To Review

#2179 Download feedback spinner
  apps/files/src/components/FileList.vue
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  src/plugins/phoenix.js
Labels: 3 - To Review

#2177 Handle errors while deleting and renaming files
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
Labels: 3 - To Review

#2197 Send header X-Requested-With: XMLHttpRequest in all requests
  apps/files/src/components/Collaborators/mixins.js
  apps/files/src/components/FileInfoVersions.vue
  apps/media-viewer/src/Mediaviewer.vue
  apps/pdf-viewer/src/PdfViewer.vue
  src/components/Avatar.vue
  src/plugins/mediaSource.js
Labels: 3 - To Review

#2204 [accentance tests] wait for at least one file to appear in the list
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2206 Switch to show instead of if in upload progress bar
  apps/files/src/components/FilesApp.vue
  tests/acceptance/pageObjects/filesPage.js
Labels: 3 - To Review

#2205 Prevent duplicate token refresh calls
  src/services/auth.js
  src/store/user.js
Labels: 3 - To Review

#2117 Fix password handling in public links
  apps/files/src/components/FileLink.vue
  apps/files/src/components/FileLinkForm.vue
Labels: bug, feature:collaborators, p3-medium

#2211 Upon token refresh do not perform full login on sdk level - this woul…
  src/store/user.js
Labels: 3 - To Review

#2220 Fix exit link on access denied page
  src/pages/accessDenied.vue
Labels: 3 - To Review

#2082 [POC] Run phoenix tests on internet explorer
  .drone.starlark
  .drone.yml
  README.md
  apps/draw-io/webpack.common.js
  apps/markdown-editor/webpack.config.js
  apps/pdf-viewer/webpack.common.js
  nightwatch.conf.js
  tests/acceptance/customCommands/clearValueWithEvent.js
  tests/acceptance/customCommands/setValueBySingleKeys.js
  tests/acceptance/features/webUIFiles/createFolders.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
  tests/acceptance/features/webUIWebdavLockProtection/upload.feature
  tests/acceptance/helpers/navigationHelper.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/pageObjects/favoritesPage.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/publicLinkFilesPage.js
  tests/acceptance/pageObjects/sharedWithMePage.js
  tests/acceptance/pageObjects/sharedWithOthersPage.js
  tests/acceptance/pageObjects/trashbinPage.js
  tests/acceptance/setup-drone.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2231 Shorten drone pipeline names
  .drone.starlark
  .drone.yml
Labels: 3 - To Review, Drone, QA-team

#2194 Upgrade deps 20191009
  apps/draw-io/yarn.lock
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/yarn.lock
  package.json
  yarn.lock
Labels: 3 - To Review

#2234 show file and line number for every test scenario
  tests/acceptance/stepDefinitions/generalContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2235 do and upload screenshots only on PRs
  .drone.starlark
  .drone.yml
Labels: 3 - To Review, Acceptance tests, QA-team

#2219 Change key of file action buttons to ariaLabel
  apps/files/src/components/FileList.vue
Labels: 3 - To Review, technical debt

#2237 Add acceptance test for deleting single file from trashbin
  tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: Acceptance tests

#2224 Fixed structure of folders in folder upload
  apps/files/src/mixins.js
Labels: 4 - To release, bug-solved

#2221 Trigger add to progress before the folders creation
  apps/files/src/mixins.js
Labels: 3 - To Review

#2146 Add test for checking delete button state when prohibiting deleting in share
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2196 Use currentFolder path in breadcrumbs and remove root folder from it
  apps/files/src/components/FilesAppBar.vue
Labels: 3 - To Review

#2233 Added sanitization to markdown editor
  apps/markdown-editor/src/MarkdownEditor.vue
Labels: 3 - To Review

#2225 Handle remove from progress in its own mutation
  apps/files/src/FileUpload.js
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
  apps/files/src/store/mutations.js
Labels: 3 - To Review, bug-solved

#2140 Add acceptance tests for deleting shared files and deleting shares
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/helpers/occHelper.js
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2238 Add new test suite for sharing permissions
  .drone.starlark
  .drone.yml
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissions/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingPermissions/sharePermissionsUsers.feature
Labels: 3 - To Review, Acceptance tests, Drone

#1951 Fix public links actions
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/store/actions.js
  src/plugins/phoenix.js
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/helpers/sharingHelper.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/publicLinkFilesPage.js
  tests/acceptance/pageObjects/publicLinkPasswordPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, bug-solved

#2017 check if a resource really exists
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2261 Use oidc-client 1.9.1
  package.json
  yarn.lock
Labels: 3 - To Review

#2265 [acceptance tests] Fix navigationHelper function for navigate and wait till loaded
  tests/acceptance/helpers/navigationHelper.js
  tests/acceptance/pageObjects/favoritesPage.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/publicLinkFilesPage.js
  tests/acceptance/pageObjects/sharedWithMePage.js
  tests/acceptance/pageObjects/sharedWithOthersPage.js
  tests/acceptance/pageObjects/trashbinPage.js
Labels: 3 - To Review, Acceptance tests

#2278 only delete 1/sec in acceptance tests
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2267 Rename acceptance test step for changing custom permission of a share
  tests/acceptance/features/webUISharingPermissions/sharePermissionsUsers.feature
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, Acceptance tests

#2147 Refactor Test function for setting collaborator permissions
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
Labels: 3 - To Review, Acceptance tests

#2159 Test resharing with different permissions
  .drone.starlark
  .drone.yml
  tests/acceptance/features/webUIResharing/reshareUsers.feature
  tests/acceptance/features/webUISharingPermissions/sharePermissionsUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/loginContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2284 clear filelocks after test run
  tests/acceptance/stepDefinitions/generalContext.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2198 Reset search value on clear action
  apps/files/src/components/FilesAppBar.vue
  package.json
  yarn.lock
Labels: 3 - To Review, bug-solved

#2285 Improve tests functions for sharing related tests
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
Labels: 3 - To Review, Acceptance tests, QA-team

#2291 Split acceptance test suite webUISharingPermissions to users and groups
  .drone.starlark
  .drone.yml
  tests/acceptance/features/webUISharingPermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
Labels: 3 - To Review, Acceptance tests, Drone, QA-team

#2294 drone notify on failure
  .drone.starlark
  .drone.yml
Labels: 4 - To release, Drone, QA-team

#2301 Update deps 20191021
  apps/draw-io/yarn.lock
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/yarn.lock
  yarn.lock
Labels: 3 - To Review

#2310 Remove file from progress after download on IE11
  src/plugins/phoenix.js
Labels: 3 - To Review, bug-solved

#2311 Added X-Frame-Options and Content-Security-Policy
  .htaccess
Labels: 3 - To Review

#2111 Add new file menu entries for different file types.
  apps/draw-io/src/app.js
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/mixins.js
  apps/markdown-editor/src/app.js
  src/store/apps.js
Labels: 3 - To Review

#2326 Add skip to component, id attribute for <main>
  src/Phoenix.vue
  src/components/SkipTo.vue
Labels: 3 - To Review, Accessibility

#2320 check for 200 ocs status code
  tests/acceptance/helpers/httpHelper.js
  tests/acceptance/helpers/occHelper.js
Labels: 3 - To Review, QA-team

#2322 wait till animations are finished after deleting file
  nightwatch.conf.js
  tests/acceptance/customCommands/waitForAnimationToFinish.js
  tests/acceptance/customCommands/waitForCSSPropertyEquals.js
  tests/acceptance/customCommands/waitForElementEnabled.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
Labels: 3 - To Review, Acceptance tests, QA-team
