Repository owncloud/web, pull requests merged in 2020-05, with the labels that each got.

#3443 [Tests-Only]Skip failing tests in ocis
  tests/acceptance/features/webUICreateFilesFolders/createFile.feature
  tests/acceptance/features/webUIFiles/sort.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
Labels: 3 - To Review, dev:acceptance-tests

#3441 [Tests-Only] Disable screenshots by default in drone
  .drone.star
  nightwatch.conf.js
Labels: 3 - To Review, Drone, QA-team

#3445 update readme file with valid url for online demo
  README.md
Labels: documentation

#3454 Configure ocis proxy as default entry point
  changelog/unreleased/3454
  config.json.sample-ocis
Labels: 3 - To Review, bug-solved

#3453 [Tests-only] improve ocis tests documentation
  docs/testing.md
Labels: QA-team, dev:acceptance-tests

#3463 [Tests-Only] Unskip tests for renaming and file list
  tests/acceptance/features/webUICreateFilesFolders/createFolderEdgeCases.feature
  tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIFiles/fileList.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3336 Removed favorite button from file list and added it instead in action…
  apps/files/src/components/AllFilesList.vue
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesLists/RowActionsDropdown.vue
  apps/files/src/components/Trashbin.vue
  apps/files/src/fileactions.js
  changelog/unreleased/3336
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
  tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/filesRow.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review

#3483 [Tests-Only] Unskip passing tests in CI
  tests/acceptance/features/webUIAccount/accountInformation.feature
  tests/acceptance/features/webUICreateFilesFolders/createFolderEdgeCases.feature
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIFiles/breadcrumb.feature
  tests/acceptance/features/webUIFiles/fileDetails.feature
  tests/acceptance/helpers/ldapHelper.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3457 [Tests-only] Reenable upload related tests
  .drone.star
  .gitignore
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
Labels: QA-team

#3490 [Tests-Only] split ocis test pipelines
  .drone.star
  package.json
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3484 Fetch settings values from sdk and use language code
  changelog/unreleased/3484-1
  changelog/unreleased/3484-2
  config.json.sample-ocis
  package.json
  src/Phoenix.vue
  src/store/index.js
  src/store/settings.js
  src/store/user.js
  yarn.lock
Labels: 2 - Developing
