Repository owncloud/web, pull requests merged in 2020-09, with the labels that each got.

#4032 [tests-only] small fixes in the tests
  nightwatch.conf.js
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
Labels: QA-team

#4033 [tests-only] fix documentation about acceptance tests
  docs/testing.md
Labels: QA-team

#4050 [tests-only] mark some tests as @ocisSmokeTest
  tests/acceptance/features/webUICreateFilesFolders/createFile.feature
  tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUILogin/login.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
  tests/acceptance/features/webUIUpload/upload.feature
Labels: QA-team

#4086 Update ods 1.10.1
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/Collaborators/EditCollaborator.vue
  apps/files/src/components/Collaborators/NewCollaborator.vue
  apps/files/src/components/Collaborators/SharedFilesList.vue
  apps/files/src/components/FileInfoVersions.vue
  apps/files/src/components/FileLinkSidebar.vue
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/FilesLists/Indicators.vue
  apps/files/src/components/FilesLists/QuickActions.vue
  apps/files/src/components/FilesLists/RowActionsDropdown.vue
  apps/files/src/components/LocationPicker/LocationPicker.vue
  apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
  apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
  apps/files/src/components/Roles/RolesSelect.vue
  apps/files/src/default.js
  apps/files/src/quickActions.js
  apps/markdown-editor/src/MarkdownEditorAppBar.vue
  changelog/unreleased/update-ods-1.11.0
  src/Phoenix.vue
  src/components/Notifications.vue
  src/components/SearchBar.vue
  src/components/Top-Bar.vue
  src/pages/account.vue
  src/pages/login.vue
  src/store/sidebar.js
  tests/acceptance/pageObjects/phoenixPage.js
  yarn.lock
Labels: 3 - To Review

#4092 Improve oc10 link
  changelog/unreleased/external-links
  src/Phoenix.vue
  src/components/ApplicationsMenu.vue
  yarn.lock
Labels: 3 - To Review

#4094 [Tests-Only] Improve error handling in tests and update ocis commit id
  .drone.star
  tests/acceptance/helpers/httpHelper.js
  tests/acceptance/stepDefinitions/generalContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#4108 [Tests-Only] Refactor restrict sharing and auto completion tests
  tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#4123 [Tests-Only] skip failing autocompletion tests
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
Labels: QA-team, dev:acceptance-tests
