Repository owncloud/web, pull requests merged in 2020-06, with the labels that each got.

#3378 Bring new modal component
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/FilesLists/RowActionsDropdown.vue
  apps/files/src/components/Trashbin.vue
  apps/files/src/components/ocDialogPrompt.vue
  apps/files/src/fileactions.js
  apps/files/src/mixins.js
  apps/files/src/mixins/deleteResources.js
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  changelog/unreleased/bring-new-modal-component
  package.json
  src/Phoenix.vue
  src/store/index.js
  src/store/modal.js
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  yarn.lock
Labels: QA-team, enhancement

#3570 Move navItems into a store module
  changelog/unreleased/dynamic-nav-items
  src/Phoenix.vue
  src/phoenix.js
  src/store/index.js
  src/store/navigation.js
Labels: 3 - To Review

#3548 [tests-only] Simplify test run
  .gitignore
  docs/testing.md
  nightwatch.conf.js
  package.json
  tests/acceptance/mac-identifier-registration.yml
  tests/acceptance/ocis-mac-config.json
Labels: QA-team, dev:acceptance-tests

#3573 Load and display quick actions
  apps/files/package.json
  apps/files/src/components/AllFilesList.vue
  apps/files/src/components/Collaborators/SharedFilesList.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesLists/QuickActions.vue
  apps/files/src/components/Trashbin.vue
  apps/files/src/default.js
  apps/files/src/quickActions.js
  apps/files/yarn.lock
  changelog/unreleased/load-and-display-quick-actions
  src/components/MessageBar.vue
  src/phoenix.js
  src/store/app.js
  tests/acceptance/features/webUIFiles/fileList.feature
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/filesRow.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
Labels: enhancement

#3602 Upgrade owncloud-sdk
  changelog/unreleased/fix-empty-settings.md
  package.json
  yarn.lock
Labels: 3 - To Review

#3606 [Tests-Only] Use owncloudci nodejs 11 docker image
  .drone.star
Labels: 3 - To Review, QA-team

#3599 [Tests-Only] Refactor .drone.star file in acceptance test step
  .drone.star
Labels: Drone, QA-team

#3613 [Tests-Only] Use openldap:1.3.0
  .drone.star
Labels: 4 - To release, QA-team

#3604 Use correct logo
  changelog/unreleased/use-correct-logo
  src/Phoenix.vue
  themes/owncloud/assets/logo.png
  themes/owncloud/assets/logo.svg
Labels: design

#3605 Rework account dropdown
  changelog/unreleased/rework-account-dropdown
  src/components/UserMenu.vue
  tests/acceptance/pageObjects/accountPage.js
  tests/acceptance/pageObjects/phoenixPage.js
  tests/acceptance/pageObjects/profilePage.js
Labels: design

#3585 Add collaborators quick action
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesLists/QuickActions.vue
  apps/files/src/quickActions.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  changelog/unreleased/add-collaborators-quick-action
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: enhancement, feature:collaborators

#3634 [skip-ci] fix path of example config file in documentation
  docs/testing.md
Labels: QA-team

#3636 [Tests-Only] Dont start oc service while testing ocis in CI
  .drone.star
Labels: Drone, QA-team

#3661 [tests-only] Improve testing documentation and test-commands
  config.json.sample-ocis
  docs/testing.md
  package.json
Labels: QA-team

#3669 [Tests-Only] Add drone CI code to allow specifying OCIS Commit
  .drone.star
Labels: 3 - To Review, QA-team

#3622 Move create new button
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesAppBar.vue
  changelog/unreleased/move-create-button
  tests/acceptance/pageObjects/filesPage.js
Labels: design

#3672 [Tests-Only] show browser logs in ocis on failure
  tests/acceptance/setup.js
Labels: QA-team, dev:acceptance-tests

#3679 Set expiration date only if it is supported
  apps/files/src/components/Collaborators/CollaboratorsEditOptions.vue
  changelog/unreleased/set-expiration-date-only-if-supported
Labels: bug-solved

#3678 Fixed quick actions
  apps/files/src/components/FileDetails.vue
  apps/files/src/quickActions.js
  changelog/unreleased/set-default-permissions
  changelog/unreleased/set-empty-object-when-resetting-current-tab
Labels: bug-solved

#3687 Do not expand resource name width over its content
  apps/files/src/components/FileItem.vue
  changelog/unreleased/resource-line-width
Labels: bug-solved

#3690 Update sdk
  changelog/unreleased/sdk-update
  package.json
  yarn.lock
Labels: dependencies

#3691 [Tests-Only] Actually run acceptance test scenarios in iPhone resolution
  .drone.star
Labels: 4 - To release, QA-team, dev:acceptance-tests
