Repository owncloud/web, pull requests merged in 2020-11, with the labels that each got.

#4203 Display collaborators type
  apps/files/src/components/Collaborators/AutocompleteItem.vue
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/Collaborators/NewCollaborator.vue
  apps/files/src/mixins/collaborators.js
  changelog/unreleased/collaborator-type
  tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
Labels: enhancement

#4260 Unskip failing autocompletion tests in ci
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
Labels: 3 - To Review, QA-team

#4262 [Tests-Only]Adjust the assertion message for the UI tests
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team

#4253 [tests-only] split and name ocis suites the same as oc10 suites
  .drone.star
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#4267 [tests-only] Minor docs changes for building and testing
  docs/building.md
  docs/testing.md
Labels: 3 - To Review, QA-team

#4282 [Tests-Only] fix browse to files page
  changelog/unreleased/fix-browse-to-files-page
  tests/acceptance/helpers/navigationHelper.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review

#4291 [tests-only]remove skipOnOCIS tag from moveFiles test
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 4 - To release, QA-team

#4285 [Tests-Only] update ocis commitid for running acceptance tests
  .drone.star
Labels: 3 - To Review, QA-team

#4299 [tests-only] added issue tag in imageMediaViewer test
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
  tests/acceptance/pageObjects/FilesPageElement/mediaViewerPage.js
Labels: 3 - To Review, QA-team

#4306 Fix dynamic client registration
  changelog/unreleased/openid-connect-dynamic-client-registration
  src/phoenix.js
Labels: 3 - To Review

#4313 Version bump for release 0.25.0
  changelog/0.25.0_2020-11-16/actions-in-sidebar
  changelog/0.25.0_2020-11-16/context-sensitive-actions
  changelog/0.25.0_2020-11-16/fix-login-as-user
  changelog/0.25.0_2020-11-16/openid-connect-dynamic-client-registration
Labels: 3 - To Review

#4233 [docs-only] correct docs & test commands according to current development
  docs/testing.md
  package.json
Labels: QA-team, documentation

#4326 [tests-only] fix order of arguments in assert
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA-team, dev:acceptance-tests

#4349 [tests-only] Fix waiting between upload & deletes
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA-team, dev:acceptance-tests

#4351 [Tests-Only] fix max listeners execceded warning in ui tests
  tests/acceptance/setup.js
Labels: 3 - To Review, dev:acceptance-tests

#4352 [tests-only] split tests in smaller suites
  .drone.star
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRootEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersBlacklisted/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootBlacklisted/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature
Labels: QA-team, dev:acceptance-tests

#4356 [tests-only] cleanup various issues with the sidebar tests
  tests/acceptance/features/webUIFiles/fileDetails.feature
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/helpers/timeoutHelper.js
  tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
  tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: QA-team, dev:acceptance-tests

#4316 [tests-only] Bump OCIS commit id
  .drone.star
Labels: QA-team

#4372 [tests-only] Skip two sharing tests on ocis
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature
Labels: 3 - To Review

#4371 [Tests-Only] only wait for upload/delete if for same user and file
  tests/acceptance/helpers/webdavHelper.js
Labels: 4 - To release

#4357 Fix icon mappings for non-existing icon files.
  apps/files/src/fileTypeIconMappings.json
  changelog/unreleased/fix-icons
Labels: 3 - To Review

#4376 Release 0.26.0
  changelog/0.26.0_2020-11-23/editor-handler
  changelog/0.26.0_2020-11-23/fix-edit-link-view
  changelog/0.26.0_2020-11-23/fix-icons
  changelog/0.26.0_2020-11-23/new-file-icon
  changelog/0.26.0_2020-11-23/theme-redirect
  changelog/0.26.0_2020-11-23/update-ods
Labels: 3 - To Review

#4381 Correct 0.24.0 release date in changelog
  changelog/0.24.0_2020-11-06/collaborator-type
  changelog/0.24.0_2020-11-06/fix-browse-to-files-page
Labels: 3 - To Review

#4382 Fix app loading failure handling
  changelog/unreleased/default-extension
  changelog/unreleased/extension-loading
  src/components/Avatar.vue
  src/components/Top-Bar.vue
  src/mixins/pluginHelper.js
  src/phoenix.js
  src/services/clientRegistration.js
  src/store/apps.js
  src/store/config.js
Labels: 3 - To Review

#4391 Text editor file path label
  apps/markdown-editor/src/MarkdownEditor.vue
  apps/markdown-editor/src/MarkdownEditorAppBar.vue
  changelog/unreleased/text-editor-file-path-label
Labels: 3 - To Review

#4398 README.md documentation link redirects to the web/getting-started documentation
  README.md
Labels: 3 - To Review
