Repository owncloud/web, pull requests merged in 2020-08, with the labels that each got.

#3852 [Tests-Only]Fixed failing test on public link share
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: QA-team

#3845 [Tests-Only] Run public share tests on ocis
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/stepDefinitions/publicLinkContext.js
Labels: 3 - To Review, QA-team

#3865 [Tests-Only] Create user without ldap server in ocis
  .drone.star
  nightwatch.conf.js
  package.json
  tests/acceptance/setup.js
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: QA-team, dev:acceptance-tests

#3891 [Tests-Only]Acceptance test for video playback in public share
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
  tests/acceptance/stepDefinitions/previewContext.js
Labels: 3 - To Review, QA-team

#3828 Removed docs how to work with hugo
  changelog/unreleased/remove-hugo-docs
  docs/building-docs.md
Labels: documentation

#3931 Update all deps
  apps/draw-io/yarn.lock
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/yarn.lock
  yarn.lock
Labels: dependencies

#3894 [Tests-Only] Added test for media viewer Navigation, download and close actions
  apps/media-viewer/src/Mediaviewer.vue
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
  tests/acceptance/filesForUpload/test_video.mp4
  tests/acceptance/pageObjects/FilesPageElement/offCanvasPage.js
  tests/acceptance/stepDefinitions/previewContext.js
Labels: QA-team

#3849 Display quota in sidebar and move information about current folder below files list
  apps/files/src/components/AllFilesList.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/SidebarQuota.vue
  apps/files/src/helpers/resources.js
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  changelog/unreleased/information-about-current-folder-under-files-list
  changelog/unreleased/quota-in-sidebar
  package.json
  src/Phoenix.vue
  src/store/sidebar.js
  yarn.lock
Labels: design

#3938 Differentiate between username and user-id
  changelog/unreleased/differentiate-between-id-and-username
  changelog/unreleased/fix-displayname
  src/Phoenix.vue
  src/pages/account.vue
  src/store/user.js
Labels: bug-solved, enhancement

#3940 [Tests-Only]Added test for the existing enabled + New button on public link in OCIS
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team

#3944 [tests-only] make rename function in tests async
  tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
Labels: QA-team, dev:acceptance-tests

#3945 [tests-only] Improve delete tests
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
Labels: QA-team, dev:acceptance-tests

#3949 [tests-only] wait for ajax calls when batch deleting
  tests/acceptance/pageObjects/filesPage.js
Labels: QA-team, dev:acceptance-tests

#3954 [tests-only] skip public link tests on ocis
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
Labels: QA-team, dev:acceptance-tests

#3956 Bump version for release 0.14.0
  changelog/0.14.0_2020-08-17/differentiate-between-id-and-username
  changelog/0.14.0_2020-08-17/fix-displayname
  changelog/0.14.0_2020-08-17/hide-search.md
  changelog/0.14.0_2020-08-17/information-about-current-folder-under-files-list
  changelog/0.14.0_2020-08-17/media-viewer-presigned-urls
  changelog/0.14.0_2020-08-17/media-viewer-video-playback
  changelog/0.14.0_2020-08-17/quota-in-sidebar
  changelog/0.14.0_2020-08-17/remove-hugo-docs
  changelog/0.14.0_2020-08-17/remove-shared-with
  changelog/0.14.0_2020-08-17/url-signing.md
Labels: 3 - To Review

#3947 [Tests-Only] Fix random failure related to breadcrumb
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA-team

#3850 Add info about number of selected items and their size
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  changelog/unreleased/multi-select-info
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
Labels: enhancement

#3989 [Tests-Only] Adjust testing doc to run tests without ldap server
  docs/testing.md
Labels: QA-team

#3986 [Test-Only] Update available users to include default users from ocis
  tests/acceptance/helpers/userSettings.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3985 [Tests-Only]Use latest ocis-commit for tests and remove ldap setup configurations
  .drone.star
  package.json
  tests/drone/identifier-registration.yml
  tests/drone/ocis-config.json
Labels: QA-team

#3998 [Tests-Only] Modified API steps to always mention username
  tests/acceptance/features/webUICreateFilesFolders/createFile.feature
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
  tests/acceptance/features/webUIFiles/copyPrivateLinks.feature
  tests/acceptance/features/webUIFiles/download.feature
  tests/acceptance/features/webUIFiles/sort.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: QA-team

#4001 merge similar scenarios together in uploadEdgeCases feature file
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
Labels: QA-team

#3982 [Tests-Only] Run trashbin tests on ocis
  .drone.star
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
  tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
Labels: 3 - To Review, QA-team

#3999 [Tests-Only] Changed wording of "there should be x files/folders listed on the webUI" test step
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team
