Repository owncloud/web, pull requests merged in 2020-07, with the labels that each got.

#3723 Fix breadcrumb last element
  apps/files/src/components/FilesAppBar.vue
  changelog/unreleased/fix-breadcrumb.md
  tests/acceptance/features/webUIFiles/breadcrumb.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review

#3730 Update ODS to 1.8.0
  package.json
  tests/acceptance/pageObjects/phoenixPage.js
  yarn.lock
Labels: dependencies

#3741 [Tests-Only] Unpin osixia/openldap version in CI
  .drone.star
Labels: 3 - To Review, QA-team

#3740 Do not fallback to appId if the file action route is not defined
  apps/pdf-viewer/src/PdfViewer.vue
  apps/pdf-viewer/src/app.js
  changelog/unreleased/file-editors-path
  src/store/apps.js
Labels: bug-solved

#3752 Remove outline around files list
  apps/files/src/components/FilesApp.vue
  changelog/unreleased/files-list-outline
Labels: bug-solved, design

#3739 Feature/move
  .drone.star
  apps/files/src/components/AllFilesList.vue
  apps/files/src/components/Collaborators/SharedFilesList.vue
  apps/files/src/components/FileItem.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/FilesLists/Indicators.vue
  apps/files/src/components/LocationPicker/LocationPicker.vue
  apps/files/src/components/LocationPicker/MoveSidebarMainContent.vue
  apps/files/src/components/Trashbin.vue
  apps/files/src/default.js
  apps/files/src/fileactions.js
  apps/files/src/helpers/permissions.js
  apps/files/src/helpers/store.js
  apps/files/src/mixins/deleteResources.js
  apps/files/src/mixins/filesListIndicators.js
  apps/files/src/store/actions.js
  changelog/unreleased/move
  src/Phoenix.vue
  src/store/index.js
  src/store/sidebar.js
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
  tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/locationPicker.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: enhancement, feature:files

#3756 Fix location picker navigation to root
  apps/files/src/components/LocationPicker/LocationPicker.vue
  changelog/unreleased/location-picker-root-target
Labels: bug-solved

#3754 Add favorites capabilities
  apps/files/src/components/FileDetails.vue
  apps/files/src/default.js
  apps/files/src/fileactions.js
  changelog/unreleased/favorites-capabilities
  src/store/navigation.js
Labels: enhancement

#3749 Feature/copy
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/LocationPicker/CopySidebarMainContent.vue
  apps/files/src/components/LocationPicker/LocationPicker.vue
  apps/files/src/fileactions.js
  changelog/unreleased/copy
  tests/acceptance/features/webUIFiles/copy.feature
  tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/locationPicker.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: enhancement

#3748 [Tests-Only] Add acceptance tests for files with commas in the filename
  tests/acceptance/features/webUICreateFilesFolders/createFile.feature
  tests/acceptance/features/webUICreateFilesFolders/createFolderEdgeCases.feature
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFiles/download.feature
  tests/acceptance/features/webUIFiles/search.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
  tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/filesForUpload/Folder,With,Comma/sunday,monday.txt
  tests/acceptance/filesForUpload/file,with,comma,.txt
Labels: QA-team

#3765 [Tests-Only]Merge similar scenarios after the issue is solved and skip tags are removed
  tests/acceptance/features/webUICreateFilesFolders/createFolderEdgeCases.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
Labels: QA-team

#3767 Fix typo in docs
  changelog/unreleased/docs-releasing.md
  docs/releasing.md
Labels: 3 - To Review, documentation

#3783 Add key to theme for sidebar logo
  changelog/unreleased/themeable-logo-in-sidebar
  src/Phoenix.vue
  src/store/config.js
  src/themes/owncloud.less
  src/themes/owncloud/autocomplete.less
  src/themes/owncloud/base.less
  src/themes/owncloud/buttons.less
  src/themes/owncloud/icon-input.less
  src/themes/owncloud/label.less
  src/themes/owncloud/loader-spinner.less
  src/themes/owncloud/logo.less
  src/themes/owncloud/main.less
  src/themes/owncloud/menu-secondary.less
  src/themes/owncloud/oc-app-container.less
  src/themes/owncloud/oc-app-menu.less
  src/themes/owncloud/oc-head.less
  src/themes/owncloud/oc-public-share-icon.less
  src/themes/owncloud/oc-shared-item-card.less
  src/themes/owncloud/oc-user-menu.less
  src/themes/owncloud/offcanvas.less
  src/themes/owncloud/text.less
  src/themes/owncloud/transitions.less
  src/themes/owncloud/variables.less
  themes/owncloud.json
Labels: enhancement

#3772 [Tests-Only] Add acceptance tests to move files/folders into a folder with no change permissions
  tests/acceptance/features/webUIFiles/copy.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/locationPicker.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA-team

#3791 [Tests-Only]Add acceptance tests for breadcrumbs with double quotes
  tests/acceptance/features/webUIFiles/breadcrumb.feature
  tests/acceptance/features/webUIFiles/copy.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA-team

#3792 Fix typo in README
  README.md
Labels: 3 - To Review

#3800 [Tests-only] Adjust browse to files page method to reduce waiting time
  tests/acceptance/helpers/navigationHelper.js
  tests/acceptance/pageObjects/filesPage.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3801 [docs] Add docs about running tests in CI
  docs/testing.md
Labels: 3 - To Review, QA-team, documentation

#3811 [Tests-Only] Add acceptance tests for navigating to last opened folder after closing the Markdown editor
  tests/acceptance/features/webUICreateFilesFolders/createFile.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA-team

#3824 [Tests-Only] Add test for hiding search bar config option
  tests/acceptance/features/webUIFiles/options.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
Labels: 4 - To release, QA-team, dev:acceptance-tests

#3812 [Tests-Only] webUI test for media viewer
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/offCanvasPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/previewContext.js
Labels: 3 - To Review, QA-team

#3773 [Tests-Only] Access last created public link with OCIS
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/helpers/sharingHelper.js
Labels: 3 - To Review, QA-team

#3803 Play videos in media viewer
  apps/media-viewer/src/Mediaviewer.vue
  apps/media-viewer/src/app.js
  changelog/unreleased/media-viewer-presigned-urls
  changelog/unreleased/media-viewer-presigned-urls copy
  package.json
  yarn.lock
Labels: enhancement

#3829 [tests-only] use openid-connect insecure and not debug setting
  .drone.star
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
Labels: QA-team, dev:acceptance-tests

#3797 Use pre-signed URLs to download files
  .drone.star
  apps/files/src/components/FileInfoVersions.vue
  changelog/unreleased/url-signing.md
  package.json
  src/plugins/phoenix.js
  yarn.lock
Labels: QA-team, enhancement

#3833 Media viewer video fixes
  apps/media-viewer/src/Mediaviewer.vue
  apps/media-viewer/src/app.js
  changelog/unreleased/media-viewer-video-playback
Labels: 3 - To Review, bug

#3840 [Tests-Only] Added media viewer tests for video
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
  tests/acceptance/filesForUpload/test_video.mp4
  tests/acceptance/pageObjects/FilesPageElement/offCanvasPage.js
Labels: QA-team

#3844 Media viewer public context
  apps/media-viewer/src/Mediaviewer.vue
  apps/media-viewer/src/mixins/loader.js
  changelog/unreleased/media-viewer-presigned-urls
  changelog/unreleased/media-viewer-video-playback
Labels: bug, bug-solved

#3848 Media viewer video navigation
  apps/media-viewer/src/Mediaviewer.vue
  changelog/unreleased/media-viewer-video-playback
Labels: 3 - To Review, bug, bug-solved
