Repository owncloud/web, pull requests merged in 2020-04, with the labels that each got.

#3292 Update owncloud-sdk 1.0.0-544
  changelog/unreleased/3292
  package.json
  yarn.lock
Labels: 3 - To Review

#3293 In slow networks requirejs reuquests can timeout. The timeout is set …
  changelog/unreleased/3293
  src/phoenix.js
Labels: 3 - To Review

#3288 Fix media-viewer on private pages
  apps/media-viewer/src/Mediaviewer.vue
  changelog/unreleased/fix_media_viewer_on_private_pages.md
Labels: 3 - To Review

#3273 [Tests-only] Run tests with openIdConnect in CI
  .drone.star
  nightwatch.conf.js
  tests/acceptance/features/webUIAccount/logout.feature
  tests/acceptance/features/webUILogin/login.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/helpers/loginHelper.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
  tests/acceptance/stepDefinitions/loginContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/drone/config.json
Labels: 3 - To Review, Drone, QA-team

#3294 mediaviewer: add state to urls
  apps/files/src/components/FilesApp.vue
  apps/files/src/fileactions.js
  apps/media-viewer/src/Mediaviewer.vue
  apps/media-viewer/src/app.js
  apps/media-viewer/src/mixins/loader.js
  changelog/unreleased/app_state_in_urls.md
  src/plugins/phoenix.js
Labels: 3 - To Review

#3323 [Tests-only] Run tests without openId login by default
  .drone.star
  nightwatch.conf.js
Labels: QA-team, dev:acceptance-tests

#3241 Fix share expiration date change
  apps/files/src/components/Collaborators/EditCollaborator.vue
  apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
  apps/files/src/store/actions.js
  changelog/unreleased/3176
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
  tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, QA-p2, QA-team

#3240 Dialog prompt message fix
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/ocDialogPrompt.vue
  changelog/unreleased/1906
  package.json
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/phoenixPage.js
  yarn.lock
Labels: 3 - To Review

#3342 Remove obsolete (and duplicate) error alert
  apps/files/src/components/ocDialogPrompt.vue
  changelog/unreleased/3342
Labels: 3 - To Review

#3339 Transpile with babel only src folder in core
  webpack.common.js
Labels: 3 - To Review

#3346 Pin easygettext@2.9.0 - current 2.10.0 cannot extract string from pl…
  changelog/unreleased/3346
  package.json
  yarn.lock
Labels: 4 - To release

#3350 [Tests-Only] Use PHP 7.3 in drone
  .drone.star
Labels: 3 - To Review, QA-team

#3369 Updated sdk
  changelog/unreleased/update_owncloud_sdk
  package.json
  yarn.lock
Labels: 3 - To Review

#3375 [Tests-only] add slash at the end of redirect_uri to allow correct logout
  tests/drone/identifier-registration.yml
Labels: QA-team, dev:acceptance-tests

#3374 [Tests-only] remove need to authorize phoenix on kopano
  tests/acceptance/helpers/loginHelper.js
  tests/acceptance/pageObjects/kopanoAuthorizePage.js
  tests/drone/identifier-registration.yml
Labels: QA-team, dev:acceptance-tests

#3345 Feature/tus upload
  apps/files/src/mixins.js
  apps/files/src/store/actions.js
  changelog/unreleased/3345
  package.json
  src/phoenix.js
  src/plugins/upload.js
  src/store/config.js
  yarn.lock
Labels: 3 - To Review, enhancement

#3297 show token string if link name is empty in FileLinkSidebar
  apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
  apps/files/src/store/actions.js
  changelog/unreleased/3297
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/stepDefinitions/publicLinkContext.js
Labels: 3 - To Review

#3266 remove deleted files from search result
  apps/files/src/store/actions.js
  apps/files/src/store/mutations.js
  changelog/unreleased/3266
  tests/acceptance/features/webUIFiles/search.feature
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review

#3379 [Tests-only] improve testing documentation
  docs/testing.md
  package.json
Labels: QA-team, documentation

#3394 [Tests-only] revert selenium chrome docker image to 3.141.59-20200326
  .drone.star
Labels: QA-p1, QA-team, dev:acceptance-tests

#3397 Updated all deps
  apps/draw-io/yarn.lock
  apps/files/yarn.lock
  apps/markdown-editor/yarn.lock
  apps/media-viewer/yarn.lock
  apps/pdf-viewer/yarn.lock
  yarn.lock
Labels: dependencies
