Repository owncloud/web, pull requests merged in 2020-12, with the labels that each got.

#4411 Not found error page
  apps/files/src/components/AllFilesList.vue
  apps/files/src/components/Collaborators/SharedFilesList.vue
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/FilesLists/NoContentMessage.vue
  apps/files/src/components/FilesLists/NotFoundMessage.vue
  apps/files/src/components/LocationPicker/LocationPicker.vue
  apps/files/src/components/Trashbin.vue
  apps/files/src/mixins/deleteResources.js
  apps/files/src/mixins/routes.js
  changelog/unreleased/configurable-home-path
  changelog/unreleased/resource-not-found-error-page
  docs/getting-started.md
  src/store/config.js
  tests/acceptance/features/webUIFiles/breadcrumb.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
  themes/owncloud.json
  themes/owncloud/assets/cloud.svg
Labels: 3 - To Review

#4420 Bump version for release 0.28.0
  changelog/0.28.0_2020-12-04/configurable-home-path
  changelog/0.28.0_2020-12-04/resource-not-found-error-page
  changelog/0.28.0_2020-12-04/text-editor-file-path-label
Labels: 3 - To Review

#4419 [tests-only] Adjust scenarios in sharedFolderWithMultipleUsersAdvancedPermissions
  tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
Labels: 3 - To Review, QA-team

#4421 Fix downstream trigger for docs
  .drone.star
Labels: 3 - To Review

#4425 Public link fixes
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/default.js
  apps/files/src/quickActions.js
  changelog/unreleased/fix-public-link-issues
Labels: 3 - To Review

#4410 Display collaborator info in labels
  .drone.star
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/FileLinkSidebar.vue
  apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
  apps/files/src/components/PublicLinksSidebar/LinkActions.vue
  apps/files/src/components/PublicLinksSidebar/LinkInfo.vue
  apps/files/src/components/PublicLinksSidebar/PrivateLinkItem.vue
  apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  changelog/unreleased/share-info-labels
  changelog/unreleased/visible-links
  package.json
  tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
  yarn.lock
Labels: enhancement

#4436 Fix file editor actions
  apps/files/src/mixins/fileActions.js
  changelog/unreleased/fix-file-action-route-checks
  src/store/apps.js
Labels: 3 - To Review

#4435 [tests-only] Fixup test suites in ci
  .drone.star
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
Labels: QA-team

#4488 Update ODS to 2.0.3
  changelog/unreleased/update-ods-2.0.3
  package.json
  yarn.lock
Labels: 3 - To Review

#4492 Improve app docs
  docs/deployments/oc10-app.md
  docs/static/oauth2.jpg
Labels: documentation

#4499 [tests-only] Remove WEB_OIDC_CLIENT_ID phoenix from .drone.star - not used
  .drone.star
Labels: 3 - To Review, QA-team

#4500 Fix opening editors in new tab
  apps/files/src/mixins/fileActions.js
  apps/media-viewer/src/app.js
  changelog/unreleased/editors-new-tab
Labels: bug-solved

#4504 Bring back the permissions field in public links editing
  apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
  changelog/1.0.0_2020-12-15/fix-link-role-selection
Labels: 3 - To Review

#4508 [tests-only] Fix random typos
  apps/files/docs/extensionpoints.adoc
  apps/files/src/helpers/collaboratorRolesDefinition.js
  apps/files/src/helpers/resources.js
  apps/files/src/helpers/route.js
  src/mixins/navigationMixin.js
  src/plugins/web.js
  src/web.js
  tests/acceptance/filesForUpload/file,with,comma,.txt
  tests/acceptance/helpers/path.js
  tests/acceptance/helpers/sharingHelper.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team

#4509 [tests-only] Fix: Delete file in trashbin UI test step not working #4437
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
  tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
Labels: QA-team

#4513 Introduce config option for disabling previews in list views.
  apps/files/src/components/AllFilesList.vue
  changelog/unreleased/disable-previews
  docs/getting-started.md
  src/store/config.js
Labels: 3 - To Review

#4533 Fix typo of inputPlaceholder
  src/store/modal.js
Labels: 3 - To Review

#4535 Update README.md
  README.md
Labels: documentation

#4536 Be more forgiving with the server url
  changelog/unreleased/server-url
  src/store/config.js
Labels: 3 - To Review

#4503 [Tests-Only] Adjust UI test scenarios related to product issue 203
  tests/acceptance/features/webUIResharing/reshareUsers.feature
  tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
Labels: 2 - Developing, QA-team

#4550 [tests-only] Use owncloudci/nodejs:12 instead of webhippie/nodejs:latest
  .drone.star
Labels: 3 - To Review, QA-team

#4555 [tests-only] Bump ocisCommit for tests
  .drone.star
Labels: 4 - To release, QA-team

#4511 [tests-only] clean code duplication
  tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
Labels: QA-team

#4556 [tests-only] remove commit id from .drone.star file
  .drone.env
  .drone.star
  docs/testing.md
Labels: QA-team

#4561 [tests-only] Bump OCIS_COMMITID for testing
  .drone.env
Labels: 3 - To Review, QA-team

#4538 [Tests Only] Add acceptance tests to restore a trashbin file whose parent folder is renamed or is not restored
  tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
  tests/acceptance/pageObjects/webPage.js
  tests/acceptance/stepDefinitions/generalContext.js
Labels: 2 - Developing

#4544 [Tests-Only] add webui tests for viewing mp3 file in media viewer
  .drone.star
  tests/acceptance/expected-failures-with-oc10-server.txt
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.txt
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
  tests/acceptance/filesForUpload/testimage.mp3
Labels: 3 - To Review, QA-team

#4543 [Tests-Only] Add ui test for checking the browser session of deleted user
  tests/acceptance/expected-failures-with-oc10-server.txt
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.txt
  tests/acceptance/features/webUILogin/login.feature
  tests/acceptance/pageObjects/loginErrorPage.js
  tests/acceptance/stepDefinitions/loginContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: 3 - To Review

#4560 [Tests-Only] Add webui tests for various file operations by public in public share
  tests/acceptance/features/webUIFiles/fileList.feature
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA-team

#4571 [tests-only] Refactor for oCIS
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/run.sh
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
  tests/acceptance/stepDefinitions/notificationsContext.js
Labels: 3 - To Review, QA-team

#4576 [tests-only] Bump OCIS commit id for tests
  .drone.env
Labels: 3 - To Review, QA-team
