Repository owncloud/web, pull requests merged in 2020-02, with the labels that each got.

#2959 Enforce order in components
  .eslintrc.json
  apps/draw-io/src/DrawIoEditor.vue
  apps/files/src/components/AllFilesList.vue
  apps/files/src/components/Collaborators/AutocompleteItem.vue
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/Collaborators/CollaboratorsEditOptions.vue
  apps/files/src/components/Collaborators/EditCollaborator.vue
  apps/files/src/components/Collaborators/NewCollaborator.vue
  apps/files/src/components/Collaborators/SharedFilesList.vue
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileDrop.vue
  apps/files/src/components/FileFilterMenu.vue
  apps/files/src/components/FileInfoVersions.vue
  apps/files/src/components/FileLinkSidebar.vue
  apps/files/src/components/FileList.vue
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/components/FileSidebarWebComponent.vue
  apps/files/src/components/FileUpload.vue
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/FolderUpload.vue
  apps/files/src/components/PublicLinks/FilesDrop.vue
  apps/files/src/components/PublicLinks/PublicLink.vue
  apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
  apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
  apps/files/src/components/Trashbin.vue
  apps/files/src/components/UploadMenu.vue
  apps/files/src/components/UploadProgress.vue
  apps/files/src/components/ocDialogPrompt.vue
  apps/markdown-editor/src/MarkdownEditor.vue
  apps/media-viewer/src/Mediaviewer.vue
  apps/pdf-viewer/src/PdfViewer.vue
  src/Phoenix.vue
  src/components/ApplicationsMenu.vue
  src/components/Avatar.vue
  src/components/MessageBar.vue
  src/components/Top-Bar.vue
  src/pages/accessDenied.vue
  src/pages/oidcCallback.vue
Labels: 3 - To Review, technical debt

#2952 Fix add/remove animations for collaborators and links
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/Collaborators/CollaboratorsEditOptions.vue
  apps/files/src/components/Collaborators/EditCollaborator.vue
  apps/files/src/components/Collaborators/NewCollaborator.vue
  apps/files/src/components/FileLinkSidebar.vue
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
  apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
  apps/files/src/mixins/collaborators.js
  apps/files/src/store/actions.js
  apps/files/src/store/getters.js
  apps/files/src/store/mutations.js
  apps/files/src/store/state.js
  changelog/unreleased/2937
Labels: 3 - To Review

#2982 Use new ODS and adjust spinner sizes.
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/Collaborators/EditCollaborator.vue
  apps/files/src/components/Collaborators/NewCollaborator.vue
  apps/files/src/components/PrivateLink.vue
  apps/files/src/components/PublicLinks/FilesDrop.vue
  apps/files/src/components/PublicLinks/PublicLink.vue
  apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
  apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
  package.json
  src/components/Avatar.vue
  yarn.lock
Labels: 3 - To Review

#2988 Upgrade ODS to most recent version
  package.json
  yarn.lock
Labels: 3 - To Review

#2990 Changelog for ODS
  changelog/unreleased/2989
Labels: 3 - To Review

#2987 Use `$ngettext` for pluralization in i18n
  apps/files/src/components/FilesAppBar.vue
  apps/files/src/components/Trashbin.vue
Labels: 3 - To Review

#2983 Collaborator panel tweaks
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/Collaborators/CollaboratorsEditOptions.vue
  apps/files/src/components/Collaborators/EditCollaborator.vue
  apps/files/src/components/Collaborators/NewCollaborator.vue
  apps/files/src/components/FileLinkSidebar.vue
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/components/FilesLists/StatusIndicators/DefaultIndicators.vue
  apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
  apps/files/src/components/Roles/RoleItem.vue
  apps/files/src/components/Roles/RolesSelect.vue
  apps/files/src/helpers/shareTypes.js
  apps/files/src/store/getters.js
  changelog/unreleased/1186-1
  changelog/unreleased/1186-2
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review

#2997 Splitted suite webUISharingFolderAdvancedPermissionsGroups
  .drone.star
  tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
Labels: 3 - To Review, QA-team

#3018 Adjusted browserslist to exclude IE 11
  apps/files/package.json
  package.json
Labels: 3 - To Review

#2995 Fixed files table header
  apps/files/src/components/AllFilesList.vue
  apps/files/src/components/FileList.vue
  changelog/unreleased/1952
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review

#3021 Fix malformed config.json.sample (removed double quote)
  config.json.sample
Labels: 3 - To Review

#3019 Change layout and styling for upload progress
  apps/files/src/components/FilesApp.vue
  apps/files/src/components/UploadMenu.vue
  apps/files/src/components/UploadProgress.vue
  changelog/unreleased/3742
Labels: 3 - To Review

#3028 [Tests-Only] Splitted suite webUISharingPublic
  .drone.star
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3013 Separated navigation
  apps/files/src/default.js
  changelog/unreleased/2746
  src/Phoenix.vue
  src/components/ApplicationsMenu.vue
  src/components/Top-Bar.vue
  src/phoenix.js
  src/plugins/phoenix.js
Labels: 3 - To Review

#3033 Add icons for public link expiration and password protection
  apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
Labels: 3 - To Review

#3032 Escaping translations
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/FileOpenActions.vue
  apps/files/src/components/FileSharingSidebar.vue
  apps/files/src/components/PublicLinks/FilesDrop.vue
  apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
  changelog/unreleased/3032
Labels: 3 - To Review, technical debt

#3059 [Tests-only] addressing issue 3055
  tests/acceptance/features/webUICreateFilesFolders/createFile.feature
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3016 [Tests-Only] Restore files and folder from trashbin with same name
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3057 [Tests-Only] Refactored closeSidebar function from PO filesList to appSideBar
  tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, QA-team

#3051 Display decimals only for MB and higher
  apps/files/src/mixins.js
  changelog/unreleased/2986
Labels: 3 - To Review, enhancement

#3063 [Tests-Only] Acceptance test for deleting file from search list
  tests/acceptance/features/webUIFiles/search.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3064 [Tests-only] Addressing issue 3062
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
  tests/acceptance/features/webUIFiles/breadcrumb.feature
  tests/acceptance/features/webUIFiles/download.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/features/webUIResharing/reshareUsers.feature
  tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
  tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
  tests/acceptance/stepDefinitions/generalContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3060 Display current user in collaborators list
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/FileSharingSidebar.vue
  changelog/unreleased/3808
  tests/acceptance/features/webUIResharing/reshareUsers.feature
  tests/acceptance/features/webUISharingFilePermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, enhancement

#3065 [Tests-Only] Moved isSidebarLinksTabPresent command into appSideBar
  tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3069 [Tests-Only] Removed unused functions
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/filesPage.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3050 Different description in overwrite dialog when versioning is enabled
  apps/files/src/mixins.js
  changelog/unreleased/3047
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
Labels: 3 - To Review, enhancement

#3081 [Tests-Only] Use closeSideBar function of appSideBar page
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3083 Fixed responsive buttons layout in app bar when multiple files are se…
  apps/files/src/components/FilesAppBar.vue
  changelog/unreleased/3011
Labels: 3 - To Review, bug-solved

#3070 [Tests-Only] Created versionsPanel PO & moved related commands/elements
  tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/versionsDialog.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3082 [Tests-Only] Moved deleteShareWithUserGroup command into collabratorsDialog
  tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 1 - To develop, dev:acceptance-tests

#3084 [Tests-Only] Moved clickCreateShare command into collaboratorsDialog
  tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3094 [Tests-Only] Moved clickEditShare command into collaboratorsDialog
  tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3066 [Tests-Only] Refactored copyPrivateLink command into publicLinksDialog
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
  tests/acceptance/stepDefinitions/privateLinksContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#3077 Moved sidebar navigation under top bar
  changelog/unreleased/3858
  src/components/Menu.vue
Labels: 3 - To Review, design

#3115 [Tests-Only] Change acceptance test steps to consistently say 'in the trashbin'
  tests/acceptance/features/webUIFiles/search.feature
  tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
  tests/acceptance/stepDefinitions/webdavContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests
