Repository owncloud/web, pull requests merged in 2021-06, with the labels that each got.

#5174 [tests-only] Adjust steps that try to navigate private links
  tests/acceptance/stepDefinitions/privateLinksContext.js
Labels: QA:team

#5184 [tests-only] [full-ci] Do not do earlyFail in CI if full-ci requested
  .drone.star
Labels: QA:team

#5185 [tests-only] Use github_token for posting comments
  .drone.star
Labels: QA:team

#5191 [tests-only] [full-ci] Exit early from build-github-comment-vrt if there are no diffs
  .drone.star
Labels: QA:team

#5179 [tests-only] [full-ci] Bump core and ocis commit id
  .drone.env
  .drone.star
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/helpers/sharingHelper.js
Labels: QA:team

#5195 [CI] Reduce the number of test pipelines in CI
  .drone.star
Labels: QA:team, Type:CI

#5188 [Tests-Only] Run tests with parts
  package.json
  tests/acceptance/run.sh
Labels: QA:team

#5197 [tests-only] Add test tag federated-server-needed
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
Labels: QA:team

#5019 [full-ci][Tests-Only] Remove @yetToImplement tags from tests (part1)
  .drone.star
  tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIAdminSettings/adminAppsSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
  tests/acceptance/features/webUIAdminSettings/helpAndTips.feature
  tests/acceptance/features/webUIComments/comments.feature
  tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIFilesDetails/fileDetails.feature
  tests/acceptance/features/webUIFilesSearch/search.feature
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team

#5205 [Tests-Only] used get text instead of getAttribute
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/personalPage.js
Labels: QA:team

#5099 [tests-only] Remove webUIFilesActionMenu/versions.feature:14 from expected to fail and fix the issue
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
Labels: QA:team

#5215 [Tests-Only] reset opcache after running occ commands
  tests/acceptance/helpers/occHelper.js
Labels: QA:team

#5208 [tests-only] Add ocisSmokeTest tag to tests
  tests/acceptance/features/webUIFilesCopy/copy.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
  tests/acceptance/features/webUIUpload/upload.feature
Labels: QA:team

#5249 [tests-only] run lint also on unit-tests inside of the packages
  package.json
  packages/web-app-files/tests/views/SharedWithMe.setup.js
  packages/web-runtime/tests/mixins/focusMixin.spec.js
Labels: QA:team

#5206 [tests-only] unit tests for UserMenu.vue
  package.json
  packages/web-runtime/tests/components/UserMenu.spec.js
  tests/unit/stubs/index.js
  yarn.lock
Labels: QA:team

#5218 [tests-only] unit tests for Notifications.vue
  packages/web-runtime/tests/components/Notification.spec.js
Labels: QA:team

#5255 [test-only][unit-tests-only] Do not run acceptance tests if only unit tests are changed
  .drone.star
Labels: QA:team

#5254 fix: do not call vuex create store multiple times
  changelog/unreleased/bugfix-remove-vuex-circular-init
  packages/web-app-files/src/views/LocationPicker.vue
  packages/web-runtime/src/index.js
  packages/web-runtime/src/plugins/mediaSource.js
  packages/web-runtime/src/router/index.js
  packages/web-runtime/src/store/index.js
  packages/web-runtime/tests/store/config.spec.js
Labels: Type:Bug

#5258 [tests-only] Unit test for FileUpload component
  packages/web-app-files/tests/components/FileUpload.spec.js
Labels: QA:team

#5253 unit tests for packages/web-app-files/src/mixins.js:fileTypeIcon
  changelog/unreleased/bugfix-typeerror-fileTypeIcon
  packages/web-app-files/src/mixins.js
  packages/web-app-files/tests/mixins.spec.js
Labels: QA:team

#5250 [unit-tests-only] unit tests for AutocompleteItem
  packages/web-app-files/src/components/Collaborators/AutocompleteItem.vue
  packages/web-app-files/tests/components/Collaborators/AutocompleteItem.spec.js
Labels: QA:team

#5267 [unit-tests-only] Unit tests for Collaborator component (1)
  packages/web-app-files/tests/components/Collaborators/Collaborator.spec.js
Labels: QA:team

#5280 [unit-tests-only] test collaborator additional info when collaborator is not current user
  packages/web-app-files/tests/components/Collaborators/Collaborator.spec.js
Labels: QA:team

#5288 [skip-ci] add coverage badge
  README.md
Labels: QA:team

#5289 [tests-only] [full-ci] Put setupServerAndApp commands into a script
  .drone.star
  tests/drone/setup-server-and-app.sh
Labels: QA:team

#5228 [full-ci][tests-only] Remove @yetToImplement tags from tests (Part-2)
  tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRootEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersBlacklisted/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootBlacklisted/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUISharingNotifications/notificationLink.feature
  tests/acceptance/features/webUISharingNotificationsToRoot/notificationLink.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/pageObjects/webPage.js
  tests/acceptance/stepDefinitions/notificationsContext.js
Labels: QA:team

#5285 [unit-tests-only] collaboratorType() of packages/web-app-files/src/mixins/collaborators.js
  packages/web-app-files/tests/unit/mixins/collaborators.spec.js
Labels: QA:team

#5294 [unit-tests-only] stub oc-pagination in SharedWithMe tests
  packages/web-app-files/tests/unit/views/SharedWithMe.setup.js
Labels: QA:team

#5297 [tests-only] [full-ci] Separated large scripts
  .drone.star
  tests/drone/build-glauth.sh
  tests/drone/build-idp.sh
  tests/drone/build-ocis-web.sh
  tests/drone/build-web-app.sh
  tests/drone/build-web.sh
  tests/drone/copy-files-for-upload.sh
  tests/drone/get-ocis.sh
  tests/drone/setup-fed-server-and-app.sh
  tests/drone/setup-graph-api-oidc.sh
  tests/drone/setup-integration-web-app.sh
  tests/drone/setup-notifications-app.sh
  tests/drone/setup-oauth2.sh
Labels: QA:team

#5295 [unit-tests-only] display share type in collaborator component
  packages/web-app-files/tests/unit/components/Collaborators/Collaborator.spec.js
Labels: QA:team

#5306 [unit-tests-only] Adjust the text of unit test it() calls
  packages/web-app-files/tests/unit/components/Collaborators/AutocompleteItem.spec.js
  packages/web-app-files/tests/unit/components/Collaborators/Collaborator.spec.js
  packages/web-runtime/tests/unit/components/Notification.spec.js
  packages/web-runtime/tests/unit/mixins/lifecycleMixin.spec.js
  tests/acceptance/features/webUIWebdavLocks/locks.feature
Labels: QA:team

#5307 [tests-only] [full-ci] Remove old OCIS bug-demo scenarios
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
Labels: QA:team

#5300 [full-ci][Tests-Only]Remove tag @issue-4295
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
Labels: QA:team

#5328 [tests-only] [full-ci] Adjust drone pipeline names
  .drone.star
Labels: QA:team

#5333 [tests-only] Improve failed acceptance test GitHub comment
  .drone.star
Labels: QA:team

#5265 [full-ci] [tests-only] Do not run acceptance tests if only unit tests files are changed
  .drone.star
  tests/drone/build-glauth.sh
  tests/drone/build-idp.sh
  tests/drone/build-ocis-web.sh
  tests/drone/build-web-app.sh
  tests/drone/build-web.sh
  tests/drone/copy-files-for-upload.sh
  tests/drone/get-ocis.sh
  tests/drone/if-diff-has-unit-tests-only.sh
  tests/drone/setup-fed-server-and-app.sh
  tests/drone/setup-graph-api-oidc.sh
  tests/drone/setup-integration-web-app.sh
  tests/drone/setup-notifications-app.sh
  tests/drone/setup-oauth2.sh
  tests/drone/setup-server-and-app.sh
Labels: QA:team

#5338 [tests-only] Refactor skipping of acceptance test steps
  .drone.star
  tests/drone/build-glauth.sh
  tests/drone/build-idp.sh
  tests/drone/build-ocis-web.sh
  tests/drone/build-web-app.sh
  tests/drone/build-web.sh
  tests/drone/copy-files-for-upload.sh
  tests/drone/get-ocis.sh
  tests/drone/setup-fed-server-and-app.sh
  tests/drone/setup-graph-api-oidc.sh
  tests/drone/setup-integration-web-app.sh
  tests/drone/setup-notifications-app.sh
  tests/drone/setup-oauth2.sh
  tests/drone/setup-server-and-app.sh
Labels: QA:team

#5340 Remove unnecessary Propfind requests
  changelog/unreleased/bugfix-unnecessary-webdav-propfind
  packages/web-app-files/src/views/Favorites.vue
  packages/web-app-files/src/views/SharedViaLink.vue
  packages/web-app-files/src/views/SharedWithMe.vue
  packages/web-app-files/src/views/SharedWithOthers.vue
Labels: Status:Needs-Review, Type:Bug

#5343 [tests-only] Respect interaction between full-ci and calculateDiffContainsUnitTestsOnly
  .drone.star
Labels: QA:team

#5352 [full-ci][tests-only] Bump commit ids for tests
  .drone.env
Labels: QA:team

#5279 [full-ci][tests-only]Changed some steps that were creating user with default attributes
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUILogin/openidLogin.feature
  tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFileGroup.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: QA:team

#5287 Report scenarios that pass on retry to github
  .drone.star
  .gitignore
  tests/acceptance/run.sh
Labels: QA:team, Status:Needs-Review

#5320 [full-ci][tests-only] Remove @yetToImplement tags from tests (Part-3)
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkPublicActions.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUISharingPublicManagement/publicLinkShareByEmail.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/features/webUITags/createTags.feature
  tests/acceptance/features/webUITags/tagsSuggestion.feature
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
  tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
Labels: QA:team

#5359 [full-ci] [tests-only] Bump test commit ids
  .drone.env
  .drone.star
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
Labels: QA:team

#5363 [full-ci][tests-only]Removed skeletondirectory from system config
  tests/drone/setup-fed-server-and-app.sh
  tests/drone/setup-server-and-app.sh
Labels: QA:team

#5366 [CI] start acceptance tests only after unit and integration tests are complete
  .drone.star
Labels: QA:team

#5370 [tests-only] Use correct skeleton file in tests
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: QA:team

#5364 Fix v-image-source updates
  changelog/unreleased/bugfix-image-source-updates
  packages/web-runtime/src/plugins/mediaSource.js
Labels: Status:Needs-Review

#5402 [full-ci][tests-only] Check resource type in test steps
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/webdavContext.js
Labels: QA:team

#5413 [unit-tests-only] ignore mocks and fixtures for coverage
  sonar-project.properties
Labels: QA:team

#5414 [full-ci][tests-only] Bump commit ids for tests
  .drone.env
Labels: QA:team

#5403 [full-ci] [tests-only] investigate unexpected passes not reporting
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/run.sh
Labels: QA:team

#5410 [full-ci][tests-only] Refactor assertResourceType added in PR #5402
  tests/acceptance/stepDefinitions/webdavContext.js
Labels: QA:team

#5426 extract loadPreview into helper
  packages/web-app-files/src/helpers/resource/asset.ts
  packages/web-app-files/src/helpers/resource/index.ts
  packages/web-app-files/src/store/actions.js
  packages/web-app-files/tests/unit/helpers/resource/asset.spec.ts
  packages/web-app-files/tests/unit/helpers/resource/privatePreviewBlob.spec.ts
Labels: Status:Needs-Review
