Repository owncloud/web, pull requests merged in 2021-05, with the labels that each got.

#5035 [Tests-Only] Include tests with undefined steps in failed list in run.sh
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/run.sh
Labels: QA:team

#5061 [tests-only] Refactor webdavHelper:getTrashBinElements function
  tests/acceptance/helpers/webdavHelper.js
Labels: QA:team

#5056 Fix z-index on the new file menu
  changelog/unreleased/bugfix-new-file-menu-z-index
  packages/web-app-files/src/App.vue
Labels: Status:Needs-Review

#5040 Remove autoclose on notifications
  changelog/unreleased/enhancement-remove-notification-autoclose
  packages/web-app-draw-io/src/App.vue
  packages/web-app-files/src/components/AppBar.vue
  packages/web-app-files/src/components/BatchActions.vue
  packages/web-app-files/src/views/LocationPicker.vue
  packages/web-app-files/src/views/SharedWithMe.vue
  packages/web-runtime/src/components/Notifications.vue
  packages/web-runtime/src/components/SearchBar.vue
  packages/web-runtime/src/store/app.js
Labels: Topic:Accessibility

#5058 Improve accessibility on new file menu
  changelog/unreleased/enhancement-new-file-menu-a11y
  packages/web-app-files/src/components/AppBar.vue
  packages/web-app-files/src/components/FileUpload.vue
  packages/web-app-files/src/components/FolderUpload.vue
Labels: Topic:Accessibility

#5062 [Tests-Only] use webdriver api to generate screenshots with proper filename
  .drone.star
  nightwatch.conf.js
  tests/acceptance/stepDefinitions/generalContext.js
Labels: QA:team

#5072 [Tests-Only] fix run.sh to report failed test when no expected failure file
  tests/acceptance/run.sh
Labels: QA:team

#5054 [Tests-Only] changed storage providers to ocis for ocis service
  .drone.env
  .drone.star
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
Labels: QA:team

#5076 [Tests-Only] removed redis information from web testing docs
  docs/testing.md
Labels: QA:team

#5091 [tests-only] Fail CI if any of the test suites does not exist
  tests/acceptance/run.sh
Labels: QA:team

#5101 [tests-only] Bump commit ids for tests
  .drone.env
Labels: QA:team

#5104 [tests-only] Feature to debug specific test suites in CI
  .drone.star
Labels: QA:team

#5111 [CI] use ocis repo for glauth
  .drone.star
Labels: QA:team, Type:CI

#5117 [Tests-Only] fix xpaths in filespage to fix intermittent tests
  tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
Labels: QA:team

#5118 fix: make skip to link visible on focus
  changelog/unreleased/bugfix-make-skip-to-visible
  packages/web-runtime/src/components/SkipTo.vue
Labels: Type:Bug

#5105 feat: use slots in sidebar
  changelog/unreleased/change-use-slots-in-sidebar
  packages/web-runtime/src/App.vue
Labels: Category:Enhancement

#5123 [Tests-Only] wait for markdown page after opening file in markdown editor
  tests/acceptance/pageObjects/markdownEditorPage.js
  tests/acceptance/stepDefinitions/markdownEditorContext.js
Labels: QA:team

#5120 [tests-only] Add correct test step to fix intermittent fail
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
Labels: QA:team

#5124 [Tests-Only] disable preview to fix failing upload test
  tests/acceptance/features/webUIUpload/upload.feature
Labels: QA:team

#5129 feat: send focus to add people btn
  changelog/unreleased/enhancement-people-focus
  packages/web-app-files/src/components/FileSharingSidebar.vue
Labels: Category:Enhancement

#5133 [tests-only] reduce log output in tests
  .drone.star
Labels: QA:team

#5141 [CI] Run cache ocis pipeline before tests and increase test timeout
  .drone.star
  tests/acceptance/run.sh
Labels: Type:CI

#5055 update all uikit tooltips to use v-oc-tooltip
  changelog/unreleased/enhancement-oc-tooltip
  packages/web-app-files/src/components/AppBar.vue
  packages/web-app-files/src/components/Collaborators/Collaborator.vue
  packages/web-app-files/src/components/Collaborators/CollaboratorsEditOptions.vue
  packages/web-app-files/src/components/FileInfoVersions.vue
  packages/web-app-files/src/components/FilesLists/QuickActions.vue
  packages/web-app-files/src/components/PublicLinksSidebar/LinkActions.vue
  packages/web-app-files/src/components/PublicLinksSidebar/LinkInfo.vue
  packages/web-app-files/src/components/PublicLinksSidebar/PrivateLinkItem.vue
  packages/web-runtime/src/components/ApplicationsMenu.vue
  packages/web-runtime/src/components/Notifications.vue
  packages/web-runtime/src/index.js
Labels: Status:In-Progress

#5151 [CI] Fix web not starting in CI
  .drone.star
Labels: QA:team, Type:CI

#5142 [tests-only]Bump ocis and core commit id for tests
  .drone.env
Labels: QA:team

#5159 add option to enable preview for specific files only
  changelog/unreleased/enhancement-file-previews
  docs/getting-started.md
  packages/web-app-files/src/store/actions.js
  packages/web-runtime/src/store/config.js
Labels: Status:Needs-Review

#5169 [tests-only] send apache log to /dev/null
  .drone.star
Labels: QA:team

#5156 [Tests-Only] add tests for sharing the shares_folder
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: QA:team

#5157 [tests-only] Adjust steps that try to create files/folder
  tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
  tests/acceptance/pageObjects/personalPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team
