Repository owncloud/web, pull requests merged in 2021-04, with the labels that each got.

#4824 [Tests-Only] Refactor webui scenarios with 'tries to'
  tests/acceptance/features/webUIFiles/copy.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/locationPicker.js
  tests/acceptance/pageObjects/personalPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team

#4875 [tests-only] Used skeleton files wisely on webUISharingInternalUsers feature
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
Labels: QA:team

#4849 Fix avatar url
  changelog/unreleased/bugfix-avatar-url
  packages/web-runtime/src/components/Avatar.vue
  tests/drone/ocis-config.json
  tests/vrt/baseline/ocis/topBar.png
Labels: QA:team

#4901 [Tests-Only] use path.join to construct skeleton dir path
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: QA:team

#4877 [Tests-Only] Split webUiFiles suite into smaller suites
  .drone.star
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-openid-login.md
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIFilesActionMenu/fileFolderActionMenu.feature
  tests/acceptance/features/webUIFilesActionMenu/scrollMenuIntoView.feature
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
  tests/acceptance/features/webUIFilesCopy/copy.feature
  tests/acceptance/features/webUIFilesCopy/copyPrivateLinks.feature
  tests/acceptance/features/webUIFilesDetails/fileDetails.feature
  tests/acceptance/features/webUIFilesList/fileList.feature
  tests/acceptance/features/webUIFilesList/sort.feature
  tests/acceptance/features/webUIFilesSearch/search.feature
Labels: QA:team

#4822 Allow for custom theming
  .gitignore
  changelog/unreleased/enhancement-introduce-web-pkg
  changelog/unreleased/enhancement-runtime-theming
  config/config.json.dist
  config/config.json.sample-oc10
  config/config.json.sample-ocis
  docs/theming/_index.md
  packages/web-app-files/src/App.vue
  packages/web-app-files/src/components/AppBar.vue
  packages/web-app-files/src/components/FilesLists/NotFoundMessage.vue
  packages/web-app-files/src/components/Sidebar.vue
  packages/web-app-files/src/components/UploadProgress.vue
  packages/web-app-files/src/views/LocationPicker.vue
  packages/web-runtime/package.json
  packages/web-runtime/src/App.vue
  packages/web-runtime/src/components/Notifications.vue
  packages/web-runtime/src/components/UserMenu.vue
  packages/web-runtime/src/helpers/theme.js
  packages/web-runtime/src/index.js
  packages/web-runtime/src/pages/login.vue
  packages/web-runtime/src/store/config.js
  packages/web-runtime/tests/helpers/theme.spec.js
  packages/web-runtime/themes/owncloud/assets/favicon.jpg
  packages/web-runtime/themes/owncloud/theme.json
  tests/acceptance/pageObjects/webPage.js
  tests/vrt/baseline/oc10/topBar.png
  tests/vrt/baseline/ocis/topBar.png
  yarn.lock
Labels: Status:Needs-Review

#4911 [tests-only] correct group sharing tests
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: QA:team

#4902 Sharing indicator fail fix
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team

#4923 [Tests-Only] replace consequent test steps with same type as And
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/features/webUIResharing/reshareUsers.feature
  tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
  tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
  tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
  tests/acceptance/features/webUIUserJourney/journey1.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
Labels: QA:team

#4918 Fix loading shares of the current folder twice
  changelog/unreleased/bugfix-parent-paths
  packages/web-app-files/src/helpers/path.js
  packages/web-app-files/tests/helpers/path.spec.js
Labels: Status:Needs-Review

#4845 [Tests-only] Skeleton files used wisely on webui sharing and autocomplete feature files
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature
Labels: QA:team

#4915 Use list element to display added people
  changelog/unreleased/people-list
  packages/web-app-files/src/components/Collaborators/NewCollaborator.vue
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
Labels: Topic:Accessibility

#4921 [Tests-Only] refactor share expire tests to not use skeleton files
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUISharingInternalUsersBlacklisted/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersExpire/shareWithUsersExpiringShares.feature
  tests/acceptance/features/webUISharingInternalUsersExpireToRoot/shareWithUsersExpiringShares.feature
Labels: QA:team, Status:Needs-Review

#4912 [Tests-Only] Split SharingInternalUsersToRoot test suite into smaller suites
  .drone.star
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootCollaborator/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootPreviews/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootShareWithPage/shareWithUsers.feature
Labels: QA:team

#4935 [Tests-Only] refactor upload tests to not use skeleton files
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
  tests/acceptance/features/webUIUserJourney/journey1.feature
  tests/acceptance/features/webUIWebdavLockProtection/delete.feature
  tests/acceptance/features/webUIWebdavLockProtection/move.feature
  tests/acceptance/features/webUIWebdavLockProtection/upload.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
Labels: QA:team, Status:Needs-Review

#4886 [Tests-Only] Split webUiSharingPublic suite into smaller suites
  .drone.star
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkPublicActions.feature
  tests/acceptance/features/webUISharingPublicManagement/publicLinkIndicator.feature
  tests/acceptance/features/webUISharingPublicManagement/publicLinkShareByEmail.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/features/webUISharingPublicManagement/sharingPublicSession.feature
Labels: QA:team

#4900 [Tests-Only] Split webUiSharingInternalUsers suite into smaller suites
  .drone.star
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersCollaborator/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
Labels: QA:team

#4922 [Tests-Only] Split Resharing test suites
  .drone.star
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIResharing1/reshareUsers.feature
  tests/acceptance/features/webUIResharing2/reshareUsers.feature
Labels: QA:team

#4880 [CI] Cache and Reuse ocis binary for tests
  .drone.env
  .drone.star
  tests/acceptance/run.sh
  tests/drone/build-ocis.sh
Labels: QA:team, Type:CI

#4958 [CI] split ocis Files test suite in CI
  .drone.star
Labels: QA:team, Type:CI

#4959 [CI] Update screenshots cache server endpoint
  .drone.star
Labels: QA:team, Type:CI

#4953 [Tests-Only] Refactor `webUIResharing` and `webUIResharingToRoot` tests to not use skeleton files
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIResharing1/reshareUsers.feature
  tests/acceptance/features/webUIResharing2/reshareUsers.feature
  tests/acceptance/features/webUIResharingToRoot/reshareUsers.feature
Labels: QA:team

#4970 [Tests-Only] Remove promise limit and delete share_folder config on before
  tests/acceptance/helpers/config.js
  tests/acceptance/helpers/occHelper.js
  tests/acceptance/setup.js
Labels: QA:team, Status:Needs-Review

#4967 [Tests-Only] Remove sharingToRoot test pipelines from oCIS acceptance test
  .drone.star
Labels: QA:team

#4950 [Tests-Only] Refactor `sharingPublic` tests to not use skeleton files
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkPublicActions.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
  tests/acceptance/features/webUISharingPublicManagement/publicLinkIndicator.feature
  tests/acceptance/features/webUISharingPublicManagement/publicLinkShareByEmail.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/features/webUISharingPublicManagement/sharingPublicSession.feature
Labels: QA:team

#4932 [Tests-Only] refactor tags and trashbin tests to not use skeleton files
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUITags/createTags.feature
  tests/acceptance/features/webUITags/tagsSuggestion.feature
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
  tests/acceptance/features/webUITrashbinFilesFolders/trashbinFilesFolders.feature
  tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
Labels: QA:team, Status:Needs-Review

#4975 Adapt breadcrumbs baseUrl according to recent route changes
  changelog/unreleased/enhancement-accessibility-improvements
  packages/web-app-files/src/components/AppBar.vue
Labels: Status:Needs-Review

#4956 [Tests-Only] Refactor `webUISharingInternalUsersSharingIndicator` tests to not use skeleton files
  .drone.star
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature
Labels: QA:team

#4974 [Tests-Only] refactor restrict sharing tests to not use skeleton files
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-openid-login.md
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
  tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature
  tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
Labels: QA:team, Status:Needs-Review

#4968 [Tests-Only] refactor files and rename tests to not use skeleton files
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIFilesList/fileList.feature
  tests/acceptance/features/webUIFilesList/sort.feature
  tests/acceptance/features/webUIFilesSearch/search.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/vrt/baseline/oc10/topBar.png
  tests/vrt/baseline/ocis/topBar.png
Labels: QA:team, Status:Needs-Review

#4962 [Tests-Only] Refactor `webUISharingInternalGroupsToRoot` tests to not use skeleton files
  .drone.star
  tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRootEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature
Labels: QA:team

#4957 [Tests-Only] refactor share permission tests to not use skeleton files
  tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-openid-login.md
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
  tests/acceptance/features/webUISharingNotifications/notificationLink.feature
  tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature
  tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
  tests/acceptance/features/webUISharingNotificationsToRoot/notificationLink.feature
  tests/acceptance/features/webUISharingNotificationsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingNotificationsToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingPermissionToRoot/shareFileWithMultipleUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/shareFolderWithMultipleUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFileGroup.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFoldersGroup.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
  tests/acceptance/features/webUITags/tagsSuggestion.feature
  tests/acceptance/features/webUIWebdavLockProtection/move.feature
  tests/acceptance/features/webUIWebdavLockProtection/upload.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
Labels: QA:team

#4961 [Tests-Only] Refactor `webUIInternalUsersToRoot` tests to not use skeleton files (part 2)
  .drone.star
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUISharingInternalUsersToRootPreviews/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature
Labels: QA:team

#4960 [Tests-Only] Refactor `webUIInternalUsersToRoot` tests to not use skeleton files (part 1)
  .drone.star
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootBlacklisted/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootCollaborator/shareWithUsers.feature
Labels: QA:team

#4981 [tests-only] create testfiles/folders async
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team

#4969 [Tests-Only] Refactor `webUISharingExternal` tests to not use skeleton files
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: QA:team

#4984 [Tests-Only] Wait for Rename button to be in enabled state
  tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
Labels: QA:team

#4976 [Tests-Only] Get share indicators of a resource with retry
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team

#4985 Show search button in search bar
  changelog/unreleased/enhancement-show-search-button
  packages/web-runtime/src/components/SearchBar.vue
  tests/vrt/baseline/oc10/topBar.png
Labels: Status:Needs-Review, Topic:Accessibility

#4991 Implement a proper direct delete
  changelog/unreleased/enhancement-direct-delete
  packages/web-app-files/src/mixins/deleteResources.js
Labels: Status:Needs-Review, Topic:Accessibility

#4990 Improve docker image
  Dockerfile
Labels: Status:Needs-Review

#4978 [tests-only] pin core commit id
  .drone.env
  .drone.star
Labels: QA:team

#5009 feat: use real titles in location picker
  changelog/unreleased/enhancement-real-location-picker-title
  packages/web-app-files/src/views/LocationPicker.vue
Labels: Category:Enhancement

#4979 [Tests-Only] Refactor webUI scenarios to prevent unnecessary skeleton file creation
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUILogin/adminBlocksUser.feature
  tests/acceptance/features/webUILogin/oauthLogin.feature
  tests/acceptance/features/webUILogin/openidLogin.feature
  tests/acceptance/features/webUIMarkdownEditor/markdownFile.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
  tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
Labels: QA:team

#4838 [Tests-only] Refactoring webui tests so that they use correct sketeton files
  tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature
  tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFilePermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
Labels: QA:team

#5007 [Tests-Only] Debug filesList intermittent fails
  tests/acceptance/features/webUIFilesList/fileList.feature
Labels: QA:team

#4937 Use oc-select to select roles
  changelog/unreleased/enhancement-select-roles
  packages/web-app-files/src/components/Collaborators/Collaborator.vue
  packages/web-app-files/src/components/Collaborators/CollaboratorsEditOptions.vue
  packages/web-app-files/src/components/Collaborators/EditCollaborator.vue
  packages/web-app-files/src/components/Collaborators/NewCollaborator.vue
  packages/web-app-files/src/components/PublicLinksSidebar/EditPublicLink.vue
  packages/web-app-files/src/components/RoleItem.vue
  packages/web-app-files/src/components/Roles/RoleItem.vue
  packages/web-app-files/src/components/Roles/RolesSelect.vue
  packages/web-app-files/src/helpers/collaboratorRolesDefinition.js
  packages/web-app-files/src/helpers/publicLinkRolesDefinition.js
  packages/web-app-files/src/mixins/collaborators.js
  tests/acceptance/helpers/stringHelper.js
  tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
Labels: Category:Enhancement

#5000 Improve accessibility for the files sidebar
  changelog/unreleased/enhancement-files-sidebar-accessibility
  packages/web-app-files/src/components/AppBar.vue
  packages/web-app-files/src/components/Sidebar.vue
  packages/web-app-files/src/components/Sidebar/ActionsAccordion.vue
  packages/web-app-files/src/mixins/actions/copy.js
  packages/web-app-files/src/mixins/actions/delete.js
  packages/web-app-files/src/mixins/actions/download.js
  packages/web-app-files/src/mixins/actions/favorite.js
  packages/web-app-files/src/mixins/actions/fetch.js
  packages/web-app-files/src/mixins/actions/move.js
  packages/web-app-files/src/mixins/actions/navigate.js
  packages/web-app-files/src/mixins/actions/rename.js
  packages/web-app-files/src/mixins/actions/restore.js
  packages/web-app-files/src/mixins/fileActions.js
  packages/web-runtime/src/directives/clickOutside.js
  packages/web-runtime/src/index.js
  tests/acceptance/features/webUIFilesActionMenu/fileFolderActionMenu.feature
  tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
  tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
Labels: Status:Needs-Review, Topic:Accessibility

#5008 Move location picker hint under breadcrumbs
  changelog/unreleased/enhancement-move-location-picker-hint
  packages/web-app-files/src/components/LocationPicker/CopySidebarMainContent.vue
  packages/web-app-files/src/components/LocationPicker/MoveSidebarMainContent.vue
  packages/web-app-files/src/views/LocationPicker.vue
  packages/web-runtime/src/App.vue
  packages/web-runtime/src/store/sidebar.js
Labels: Category:Enhancement

#5010 Improve accessibility on user menu
  changelog/unreleased/enhancement-user-menu-a11y
  packages/web-runtime/src/components/UserMenu.vue
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIFilesCopy/copy.feature
  tests/acceptance/features/webUIFilesCopy/copyPrivateLinks.feature
  tests/acceptance/features/webUIFilesDetails/fileDetails.feature
Labels: Status:Needs-Review, Topic:Accessibility

#5012 Use a proper definition list for the account settings page
  changelog/unreleased/enhancement-account-definition-list
  packages/web-runtime/src/pages/account.vue
  tests/acceptance/pageObjects/accountPage.js
Labels: Status:Needs-Review, Topic:Accessibility

#5023 fix: display navigation for resolved private link
  changelog/unreleased/bugfix-navigation-in-private-links
  packages/web-app-files/src/views/PrivateLink.vue
Labels: Type:Bug

#5033 [tests-only] Remove tech_preview setting from CI and docs
  .drone.star
  docs/backend-oc10.md
Labels: QA:team

#5016 [Tests-Only] Run smoke tests with oc10-integration app
  .drone.star
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
  tests/drone/config-oc10-integration-app-oauth.json
Labels: QA:team

#5039 fix: add missing healthcheck script
  .drone.star
  docker/Dockerfile
  docker/overlay/usr/bin/healthcheck
Labels: Status:Needs-Review

#5053 Change appearance of the share action buttons
  changelog/unreleased/enhancement-share-action-buttons
  packages/web-app-files/src/views/SharedWithMe.vue
Labels: Status:Needs-Review, Topic:Accessibility
