Repository owncloud/web, pull requests merged in 2021-03, with the labels that each got.

#4780 [tests-only] Fix expected failures for sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
Labels: QA:team

#4782 [Tests-Only] fix createUser function to handle users without email
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: QA:team

#4781 [CI] fix uploading screenshots to github on test failure
  .drone.star
Labels: QA:team

#4793 [tests-only] bump ocis commit id
  .drone.env
Labels: QA:team

#4794 [tests-only] Refactor some function and var names
  tests/acceptance/stepDefinitions/generalContext.js
Labels: QA:team

#4792 [Tests-Only] Update expected to failure file
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIResharing/reshareUsers.feature
  tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
Labels: QA:team

#4799 [tests-only] Bump ocis commit id 2021-03-09
  .drone.env
Labels: QA:team

#4686 [Tests-Only] Acceptance test for password protected public share
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
Labels: QA:team

#4803 [docs-only] Improve docs for running acceptance tests
  docs/testing.md
Labels: QA:team

#4804 [tests-only] Bump ocis commit id 2021-03-11
  .drone.env
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
Labels: QA:team

#4800 [tests-only] Adjusts webUI test scenarios with tries to in its step while canceling copy and move
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIFiles/copy.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team

#4807 [CI] Bump ocis commit id 2021-03-15
  .drone.env
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
Labels: QA:team

#4820 set NODE_ENV based on rollup build type
  changelog/unreleased/fix-node-env
  rollup.config.js
Labels: Status:Needs-Review

#4821 fix typo in makefile
  packages/web-runtime/l10n/Makefile
Labels: Type:Bug

#4825 [tests-only] Bump OCIS_COMMITID to 2021-03-17
  .drone.env
Labels: QA:team

#4827 [tests-only] Bump commit id for tests
  .drone.env
Labels: QA:team

#4689 download password protected public shared files using pre-signed url
  changelog/unreleased/public-link-download
  packages/web-app-files/src/mixins/actions/fetch.js
  packages/web-app-files/src/store/actions.js
  packages/web-app-files/src/store/state.js
  packages/web-app-media-viewer/src/App.vue
  packages/web-app-media-viewer/src/mixins/loader.js
  packages/web-runtime/src/plugins/web.js
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
Labels: Priority:p1-urgent, QA:p1, Status:Blocked

#4841 Bump version for release 2.1.0
  changelog/2.1.0_2021-03-24/bugfix-missing-tanslations-in-applications-menu
  changelog/2.1.0_2021-03-24/bugfix-node-env
  changelog/2.1.0_2021-03-24/bugfix-remove-unsupported-shareType
  changelog/2.1.0_2021-03-24/enhancement-a11y-improvements-for-meta-attributes
  changelog/2.1.0_2021-03-24/enhancement-moment-js-set-locale-for-i18n
  changelog/2.1.0_2021-03-24/enhancement-public-link-download
  package.json
  packages/web-integration-oc10/appinfo/info.xml
Labels: Interaction:Minor-Release

#4812 added route change announcement
  changelog/unreleased/enhancement-live-region-updates
  packages/web-runtime/src/App.vue
  packages/web-runtime/src/router/index.js
Labels: Category:Enhancement, Topic:Accessibility

#4879 [Tests-Only] Fix unexpected passes of `imageMediaViewer` and `shareByPublicLink` tests
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-openid-login.md
Labels: QA:team

#4884 [tests-only] speed up web tests by reducing timeouts
  tests/acceptance/customCommands/waitForAjaxCallsToStartAndFinish.js
  tests/acceptance/pageObjects/personalPage.js
Labels: QA:team

#4897 [Tests-Only] Skip file deletion fail in public share
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
  tests/acceptance/features/webUITrashbinFilesFolders/trashbinFilesFolders.feature
Labels: QA:team

#4874 [Tests-Only] Fix test scenarios with same title on same file
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
  tests/acceptance/features/webUILogin/adminBlocksUser.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/features/webUIResharing/reshareUsers.feature
  tests/acceptance/features/webUIResharingToRoot/reshareUsers.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
  tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
Labels: QA:team
