Repository owncloud/web, pull requests merged in 2021-11, with the labels that each got.

#5965 [tests-only][full-ci]Bump commit id
  .drone.env
Labels: QA:team

#5979 [tests-only] Do not retry failed acceptance tests in cron nightly
  .drone.star
  tests/acceptance/run.sh
Labels: QA:team

#5983 Reduce sidebar width in files app
  changelog/unreleased/enhancement-files-sidebar-reduced-width
  packages/web-app-files/src/App.vue
  packages/web-app-files/src/components/SideBar/FileInfo.vue
Labels: Category:Enhancement, Type:Design, Early-Adopter:CERN

#5966 [Tests-Only] refactor date selection in integration tests for expiration dates in shares
  packages/web-app-files/tests/integration/specs/peopleExpirationDate.spec.js
Labels: QA:team

#6008 make it possible to run integration and unit tests with linked ODS
  package.json
  packages/web-app-files/tests/unit/components/Search/List.spec.js
  tests/integration/config/jest.config.js
  tests/unit/config/jest.config.js
  yarn.lock
Labels: Status:Needs-Review

#5996 Automatically show oC10 apps in app switcher menu
  changelog/unreleased/enhancement-oc10-apps-in-app-switcher
  changelog/unreleased/enhancement-update-ods
  docs/deployments/oc10-app.md
  packages/web-integration-oc10/lib/Controller/ConfigController.php
  packages/web-runtime/package.json
  yarn.lock
Labels: Status:Needs-Review, Platform:oC10

#5795 [unit-tests-only] Implemented `todo` unit tests for route helper
  packages/web-app-files/tests/unit/helpers/route.spec.js
Labels: QA:team

#6021 late deliver of accentuate new files tests
  packages/web-app-files/src/helpers/store.ts
  packages/web-app-files/tests/unit/helpers/store.spec.ts
  packages/web-app-files/tests/unit/helpers/ui/filesList.spec.ts
  packages/web-app-files/tests/unit/views/Personal.spec.js
  packages/web-app-files/tests/unit/views/PublicFiles.spec.ts
  packages/web-app-files/tests/unit/views/views.shared.ts
Labels: Status:Needs-Review

#6031 fix url to fetch capabilities
  changelog/unreleased/bugfix-capabilites-fetched-when-server-runs-in-subfolder
  packages/web-runtime/src/store/user.js
Labels: QA:team

#6028 [tests-only] [full-ci] fix for intermittent share-exp-date test fail
  tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
Labels: QA:team

#6034 [tests-only] [full-ci] latest ocis commit id bump
  .drone.env
Labels: QA:team

#6043 [tests-only] [full-ci] adds `@skipOnOC10` tag
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
Labels: QA:team

#6050 revert processDirectoryEntryRecursively
  packages/web-app-files/src/mixins.js
Labels: Status:Needs-Review

#6058 [tests-only][full-ci] Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#6049 convert FileListHeaderPosition mixin to composable
  packages/web-app-files/src/components/AppBar/AppBar.vue
  packages/web-app-files/src/components/Search/List.vue
  packages/web-app-files/src/composables/index.ts
  packages/web-app-files/src/composables/store/index.ts
  packages/web-app-files/src/composables/store/mutationSubscription.ts
  packages/web-app-files/src/composables/store/store.ts
  packages/web-app-files/src/composables/useFileListHeaderPosition/index.ts
  packages/web-app-files/src/helpers/store.ts
  packages/web-app-files/src/mixins/filesListPositioning.js
  packages/web-app-files/src/views/Favorites.vue
  packages/web-app-files/src/views/LocationPicker.vue
  packages/web-app-files/src/views/Personal.vue
  packages/web-app-files/src/views/PublicFiles.vue
  packages/web-app-files/src/views/SharedViaLink.vue
  packages/web-app-files/src/views/SharedWithMe.vue
  packages/web-app-files/src/views/SharedWithOthers.vue
  packages/web-app-files/src/views/Trashbin.vue
  packages/web-app-files/tests/unit/composables/store/mutationSubscription.spec.ts
  packages/web-app-files/tests/unit/composables/store/spec/index.ts
  packages/web-app-files/tests/unit/composables/store/store.spec.ts
  packages/web-app-files/tests/unit/composables/useFileListHeaderPosition/index.spec.ts
  packages/web-app-files/tests/unit/composables/useFileListHeaderPosition/spec/index.ts
  packages/web-app-files/tests/unit/helpers/store.spec.ts
  packages/web-app-files/tests/unit/views/views.shared.ts
  tests/unit/config/jest.config.js
Labels: Status:Needs-Review, Type:Technical-Debt

#6044 Implement breadcrumb context menu
  changelog/unreleased/enhancement-breadcrumb-context-menu
  packages/web-app-files/src/components/AppBar/AppBar.vue
  packages/web-app-files/src/mixins/actions/delete.js
  packages/web-app-files/src/mixins/actions/rename.js
  packages/web-app-files/src/mixins/deleteResources.js
  packages/web-app-files/src/store/actions.js
  packages/web-app-files/tests/unit/mixins/actions/delete.spec.js
  packages/web-app-files/tests/unit/mixins/actions/rename.spec.js
  packages/web-app-files/tests/unit/mixins/deleteResources.spec.js
  packages/web-runtime/package.json
  packages/web-runtime/tests/unit/components/__snapshots__/ApplicationsMenu.spec.js.snap
  yarn.lock
Labels: Category:Enhancement, Status:Needs-Review

#6064 [tests-only] Shorten pipeline names
  .drone.star
Labels: QA:team

#6066 [tests-only] [full-ci] latest ocis commit id bump
  .drone.env
Labels: QA:team

#6067 [Tests-Only][full-ci] increase the wait for condition timeout to 10s for acceptance tests
  tests/acceptance/nightwatch.conf.js
Labels: QA:team

#6065 [full-ci] refactor pagination into composable, cleanup store, views and tests
  packages/web-app-files/src/components/AppBar/ViewOptions.vue
  packages/web-app-files/src/components/FilesList/Pagination.vue
  packages/web-app-files/src/components/Search/List.vue
  packages/web-app-files/src/composables/index.ts
  packages/web-app-files/src/composables/router/index.ts
  packages/web-app-files/src/composables/router/useRouteQuery.ts
  packages/web-app-files/src/composables/router/useRouter.ts
  packages/web-app-files/src/composables/store/index.ts
  packages/web-app-files/src/composables/store/useMutationSubscription.ts
  packages/web-app-files/src/composables/store/useStore.ts
  packages/web-app-files/src/composables/useDefaults/index.ts
  packages/web-app-files/src/composables/usePagination/index.ts
  packages/web-app-files/src/composables/utils/index.ts
  packages/web-app-files/src/composables/utils/types.ts
  packages/web-app-files/src/mixins/actions/emptyTrashBin.js
  packages/web-app-files/src/mixins/filesListFilter.js
  packages/web-app-files/src/mixins/filesListPagination.js
  packages/web-app-files/src/store/getters.js
  packages/web-app-files/src/store/index.js
  packages/web-app-files/src/store/modules/pagination.js
  packages/web-app-files/src/views/Favorites.vue
  packages/web-app-files/src/views/LocationPicker.vue
  packages/web-app-files/src/views/Personal.vue
  packages/web-app-files/src/views/PublicFiles.vue
  packages/web-app-files/src/views/SharedViaLink.vue
  packages/web-app-files/src/views/SharedWithOthers.vue
  packages/web-app-files/src/views/Trashbin.vue
  packages/web-app-files/tests/integration/specs/pagination.spec.js
  packages/web-app-files/tests/unit/components/AppBar/ViewOptions.spec.js
  packages/web-app-files/tests/unit/components/FilesList/Pagination.spec.js
  packages/web-app-files/tests/unit/components/Search/List.spec.js
  packages/web-app-files/tests/unit/components/Search/__snapshots__/List.spec.js.snap
  packages/web-app-files/tests/unit/composables/router/spec/index.ts
  packages/web-app-files/tests/unit/composables/router/useRouteQuery.spec.ts
  packages/web-app-files/tests/unit/composables/router/useRouter.spec.ts
  packages/web-app-files/tests/unit/composables/store/useMutationSubscription.spec.ts
  packages/web-app-files/tests/unit/composables/store/useStore.spec.ts
  packages/web-app-files/tests/unit/composables/usePagination/index.spec.ts
  packages/web-app-files/tests/unit/composables/usePagination/spec/index.ts
  packages/web-app-files/tests/unit/store/getters.spec.js
  packages/web-app-files/tests/unit/store/modules/pagination.spec.js
  packages/web-app-files/tests/unit/views/Favorites.spec.js
  packages/web-app-files/tests/unit/views/Personal.spec.js
  packages/web-app-files/tests/unit/views/PublicFiles.spec.ts
  packages/web-app-files/tests/unit/views/views.setup.js
  packages/web-app-files/tests/unit/views/views.shared.ts
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
Labels: Type:Technical-Debt

#5756 [unit-tests] Implemented todo unit tests for public link view
  packages/web-app-files/src/views/PublicLink.vue
  packages/web-app-files/tests/unit/components/FilesList/Pagination.spec.js
  packages/web-app-files/tests/unit/views/PublicLink.spec.js
  packages/web-app-files/tests/unit/views/__snapshots__/PublicLink.spec.js.snap
Labels: QA:team

#6037 Add tooltips with absolute dates to relative dates
  changelog/unreleased/enhancement-relative-date-tooltips
  packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
  packages/web-app-files/src/components/SideBar/FileInfo.vue
  packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkInfo.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/ShowCollaborator.vue
  packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
  packages/web-app-files/src/mixins.js
  packages/web-app-files/tests/unit/components/SideBar/FileInfo.spec.js
  packages/web-runtime/package.json
  yarn.lock
Labels: Category:Enhancement
