Repository owncloud/web, pull requests merged in 2021-09, with the labels that each got.

#5675 [full-ci] feat(smoke tests): automated parallel smoke tests
  .drone.env
  .drone.star
  .eslintrc.js
  cucumber.js
  package.json
  tests/acceptance/run.sh
  tests/acceptance/setup.js
  tests/acceptance/stepDefinitions/accountContext.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
  tests/acceptance/stepDefinitions/loginContext.js
  tests/acceptance/stepDefinitions/markdownEditorContext.js
  tests/acceptance/stepDefinitions/messagesContext.js
  tests/acceptance/stepDefinitions/notificationsContext.js
  tests/acceptance/stepDefinitions/previewContext.js
  tests/acceptance/stepDefinitions/privateLinksContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
  tests/acceptance/stepDefinitions/searchContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
  tests/acceptance/stepDefinitions/visualContext.js
  tests/acceptance/stepDefinitions/webdavContext.js
  tests/smoke/README.md
  tests/smoke/features/kindergarten.feature
  tests/smoke/features/step_definitions/api.ts
  tests/smoke/features/step_definitions/app.files.ts
  tests/smoke/features/step_definitions/runtime.ts
  tests/smoke/features/step_definitions/session.ts
  tests/smoke/support/api/http.ts
  tests/smoke/support/api/index.ts
  tests/smoke/support/api/user.ts
  tests/smoke/support/config.ts
  tests/smoke/support/cta/files/index.ts
  tests/smoke/support/cta/files/misc.ts
  tests/smoke/support/cta/files/sidebar.ts
  tests/smoke/support/cta/index.ts
  tests/smoke/support/cucumber/index.ts
  tests/smoke/support/cucumber/snippets-syntax.js
  tests/smoke/support/index.ts
  tests/smoke/support/page/files/allFiles.ts
  tests/smoke/support/page/files/index.ts
  tests/smoke/support/page/files/sharedWithMe.ts
  tests/smoke/support/page/index.ts
  tests/smoke/support/page/login/index.ts
  tests/smoke/support/page/login/oc10.ts
  tests/smoke/support/page/login/ocis.ts
  tests/smoke/support/page/runtime.ts
  tests/smoke/support/store/actor.ts
  tests/smoke/support/store/index.ts
  tests/smoke/support/store/user.ts
  tests/smoke/support/types.ts
  tests/smoke/support/world/actor.setup.ts
  tests/smoke/support/world/actor.ts
  tests/smoke/support/world/file.ts
  tests/smoke/support/world/index.ts
  tests/smoke/support/world/user.ts
  tsconfig.json
  yarn.lock
Labels: Type:CI, QA:testing

#5784 [tests-only] [full-ci] Bump CORE_COMMITID
  .drone.env
Labels: QA:team

#5557 [unit-tests-only] add unit tests for files actions sidebar
  packages/web-app-files/tests/__fixtures__/fileActions.js
  packages/web-app-files/tests/unit/components/SideBar/Actions/FileActions.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Actions/__snapshots__/FileActions.spec.js.snap
Labels: QA:team

#5787 [tests-only] [full-ci] Bump OCIS_COMMITID
  .drone.env
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFilesList/fileList.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkPublicActions.feature
Labels: QA:team

#5632 [full-ci] feat: redesign recipient roles select
  changelog/unreleased/enhancement-redesign-recipient-role-select
  packages/web-app-files/src/components/SideBar/Shared/RoleItem.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditCollaborator.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/NewCollaborator.vue
  packages/web-app-files/src/helpers/collaboratorRolesDefinition.js
  packages/web-app-files/src/mixins/collaborators.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ShowCollaborator.spec.js
  tests/acceptance/features/webUIResharing1/reshareUsers.feature
  tests/acceptance/features/webUIResharing2/reshareUsers.feature
  tests/acceptance/features/webUIResharingToRoot/reshareUsers.feature
  tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFilePermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersCollaborator/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootCollaborator/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingPermissionToRoot/shareFileWithMultipleUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/shareFolderWithMultipleUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFileGroup.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFoldersGroup.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
Labels: Category:Enhancement

#5779 [unit-tests-only] Add TODO unit tests for publicLinkRolesDefinition helper
  packages/web-app-files/tests/unit/helpers/publicLinkRolesDefinition.spec.js
Labels: QA:team

#5717 [unit-tests] Add unit tests for ApplicationsMenu component
  packages/web-runtime/tests/unit/components/ApplicationsMenu.spec.js
  packages/web-runtime/tests/unit/components/__snapshots__/ApplicationsMenu.spec.js.snap
Labels: QA:team

#5791 [unit-tests-only] Add unit tests for publicLinkRolesDefinition helper
  packages/web-app-files/tests/unit/helpers/publicLinkRolesDefinition.spec.js
Labels: QA:team

#5755 [unit-tests-only] Add unit tests for PrivateLink view
  packages/web-app-files/tests/unit/views/PrivateLink.spec.js
  packages/web-app-files/tests/unit/views/__snapshots__/PrivateLink.spec.js.snap
  packages/web-app-files/tests/unit/views/views.setup.js
Labels: QA:team

#5718 [unit-tests-only] Add unit tests for Avatar component
  packages/web-runtime/tests/unit/components/Avatar.spec.js
Labels: QA:team

#5694 [unit-tests-only] Add unit tests for Preview component
  packages/web-app-files/tests/unit/components/Search/Preview.spec.js
Labels: QA:team

#5775 [unit-tests-only] Added unit tests todo items for route helper
  packages/web-app-files/tests/unit/helpers/route.spec.js
Labels: QA:team

#5771 [unit-tests-only] Added todo unit tests for statusIndicator helper
  packages/web-app-files/tests/unit/helpers/statusIndicator.spec.js
Labels: QA:team

#5772 [unit-tests-only] Added unit tests todo items for textUtils helper
  packages/web-app-files/tests/unit/helpers/textUtils.spec.js
Labels: QA:team

#5665 [full-ci] feat: fetch file info in the sidebar
  __fixtures__/files.js
  __fixtures__/sharedFiles.js
  __mocks__/sdk.js
  changelog/unreleased/enhancement-fetch-file-info-in-sidebar
  packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
  packages/web-app-files/src/components/SideBar/FileInfo.vue
  packages/web-app-files/src/components/SideBar/Links/FileLinks.vue
  packages/web-app-files/src/components/SideBar/Links/PrivateLinkItem.vue
  packages/web-app-files/src/components/SideBar/SideBar.vue
  packages/web-app-files/src/fileSideBars.js
  packages/web-app-files/src/index.js
  packages/web-app-files/src/mixins/actions/favorite.js
  packages/web-app-files/src/routes.js
  packages/web-app-files/src/store/actions.js
  packages/web-app-files/tests/integration/specs/sidebar.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Links/FileLinks.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Links/PrivateLinkItem.spec.js
  packages/web-app-files/tests/unit/components/SideBar/SideBar.spec.js
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
  tests/integration/config/jest.init.js
Labels: Category:Enhancement

#5802 [full-ci][tests-only] Bump commit ids for tests
  .drone.env
Labels: QA:team

#5816 [full-ci][tests-only] Bump commit ids for tests
  .drone.env
Labels: QA:team

#5829 [docs-only] Remove trailing commas from json snippets, add validator hint
  docs/deployments/oc10-app.md
Labels: Topic:Documentation

#5827 [tests-only] [full-ci] Bump commit ids for testing
  .drone.env
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
  tests/acceptance/features/webUIResharing1/reshareUsers.feature
  tests/acceptance/features/webUIResharing2/reshareUsers.feature
  tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFilePermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersBlacklisted/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersCollaborator/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersExpire/shareWithUsersExpiringShares.feature
  tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature
  tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
  tests/acceptance/helpers/sharingHelper.js
Labels: QA:team

#5830 [tests-only] fix bash script for running acceptance tests
  tests/acceptance/run.sh
Labels: QA:team

#5833 [tests-only] Do not skip npm install when there are only unit test changes
  .drone.star
Labels: QA:team

#5849 [full-ci][tests-only]Bump core and ocis commit id for tests
  .drone.env
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
Labels: QA:team

#5852 [tests-only full-ci] disable previews in tests that check sharing indicators
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
  tests/acceptance/features/webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublicManagement/publicLinkIndicator.feature
Labels: QA:team

#5680 [unit-tests-only] added unit tests for files drop view
  packages/web-app-files/tests/unit/views/FilesDrop.spec.js
  packages/web-app-files/tests/unit/views/__snapshots__/FilesDrop.spec.js.snap
  packages/web-app-files/tests/unit/views/views.setup.js
Labels: QA:team
