Repository owncloud/web, pull requests merged in 2021-08, with the labels that each got.

#5601 [tests-only] Bump test commit ids
  .drone.env
Labels: QA:team

#5577 [unit-tests] Added unit tests for link actions component
  packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkActions.spec.js
Labels: QA:team

#5623 [tests-only] run unit and integration tests on tags
  .drone.star
Labels: QA:team

#5631 [unit-tests-only] Run minimum pipelines for unit tests only PRs
  .drone.star
Labels: QA:team

#5626 [full-ci][tests-only] Bump core and ocis commit id to latest
  .drone.env
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
Labels: QA:team

#5641 [docs-only] Do not run unit and acceptance test pipelines for docs only PRs
  .drone.star
  Makefile
Labels: QA:team

#5603 [unit-tests-only] Add unit tests for AppBar component
  packages/web-app-files/tests/unit/components/AppBar/AppBar.spec.js
Labels: QA:team

#5629 Added unit tests for link list item component
  packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/ListItem.spec.js
Labels: QA:team

#5655 [full-ci] fix: escape image name in media viewer
  changelog/unreleased/bugfix-escape-file-path-in-media-viewer
  packages/web-app-media-viewer/src/App.vue
  packages/web-app-media-viewer/src/mixins/loader.js
Labels: Type:Bug

#5550 [full-ci] [tests-only] Open jpeg file in "shared with me page" or "shared with other"
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
Labels: QA:team

#5642 Added unit tests for resources mixin
  packages/web-app-files/tests/unit/mixins/resources.spec.js
Labels: QA:team

#5667 [full-ci] [tests-only] Bump commit id for oCIS
  .drone.env
  tests/acceptance/features/webUIUpload/upload.feature
Labels: QA:team

#5658 Added unit tests for permissions helper
  packages/web-app-files/tests/unit/helpers/permissions.spec.js
Labels: QA:team

#5677 [CI] Fix diff calculation for drone builds
  .drone.star
  tests/drone/if-diff-has-unit-tests-only.sh
Labels: QA:team

#5638 Added unit tests for sidebar link components
  packages/web-app-files/src/components/SideBar/Links/FileLinks.vue
  packages/web-app-files/src/components/SideBar/Links/PrivateLinkItem.vue
  packages/web-app-files/tests/unit/components/SideBar/Links/CopyToClipboardButton.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Links/FileLinks.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Links/PrivateLinkItem.spec.js
Labels: QA:team

#5624 [unit-tests] Added unit tests for link info component
  packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkInfo.vue
  packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkInfo.spec.js
Labels: QA:team

#5659 [full-ci] feat: refresh list on breadcrumb click
  changelog/unreleased/enhancement-refresh-list-via-breadcrumbs
  packages/web-app-files/src/components/AppBar/AppBar.vue
  packages/web-app-files/src/views/Personal.vue
  packages/web-app-files/src/views/PublicFiles.vue
  packages/web-app-files/tests/integration/specs/appBar.spec.js
Labels: Category:Enhancement

#5691 [tests-only] [full-ci] Fix openIdLogin scenario for login with invalid password
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUILogin/openidLogin.feature
Labels: QA:team

#5692 [tests-only] [full-ci] bump id for core and ocis in web
  .drone.env
Labels: QA:team

#5651 Added unit tests for files mixin
  packages/web-app-files/tests/unit/mixins.spec.js
  packages/web-app-files/tests/unit/mixins/actions/acceptShare.spec.js
Labels: QA:team

#5710 [full-ci] fix(media-viewer): fix davProperties
  changelog/4.1.0_2021-08-19/bugfix-load-folder-in-media-viewer
  packages/web-app-media-viewer/src/mixins/loader.js
Labels: Type:Bug

#5713 [full-ci] [tests-only] Bump commit ids
  .drone.env
Labels: QA:team

#5720 [unit-tests-only] Add unit tests for SkipTo component
  packages/web-runtime/tests/unit/components/SkipTo.spec.js
Labels: QA:team

#5682 [unit-tests] Add unit tests for ProgressBar component
  packages/web-app-files/src/components/Upload/ProgressBar.vue
  packages/web-app-files/tests/unit/components/Upload/ProgressBar.spec.js
Labels: QA:team

#5721 [unit-tests-only] Add unit tests for OcAppContent component
  packages/web-runtime/tests/unit/components/OcAppContent.spec.js
Labels: QA:team

#5746 [unit-tests-only] Refactored favorites spec to use helper functions and variable selectors
  packages/web-app-files/tests/unit/views/Favorites.spec.js
  packages/web-app-files/tests/unit/views/views.setup.js
Labels: QA:team

#5734 [tests-only][full-ci] Exclude test suites that are not meant to run on oCIS
  tests/acceptance/run.sh
  tests/acceptance/suites-not-to-run-on-ocis.txt
Labels: QA:team

#5649 Added unit test for FileVersions component
  packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
  packages/web-app-files/tests/unit/components/SideBar/Versions/FileVersions.spec.js
Labels: QA:team

#5609 [unit-tests] Added unit tests for link edit component
  packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkEdit.vue
  packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkEdit.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/__snapshots__/LinkEdit.spec.js.snap
Labels: QA:team

#5749 [unit-tests] Added unit test todo skeleton for public link view
  packages/web-app-files/tests/unit/views/PublicLink.spec.js
Labels: QA:team

#5750 [unit-tests-only] Add todo unit tests for PrivateLink view
  packages/web-app-files/tests/unit/views/PrivateLink.spec.js
Labels: QA:team

#5751 [unit-tests-only] Add todo unit tests for SharedViaLink view
  packages/web-app-files/tests/unit/views/SharedViaLink.spec.js
Labels: QA:team
