Repository owncloud/web, pull requests merged in 2021-12, with the labels that each got.

#6072 [tests-only][full-ci]Fix failing expiration dates tests
  tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
Labels: QA:team

#6047 [tests-only][full-ci]Add valid tests that were removed by PR `#5973`
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
  tests/acceptance/helpers/webdavHelper.js
Labels: QA:team

#5136 [Tests-Only] run tests using middleware in CI
  .drone.star
  docker-compose.yml
  docs/testing-manual.md
  docs/testing.md
  tests/acceptance/features/webUIFilesList/fileList.feature
  tests/acceptance/nightwatch.conf.js
  tests/acceptance/stepDefinitions/middlewareContext.js
Labels: QA:team

#6083 [tests-only]Store upload time after the upload is completed
  tests/acceptance/helpers/webdavHelper.js
Labels: QA:team

#6078 [tests-only][full-ci] latest ocis commit id bump
  .drone.env
Labels: QA:team

#6096 [tests-only] Playwright cache is not needed in nightwatch test pipelines
  .drone.star
Labels: QA:team

#6109 [CI] Restructure CI pipelines to make the CI runtime even
  .drone.star
Labels: QA:team

#6084 [full-ci] Fix inconsistencies in share expiry dates
  __mocks__/sdk.js
  changelog/unreleased/bugfix-expiry-date-inconsistencies
  packages/web-app-files/src/components/SideBar/Links/FileLinks.vue
  packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkActions.vue
  packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkEdit.vue
  packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkInfo.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.vue
  packages/web-app-files/tests/integration/helpers/date.js
  packages/web-app-files/tests/integration/specs/linkExpirationDate.spec.js
  packages/web-app-files/tests/integration/specs/peopleExpirationDate.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkEdit.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkInfo.spec.js
Labels: Type:Bug, Status:Needs-Review

#5985 [full-ci] Small fixes
  changelog/unreleased/bugfix-extension-img
  changelog/unreleased/bugfix-hide-files-by-default
  changelog/unreleased/bugfix-order-extensions
  changelog/unreleased/enhancement-build-options
  changelog/unreleased/enhancement-feedback-on-startup
  packages/web-app-files/src/components/ActionMenuItem.vue
  packages/web-app-files/src/components/AppBar/AppBar.vue
  packages/web-app-files/src/mixins/fileActions.js
  packages/web-app-files/tests/unit/components/ActionMenuItem.spec.js
  packages/web-container/index.html.ejs
  packages/web-runtime/src/pages/oidcCallback.vue
  packages/web-runtime/src/store/apps.js
  rollup.config.js
Labels: Early-Adopter:CERN

#6148 [full-ci] Upstream small CERNbox fixes
  changelog/unreleased/bugfix-extension-img
  changelog/unreleased/bugfix-hide-files-by-default
  changelog/unreleased/bugfix-order-extensions
  changelog/unreleased/enhancement-build-options
  changelog/unreleased/enhancement-default-markdown-mediaviewer-extensions
  changelog/unreleased/enhancement-feedback-on-startup
  packages/web-app-files/src/components/ActionMenuItem.vue
  packages/web-app-files/src/components/AppBar/AppBar.vue
  packages/web-app-files/src/mixins/fileActions.js
  packages/web-app-files/tests/unit/components/ActionMenuItem.spec.js
  packages/web-app-markdown-editor/src/index.js
  packages/web-app-media-viewer/src/index.js
  packages/web-container/index.html.ejs
  packages/web-runtime/src/pages/oidcCallback.vue
  packages/web-runtime/src/store/apps.js
  rollup.config.js
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
  tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
Labels: Early-Adopter:CERN

#6135 Ensure route config is honored for new file handlers
  changelog/unreleased/bugfix-new-file-handler
  packages/web-app-files/src/components/AppBar/AppBar.vue
  packages/web-app-files/src/helpers/route.js
  packages/web-runtime/src/store/apps.js
Labels: Type:Bug, Early-Adopter:CERN

#6153 [tests-only] do not run acceptance tests if only smoke tests changed
  .drone.star
Labels: QA:team

#6170 [tests-only][full-ci]Fix expiration date failing tests
  tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
Labels: QA:team

#5778 [unit-tests-only] Add unit tests for SharedViaLink view
  packages/web-app-files/tests/unit/views/SharedViaLink.spec.js
  packages/web-app-files/tests/unit/views/__snapshots__/SharedViaLink.spec.js.snap
  packages/web-app-files/tests/unit/views/views.setup.js
Labels: QA:team

#6089 [tests-only][full-ci]Adds test related to renaming of file
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/pageObjects/FilesPageElement/contextMenu.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team

#6176 improve people sharing sidebar
  changelog/unreleased/enhancement-respect-share-expiration-date
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
  packages/web-app-files/src/components/SideBar/Shares/InviteCollaborator/ExpirationDatepicker.vue
  packages/web-app-files/src/components/SideBar/Shares/InviteCollaborator/InviteCollaboratorForm.vue
  packages/web-app-files/src/gettext.js
  packages/web-app-files/tests/integration/specs/peopleExpirationDate.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Details/FileDetailsMultiple.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ListItem.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/InviteCollaborator/AutocompleteItem.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/InviteCollaborator/ExpirationDatepicker.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/InviteCollaborator/ExpirationDatepicker.spec.ts
  packages/web-app-files/tests/unit/views/Favorites.spec.js
  packages/web-runtime/package.json
  tests/smoke/support/page/files/allFiles.ts
  web.d.ts
  yarn.lock
Labels: Status:Needs-Review

#6200 [tests-only][full-ci]Remove the tests present in middleware from notificationsContext.js
  tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
  tests/acceptance/features/webUISharingNotifications/notificationLink.feature
  tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature
  tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
  tests/acceptance/features/webUISharingNotificationsToRoot/notificationLink.feature
  tests/acceptance/features/webUISharingNotificationsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingNotificationsToRoot/shareWithUsers.feature
  tests/acceptance/stepDefinitions/notificationsContext.js
Labels: QA:team

#6201 [tests-only][full-ci] Bump oCIS commit id for tests
  .drone.env
Labels: QA:team

#6086 [full-ci] Redesign main layout
  __fixtures__/sidebarNavItems.js
  changelog/unreleased/enhancement-redesign-main-layout
  changelog/unreleased/enhancement-update-ods
  packages/web-app-files/src/App.vue
  packages/web-app-files/tests/unit/components/Search/__snapshots__/List.spec.js.snap
  packages/web-app-markdown-editor/src/App.vue
  packages/web-app-media-viewer/src/App.vue
  packages/web-runtime/package.json
  packages/web-runtime/src/App.vue
  packages/web-runtime/src/components/ApplicationsMenu.vue
  packages/web-runtime/src/components/FeedbackLink.vue
  packages/web-runtime/src/components/Notifications.vue
  packages/web-runtime/src/components/OcAppContent.vue
  packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
  packages/web-runtime/src/components/SidebarNav/SidebarNavItem.vue
  packages/web-runtime/src/components/TopBar.vue
  packages/web-runtime/src/components/UserMenu.vue
  packages/web-runtime/src/defaults/vue.js
  packages/web-runtime/src/store/index.js
  packages/web-runtime/src/store/navigation.js
  packages/web-runtime/tests/unit/components/OcAppContent.spec.js
  packages/web-runtime/tests/unit/components/SidebarNav/SidebarNav.spec.js
  packages/web-runtime/tests/unit/components/SidebarNav/SidebarNavItem.spec.js
  packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNav.spec.js.snap
  packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNavItem.spec.js.snap
  packages/web-runtime/tests/unit/components/TopBar.spec.js
  packages/web-runtime/tests/unit/components/__snapshots__/ApplicationsMenu.spec.js.snap
  packages/web-runtime/tests/unit/components/__snapshots__/FeedbackLink.spec.js.snap
  packages/web-runtime/tests/unit/components/__snapshots__/TopBar.spec.js.snap
  tests/acceptance/features/webUIAccount/userProfile.feature
  tests/acceptance/pageObjects/profilePage.js
  tests/acceptance/pageObjects/webPage.js
  tests/acceptance/stepDefinitions/visualContext.js
  tests/e2e/cucumber/step_definitions/app.files.ts
  tests/e2e/support/page/files/allFiles.ts
  yarn.lock
Labels: Status:Needs-Review
