Repository owncloud/web, pull requests merged in 2021-07, with the labels that each got.

#5428 [tests-only] skip cache ocis step if diff contains unit tests only
  .drone.star
  tests/drone/build-ocis.sh
Labels: QA:team

#5308 [unit-tests-only] more tests for collaborator component
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/ShowCollaborator.vue
  packages/web-app-files/tests/unit/components/Collaborators/ShowCollaborator.spec.js
Labels: QA:team

#5282 Unit tests for BatchActions component (part1)
  packages/web-app-files/src/components/AppBar/SelectedResources/BatchActions.vue
  packages/web-app-files/tests/unit/components/BatchActions.spec.js
Labels: QA:team

#5374 [full-ci] Batch actions for accepting and declining shares
  changelog/unreleased/enhancement-share-batch-actions
  packages/web-app-files/src/App.vue
  packages/web-app-files/src/components/AppBar/SelectedResources/BatchActions.vue
  packages/web-app-files/src/helpers/resources.js
  packages/web-app-files/src/helpers/share/triggerShareAction.js
  packages/web-app-files/src/mixins/actions/acceptShare.js
  packages/web-app-files/src/mixins/actions/declineShare.js
  packages/web-app-files/src/mixins/actions/delete.js
  packages/web-app-files/src/mixins/actions/navigate.js
  packages/web-app-files/src/mixins/fileActions.js
  packages/web-app-files/src/mixins/sidebar/destroySideBar.js
  packages/web-app-files/src/mixins/sidebar/mountSideBar.js
  packages/web-app-files/src/store/getters.js
  packages/web-app-files/src/store/mutations.js
  packages/web-app-files/src/store/state.js
  packages/web-app-files/src/views/Favorites.vue
  packages/web-app-files/src/views/Personal.vue
  packages/web-app-files/src/views/PublicFiles.vue
  packages/web-app-files/src/views/SharedViaLink.vue
  packages/web-app-files/src/views/SharedWithMe.vue
  packages/web-app-files/src/views/SharedWithOthers.vue
  packages/web-app-files/src/views/Trashbin.vue
  packages/web-app-files/tests/unit/helpers/share/triggerShareAction.spec.js
  packages/web-app-files/tests/unit/views/SharedWithMe.spec.js
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
  tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/sharedWithMePage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: Status:Needs-Review

#5358 Remove obsolete dependencies
  packages/web-app-draw-io/package.json
  packages/web-app-files/package.json
  packages/web-app-files/src/components/SideBar/Links/FileLinks.vue
  packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkEdit.vue
  packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkInfo.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/AutocompleteItem.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditCollaborator.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/ShowCollaborator.vue
  packages/web-app-files/src/components/SideBar/SideBar.vue
  packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
  packages/web-app-files/src/fileSortFunctions.js
  packages/web-app-files/src/helpers/resources.js
  packages/web-app-files/src/helpers/statusIndicators.js
  packages/web-app-files/src/mixins.js
  packages/web-app-files/src/mixins/collaborators.js
  packages/web-app-files/src/mixins/fileActions.js
  packages/web-app-files/src/quickActions.js
  packages/web-app-files/src/store/actions.js
  packages/web-app-files/src/store/getters.js
  packages/web-app-files/src/store/mutations.js
  packages/web-app-files/src/store/state.js
  packages/web-app-files/src/views/LocationPicker.vue
  packages/web-app-files/src/views/Personal.vue
  packages/web-app-files/tests/unit/mixins/collaborators.spec.js
  packages/web-app-files/tests/unit/store/getters.spec.js
  packages/web-runtime/package.json
  packages/web-runtime/src/App.vue
  packages/web-runtime/src/index.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  yarn.lock
Labels: Topic:Dependencies, Type:Technical-Debt

#5449 [tests-only][full-ci] Removed closed sharing issues form various features
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
  tests/acceptance/features/webUIFilesCopy/copy.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersCollaborator/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersExpire/shareWithUsersExpiringShares.feature
  tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPublicManagement/publicLinkIndicator.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/helpers/sharingHelper.js
Labels: QA:team

#5434 [full-ci][tests-only] Remove @yetToImplement tags from tests (part5)
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIWebdavLockProtection/delete.feature
  tests/acceptance/features/webUIWebdavLockProtection/move.feature
  tests/acceptance/features/webUIWebdavLockProtection/upload.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
  tests/acceptance/helpers/httpHelper.js
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/webPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: QA:team

#5459 [tests-only] Refactored confusing step definition
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/features/webUIUserJourney/journey1.feature
  tests/acceptance/stepDefinitions/generalContext.js
Labels: QA:team

#5469 [full-ci] [tests-only] Split "Basic" pipelines to reduce CI time
  .drone.star
  tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIAdminSettings/adminAppsSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
  tests/acceptance/features/webUIAdminSettings/helpAndTips.feature
Labels: QA:team

#5284 [full-ci] Add details accordion in sharing sidebar
  changelog/3.3.0_2021-06-23/bugfix-unnecessary-webdav-propfind
  changelog/unreleased/enhancement-details-in-sharing-sidebar
  packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
  packages/web-app-files/src/components/SideBar/SideBar.vue
  packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
  packages/web-app-files/src/helpers/resources.js
  packages/web-app-files/src/index.js
  packages/web-app-files/src/store/actions.js
  packages/web-app-files/src/store/getters.js
  packages/web-app-files/src/store/mutations.js
  packages/web-app-files/src/store/state.js
  packages/web-app-files/tests/unit/components/AppBar/AppBar.spec.js
  packages/web-app-files/tests/unit/components/AppBar/SelectedResources/BatchActions.spec.js
  packages/web-app-files/tests/unit/components/AppBar/Upload/FileUpload.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/AutocompleteItem.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ShowCollaborator.spec.js
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFilesActionMenu/fileFolderActionMenu.feature
  tests/acceptance/features/webUIFilesCopy/copy.feature
  tests/acceptance/features/webUIFilesDetails/fileDetails.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/filesRow.js
  tests/acceptance/pageObjects/FilesPageElement/mediaViewerPage.js
  tests/acceptance/pageObjects/markdownEditorPage.js
  tests/acceptance/pageObjects/personalPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/unit/config/jest.init.js
  tests/unit/stubs/index.js
Labels: QA:team

#5478 [Tests-Only] Fix links for issuesin expected failure files
  tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
Labels: QA:team

#5412 [unit-tests-only] move typescript tests to unit folder
  packages/web-pkg/tests/unit/cache/cache.spec.ts
  packages/web-pkg/tests/unit/http/client.spec.ts
  packages/web-pkg/tests/unit/observer/visibility.spec.ts
  packages/web-pkg/tests/unit/utils/encodePath.spec.ts
  packages/web-pkg/tests/unit/utils/objectKeys.spec.ts
Labels: QA:team

#5447 [full-ci][Tests-Only] Fix intermittent failure on user creation
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
  tests/acceptance/helpers/httpHelper.js
  tests/acceptance/helpers/sharingHelper.js
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: QA:team

#5502 [tests-only] [full-ci] Run all acceptance tests on tag event
  .drone.star
Labels: QA:team

#5504 add more badges to readme
  README.md
Labels: Status:Needs-Review

#5423 [full-ci][tests-only] Remove @yetToImplement tags from tests (part4)
  tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFiles/browseDirectlyToDetailsTab.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team

#5505 [tests-only] [full-ci] Bump commit ids for tests
  .drone.env
  tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
Labels: QA:team

#5493 fix: view options position
  changelog/unreleased/bugfix-view-options-position
  packages/web-app-files/src/components/AppBar/AppBar.vue
Labels: Type:Bug

#5463 [tests-only] [full-ci] remove more closed issue tags from features and expected failures
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFilesCopy/copy.feature
  tests/acceptance/features/webUIFilesDetails/fileDetails.feature
  tests/acceptance/features/webUIResharing1/reshareUsers.feature
  tests/acceptance/features/webUIResharing2/reshareUsers.feature
  tests/acceptance/features/webUISharingFilePermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersBlacklisted/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersCollaborator/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkPublicActions.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
  tests/acceptance/features/webUISharingPublicManagement/publicLinkIndicator.feature
  tests/acceptance/features/webUISharingPublicManagement/publicLinkShareByEmail.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
Labels: QA:team

#5492 [unit-tests-only] role of collaborator
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ShowCollaborator.spec.js
Labels: QA:team

#5511 [Tests-Only] Dont crash the test build if dav properties are not found
  tests/acceptance/helpers/webdavHelper.js
Labels: QA:team

#5516 [Tests-Only] Remove unnecessary console.log line in webdavHelper
  tests/acceptance/helpers/webdavHelper.js
Labels: QA:team

#5495 [unit-tests] Added unit tests for ListInfo component
  packages/web-app-files/tests/unit/components/FilesList/ListInfo.spec.js
Labels: QA:team

#5521 [tests-only] [unit-tests] Added unit tests for NotFoundMessage component
  packages/web-app-files/tests/unit/components/FilesList/NotFoundMessage.spec.js
Labels: QA:team

#5517 [unit-tests] Added unit tests for NoContentMessage component
  packages/web-app-files/tests/unit/components/FilesList/NoContentMessage.spec.js
Labels: QA:team

#5510 [Tests-Only]Add UI tests for dot in folder name
  tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
  tests/acceptance/features/webUITrashbinFilesFolders/trashbinFilesFolders.feature
  tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team

#5520 [full-ci] [tests-only]investigate webUISharingInternalUsers/shareWithUsers.feature:78
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
Labels: QA:team

#5522 [unit-tests] unit tests for SizeInfo component
  packages/web-app-files/src/components/AppBar/SelectedResources/SizeInfo.vue
  packages/web-app-files/tests/unit/components/AppBar/SelectedResources/SizeInfo.spec.js
Labels: QA:team

#5527 [full-ci][tests-only] Remove @skip tags from tests
  tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIAccount/logout.feature
  tests/acceptance/features/webUIFilesActionMenu/scrollMenuIntoView.feature
  tests/acceptance/features/webUIFilesSearch/search.feature
  tests/acceptance/features/webUILogin/openidLogin.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/pageObjects/personalPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/loginContext.js
Labels: QA:team

#5178 Enable capability-based avatar img loading
  changelog/unreleased/enhancement-use-profile-picture-capability
  packages/web-app-files/src/store/actions.js
  packages/web-runtime/src/components/Avatar.vue
  tests/vrt/baseline/ocis/topBar.png
Labels: Early-Adopter:CERN, Type:Technical-Debt

#5546 [tests-only] Refactor 'in the webUI' to 'on the webUI'
  tests/acceptance/features/webUIAccount/userProfile.feature
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFiles/options.feature
  tests/acceptance/features/webUIFilesActionMenu/fileFolderActionMenu.feature
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
  tests/acceptance/features/webUIFilesDetails/fileDetails.feature
  tests/acceptance/features/webUIMarkdownEditor/markdownFile.feature
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature
  tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFilePermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRootEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersExpire/shareWithUsersExpiringShares.feature
  tests/acceptance/features/webUISharingInternalUsersExpireToRoot/shareWithUsersExpiringShares.feature
  tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootCollaborator/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingPermissionToRoot/shareFileWithMultipleUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/shareFolderWithMultipleUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFileGroup.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFoldersGroup.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/features/webUISharingPublicManagement/sharingPublicSession.feature
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/loginContext.js
  tests/acceptance/stepDefinitions/markdownEditorContext.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: QA:team

#5519 Unit tests for BatchActions component (part2)
  packages/web-app-files/tests/unit/components/AppBar/SelectedResources/BatchActions.spec.js
Labels: QA:team

#5526 [unit-tests] add unit tests for QuickActions component
  packages/web-app-files/tests/unit/components/FilesList/QuickActions.spec.js
Labels: QA:team

#5552 [unit-tests] unit tests for FileDrop component
  packages/web-app-files/tests/unit/components/AppBar/Upload/FileDrop.spec.js
Labels: QA:team

#5558 [full-ci][tests-only] bump core and ocis commit id
  .drone.env
Labels: QA:team

#5524 [unit-tests] added unit tests for FilesList Pagination component
  packages/web-app-files/tests/unit/components/FilesList/Pagination.spec.js
Labels: QA:team

#5544 [unit-tests] Added unit test for collaborator role definition helper
  packages/web-app-files/tests/unit/helpers/collaboratorRolesDefinition.spec.js
Labels: QA:team

#5563 [tests-only][unit-tests] Move ViewOptions component unit test to respective folder
  packages/web-app-files/tests/unit/components/AppBar/ViewOptions.spec.js
Labels: QA:team

#5559 [tests-only][unit-tests] Add unit tests for FolderUpload component
  packages/web-app-files/tests/unit/components/AppBar/Upload/FolderUpload.spec.js
Labels: QA:team

#5548 [tests-only] change the file content of a received share
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
Labels: QA:team

#5549 [full-ci] Sliding Sidebar
  .drone.star
  changelog/unreleased/enhancement-sidebar-navigation
  packages/web-app-files/src/App.vue
  packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
  packages/web-app-files/src/components/SideBar/FileInfo.vue
  packages/web-app-files/src/components/SideBar/Links/FileLinks.vue
  packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkActions.vue
  packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkEdit.vue
  packages/web-app-files/src/components/SideBar/Shared/RoleItem.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.vue
  packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
  packages/web-app-files/src/components/SideBar/SideBar.vue
  packages/web-app-files/src/helpers/route.js
  packages/web-app-files/src/helpers/statusIndicators.js
  packages/web-app-files/src/index.js
  packages/web-app-files/src/mixins/routes.js
  packages/web-app-files/src/mixins/sidebar/destroySideBar.js
  packages/web-app-files/src/quickActions.js
  packages/web-app-files/src/store/mutations.js
  packages/web-app-files/src/store/state.js
  packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
  packages/web-runtime/package.json
  packages/web-runtime/src/index.js
  tests/acceptance/features/webUIFilesActionMenu/fileFolderActionMenu.feature
  tests/acceptance/features/webUIFilesDetails/fileDetails.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/filesRow.js
  tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/pageObjects/personalPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
  yarn.lock
Labels: Status:Needs-Review, Topic:UX-Design

#5506 add option to define how many share recipients should be shown
  changelog/unreleased/enhancement-share-recipients-number
  docs/getting-started.md
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/NewCollaborator.vue
  packages/web-runtime/src/store/config.js
Labels: Category:Change

#5573 [full-ci] feat: load only opened panels
  changelog/unreleased/enhancement-load-only-opened-panels
  packages/web-app-files/src/components/SideBar/SideBar.vue
Labels: Category:Enhancement

#5574 [tests-only][full-ci]bump core and ocis commit id
  .drone.env
Labels: QA:team

#5554 [full-ci] feat: add invite instead of autocomplete
  changelog/unreleased/enhancement-filestable-dropdown-actions
  changelog/unreleased/enhancement-invite
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/AutocompleteItem.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/NewCollaborator.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/RecipientContainer.vue
  packages/web-runtime/package.json
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  yarn.lock
Labels: Category:Enhancement

#5596 [tests-only] [full-ci] Adjust invalid file and folder name tests
  .drone.env
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
Labels: QA:team
