Repository owncloud/web, pull requests merged in 2021-10, with the labels that each got.

#5647 [full-ci] feat: move custom permissions to a drop
  changelog/unreleased/enhancement-move-custom-permissions-to-drop
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/AdditionalPermissions.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.vue
  packages/web-app-files/src/mixins/collaborators.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/AdditionalPermissions.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.spec.js
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
  tests/acceptance/features/webUISharingInternalUsersCollaborator/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootCollaborator/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/stepDefinitions/sharingContext.js
  yarn.lock
Labels: Category:Enhancement

#5858 Fix theme import
  packages/web-runtime/src/container/bootstrap.ts
  packages/web-runtime/src/index.ts
Labels: Status:Needs-Review, Early-Adopter:CERN

#5876 [tests-only][full-ci]Bump core commit id
  .drone.env
Labels: QA:team

#5842 Add step definition "move rename" to smoke test with playwrigth
  tests/smoke/features/kindergarten.feature
  tests/smoke/features/shareFileJourney.feature
  tests/smoke/features/step_definitions/api.ts
  tests/smoke/features/step_definitions/app.files.ts
  tests/smoke/support/api/http.ts
  tests/smoke/support/api/index.ts
  tests/smoke/support/api/recevedFolder.ts
  tests/smoke/support/cta/files/sidebar.ts
  tests/smoke/support/page/files/allFiles.ts
  tests/smoke/support/page/files/sharedWithMe.ts
Labels: QA:testing

#5877 [tests-only][full-ci] fixes frequently failing unshare test
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
Labels: QA:team

#5693 [unit-tests-only] Add unit tests for List component
  packages/web-app-files/tests/unit/components/Search/List.spec.js
  packages/web-app-files/tests/unit/components/Search/__snapshots__/List.spec.js.snap
Labels: QA:team

#5909 Run CI against latest oC10 release
  .drone.env
  .drone.star
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
  tests/acceptance/helpers/sharingHelper.js
Labels: QA:team
