Repository owncloud/web, pull requests merged in 2021-01, with the labels that each got.

#4540 [Tests-Only] Add webui tests for previews in list view
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team

#4581 [tests-only] Add webui test for checking accepted share from remote user is listed in shared-with-me page
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
Labels: dev:acceptance-tests

#4551 [tests-only] Add webui tests for checking different available options of actions menu
  tests/acceptance/features/webUIFiles/fileDetails.feature
  tests/acceptance/features/webUIFiles/fileFolderActionMenu.feature
  tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team

#4589 [tests-only] Bump OCIS_COMMITID as at 2021-01-06AM
  .drone.env
Labels: QA-team

#4583 [Tests-Only] Add jest and write example unit test
  .drone.star
  .eslintrc.json
  .gitignore
  package.json
  src/components/Top-Bar.vue
  tests/unit/config/jest.config.js
  tests/unit/config/jest.init.js
  tests/unit/config/stubs.js
  tests/unit/specs/TopBar.spec.js
  tests/unit/specs/__snapshots__/TopBar.spec.js.snap
  webpack.common.js
  yarn.lock
Labels: QA

#4588 [Tests-only] Adds webUI tests for deleting and restoring a file inside a received share folder
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.txt
  tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
  tests/acceptance/helpers/webdavHelper.js
Labels: QA-team

#4593 Version bump for release 1.0.1
  changelog/1.0.1_2021-01-08/copy-action-label
  changelog/1.0.1_2021-01-08/disable-previews
  changelog/1.0.1_2021-01-08/fix-burger-menu
  changelog/1.0.1_2021-01-08/oc10-app-controllers
  changelog/1.0.1_2021-01-08/server-url
Labels: 3 - To Review

#4600 [Tests-Only][CI] use OCIS_URL env var to simplify ocis configuration in ci
  .drone.star
Labels: 3 - To Review, Drone

#4602 [tests-only] Update OCIS_COMMITID for tests
  .drone.env
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.txt
Labels: QA-team

#4575 [Tests-Only] Adds webUI tests for sharing file after renaming it
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.txt
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 3 - To Review, QA-team

#4592 [tests-only] Add webui tests for markdown editor
  .drone.star
  tests/acceptance/features/webUIMarkdownEditor/markdownFile.feature
  tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/pageObjects/markdownEditorPage.js
  tests/acceptance/stepDefinitions/markdownEditorContext.js
  tests/acceptance/stepDefinitions/webdavContext.js
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#4613 [Tests-Only] Add webUI tests for performing cancel action while copying and moving a files/folders
  tests/acceptance/features/webUIFiles/copy.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/filesPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA-team

#4612 [tests-only] Convert expected failure text file to markdown
  .drone.star
  tests/acceptance/expected-failures-with-oc10-server.md
  tests/acceptance/expected-failures-with-oc10-server.txt
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.txt
  tests/acceptance/run.sh
Labels: 3 - To Review, QA-team

#4618 [tests-only] Be more specific matching an expected-failure
  tests/acceptance/run.sh
Labels: 4 - To release, QA-team

#4619 [tests-only] Adjust format of expected-failures markdown files
  tests/acceptance/expected-failures-with-oc10-server.md
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
Labels: QA-team

#4574 [POC][Tests-Only] Add first visual regression tests
  .drone.star
  .gitignore
  docs/testing.md
  nightwatch.conf.js
  package.json
  tests/acceptance/features/webUIFiles/fileList.feature
  tests/acceptance/stepDefinitions/visualContext.js
  tests/vrt/baseline/oc10/sideBar.png
  tests/vrt/baseline/oc10/topBar.png
  tests/vrt/baseline/ocis/sideBar.png
  tests/vrt/baseline/ocis/topBar.png
  yarn.lock
Labels: 3 - To Review, QA-team, dev:acceptance-tests, review carefully!

#4617 [Tests-Only] Add tests for valid and invalid file/folder name
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
Labels: 3 - To Review, QA-team

#4622 [docs-only] Bump version for oc10 app
  appinfo/info.xml
  docs/releasing.md
Labels: 3 - To Review

#4621 Fix paths in l10n Makefile
  l10n/Makefile
Labels: 3 - To Review

#4624 [docs-only] Fix docs for oc10 app
  docs/deployments/oc10-app.md
Labels: 3 - To Review

#4626 [tests-only] Adjust regex for SUITE_SCENARIO in acceptance tests
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/run.sh
Labels: QA-team

#4625 share a folder with some resources in it
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
Labels: 3 - To Review, QA-team

#4634 [docs-only] Fix typos in testing.md
  docs/testing.md
Labels: 3 - To Review, QA-team

#4643 [tests-only] change visual regression threshold to 0.002
  nightwatch.conf.js
Labels: 3 - To Review, QA-team

#4645 [tests-only] do not let someone accidentally commit a local .drone.yml
  .gitignore
Labels: QA-team

#4652 [tests-only] remove trashbinDelete bug demo scenario
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
Labels: QA-team

#4663 [Tests-Only]Add media viewer preview tests for different file formats
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
  tests/acceptance/filesForUpload/sampleGif.gif
  tests/acceptance/filesForUpload/sampleOgg.ogg
  tests/acceptance/filesForUpload/sampleWebm.webm
Labels: 2 - Developing, QA-team

#4662 [Tests-Only] Strictly check for the image for media viewer preview
  tests/acceptance/expected-failures-with-oc10-server.md
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: 4 - To release, QA-team

#4671 [tests-only] Follow renaming of konnectd to idp from ocis repo
  .drone.env
  .drone.star
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/drone/config.json
Labels: 3 - To Review
