Repository owncloud/web, pull requests merged in 2021-02, with the labels that each got.

#4670 [Tests-Only]Add tests for media viewer files with upper case file extensions
  tests/acceptance/expected-failures-with-oc10-server.md
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIPreview/imageMediaViewer.feature
  tests/acceptance/stepDefinitions/previewContext.js
Labels: 3 - To Review, QA-team

#4678 [Tests-Only] Change issue number in expected failure file forlogin test
  tests/acceptance/expected-failures-with-oc10-server.md
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
Labels: QA:team, Status:Needs-Review

#4594 Update ODS to 2.1.2
  .drone.star
  apps/draw-io/src/DrawIoEditor.vue
  apps/files/package.json
  apps/files/src/components/Collaborators/Collaborator.vue
  apps/files/src/components/Collaborators/NewCollaborator.vue
  apps/files/src/components/FileDetails.vue
  apps/files/src/components/FileInfoVersions.vue
  apps/files/src/components/PublicLinks/FilesDrop.vue
  apps/files/webpack.common.js
  apps/files/yarn.lock
  changelog/unreleased/update-ods-2.1.2
  package.json
  tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
  webpack.common.js
  yarn.lock
Labels: Status:Needs-Review

#4674 [Tests-Only] add webUI tests for disabling user
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUILogin/adminBlocksUser.feature
  tests/acceptance/pageObjects/loginPage.js
  tests/acceptance/stepDefinitions/provisioningContext.js
Labels: QA:team, Status:Needs-Review

#4687 [tests-only] delete wrong doc comment
  tests/acceptance/helpers/webdavHelper.js
Labels: QA:team

#4681 [Tests-only] Update selenium version
  .drone.star
Labels: QA:team

#4682 [Tests-Only] add webUI tests for user session of a deleted user
  tests/acceptance/expected-failures-with-oc10-server.md
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUILogin/login.feature
Labels: QA:team, Status:Needs-Review

#4669 [Tests-Only] add webUI tests for moving shared file
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
Labels: QA:team, Status:Needs-Review

#4740 Change configuration for tests in CI to use oauth2
  .drone.star
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-openid-login.md
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
  tests/acceptance/features/webUILogin/adminBlocksUser.feature
  tests/acceptance/features/webUILogin/oauthLogin.feature
  tests/acceptance/features/webUILogin/openidLogin.feature
  tests/acceptance/pageObjects/ownCloudLoginPage.js
  tests/acceptance/pageObjects/userDisabledPage.js
  tests/acceptance/stepDefinitions/loginContext.js
  tests/drone/config-oc10-oauth.json
  tests/drone/config-oc10-openid.json
Labels: QA:team, Status:Needs-Review

#4750 Increase version for release 2.0.0
  changelog/2.0.0_2020-02-16/rollup
  changelog/2.0.0_2020-02-16/update-ods-2.1.2
  package.json
  packages/web-integration-oc10/appinfo/info.xml
Labels: Status:Needs-Review

#4748 [tests-only] Bump OCIS_COMMITID
  .drone.env
  tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
Labels: QA:team

#4745 Fix l10n paths
  Makefile
  packages/web-runtime/l10n/Makefile
  packages/web-runtime/package.json
  yarn.lock
Labels: Topic:Translation

#4749 show error message if config could not be parsed
  changelog/unreleased/invalidConfig
  package.json
  packages/web-runtime/src/configHelper.js
  packages/web-runtime/src/index.js
  packages/web-runtime/src/pages/missingOrInvalidConfig.vue
  tests/unit/specs/loadConfig.spec.js
  yarn.lock
Labels: QA:team

#4737 [tests-only] Only count fails on attempt 2
  tests/acceptance/run.sh
Labels: QA:team

#4753 Search for sharees in additional info
  changelog/unreleased/search-in-additional-info
  packages/web-app-files/src/components/Collaborators/NewCollaborator.vue
Labels: Status:Needs-Review

#4754 [tests-only] Bump OCIS commit id
  .drone.env
Labels: QA:team

#4756 [tests-only] fail CI when there is no expected-to-fail file but some tests failed
  tests/acceptance/run.sh
Labels: QA:team

#4757 Fix allowed folders and CSP in oc10 app
  changelog/2.0.1_2021-02-18/fix-php-controller
  package.json
  packages/web-integration-oc10/appinfo/info.xml
  packages/web-integration-oc10/lib/Controller/FilesController.php
Labels: Status:Needs-Review

#4758 Move changelog files to release changelog folder
  changelog/2.0.1_2021-02-18/invalidConfig
  changelog/2.0.1_2021-02-18/search-in-additional-info
Labels: Status:Needs-Review

#4759 Supress redirect error
  changelog/unreleased/surpress-redirect-error
  packages/web-runtime/src/store/user.js
Labels: Topic:Hardening

#4760 [tests-only] Bump OCIS commit id for tests
  .drone.env
Labels: QA:team

#4773 [tests-only] bump ocis commit id
  .drone.env
  tests/vrt/baseline/ocis/topBar.png
Labels: QA:team
