Repository owncloud/web, pull requests merged in 2022-03, with the labels that each got.

#6498 [tests-only] [full-ci] Refactor download.feature to make it more reliable
  tests/acceptance/features/webUIFiles/download.feature
Labels: QA:team

#6499 [tests-only] Refactor accessingPrivateLinks tests
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team

#6474 [tests-only][full-ci] Bump oCIS commit id for the tests
  .drone.env
  packages/web-runtime/src/components/SidebarNav/SidebarNavItem.vue
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUILogin/oauthLogin.feature
  tests/acceptance/features/webUIUserJourney/journey1.feature
  tests/acceptance/nightwatch.conf.js
  tests/acceptance/pageObjects/accountPage.js
  tests/acceptance/pageObjects/favoritesPage.js
  tests/acceptance/pageObjects/filesDropPage.js
  tests/acceptance/pageObjects/loginErrorPage.js
  tests/acceptance/pageObjects/loginPage.js
  tests/acceptance/pageObjects/personalPage.js
  tests/acceptance/pageObjects/publicLinkFilesPage.js
  tests/acceptance/pageObjects/sharedViaLinkPage.js
  tests/acceptance/pageObjects/sharedWithMePage.js
  tests/acceptance/pageObjects/sharedWithOthersPage.js
  tests/acceptance/pageObjects/trashbinPage.js
  tests/acceptance/pageObjects/webPage.js
  tests/e2e/support/page/files/allFiles.ts
  tests/e2e/support/page/files/publicLink.ts
  tests/e2e/support/page/files/sharedWithMe.ts
  tests/e2e/support/page/runtime.ts
Labels: QA:team

#6471 [full-ci] enable capability loading for password protected public links
  changelog/unreleased/bugfix-password-protected-public-link-capabilities
  packages/web-app-files/src/views/PublicFiles.vue
Labels: Early-Adopter:CERN, bug

#6522 [tests-only] add unit tests for the account page and minimize coverage from acceptance tests
  packages/web-runtime/src/pages/account.vue
  packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.js.snap
  packages/web-runtime/tests/unit/pages/account.spec.js
  tests/acceptance/features/webUIAccount/accountInformation.feature
  tests/acceptance/pageObjects/accountPage.js
  tests/acceptance/stepDefinitions/accountContext.js
Labels: QA:team

#6520 [tests-only][full-ci] Suppress NoSuchElementError on isVisible whenever expected not to be visible
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFilesDetails/fileDetails.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
  tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
  tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
  tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
  tests/acceptance/pageObjects/personalPage.js
  tests/acceptance/pageObjects/webPage.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: QA:team

#6564 [full-ci] [tests-only] Bump ocis commit id
  .drone.env
Labels: QA:team

#6568 Fix TypeErrors when trying to destruct undefined properties
  changelog/unreleased/bugfix-space-permission-destructing
  packages/web-app-files/src/helpers/resources.js
Labels: Type:Bug

#6572 Fix share panel loading for resources within a shared folder
  changelog/unreleased/enhancement-spaces-people-sharing
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
Labels: Type:Bug

#6569 Fix resize observer errors within subfolders of a space
  changelog/unreleased/bugfix-resize-observer-errors
  packages/web-app-files/src/views/spaces/Project.vue
Labels: Type:Bug

#6461 [tests-only] Add e2e test for unauthorized user opening public link
  tests/e2e/cucumber/publicLinkToFolderJourney.feature
  tests/e2e/cucumber/step_definitions/app.files.ts
  tests/e2e/support/cta/files/index.ts
  tests/e2e/support/cta/files/misc.ts
  tests/e2e/support/cta/files/publicLink.ts
  tests/e2e/support/page/files/publicLink.ts
  tests/e2e/support/page/publicLinkPage.ts
Labels: QA:team

#6592 Fix SET_QUOTA call in the loader for the personal files list
  packages/web-app-files/src/services/folder/loaderPersonal.ts
Labels: Type:Bug

#6606 [full-ci][tests-only]Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#6565 [full-ci] Update drone starlark
  .drone.star
  tests/acceptance/cancelBuilds.sh
Labels: QA:team

#6554 Show space members in the share panel for regular files inside a space
  __fixtures__/users.js
  changelog/unreleased/enhancement-space-members-regular-sidebar
  packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
  packages/web-app-files/src/helpers/space/index.ts
  packages/web-app-files/src/helpers/space/sortMembers.ts
  packages/web-app-files/src/store/actions.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.js.snap
Labels: Status:Needs-Review

#6613 Implement the share inheritance indicators
  changelog/unreleased/enhancement-share-inheritance-indicators
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
  packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ListItem.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.js.snap
  packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.js.snap
Labels: Status:Needs-Review

#6632 Fix natural sort order
  changelog/unreleased/bugfix-sort-order
  packages/web-app-files/src/composables/sort/useSort.ts
  packages/web-app-files/tests/unit/composables/sort/useSort.spec.ts
Labels: Status:Needs-Review

#6646 [full-ci] [tests-only] Bump ocis commit id
  .drone.env
Labels: QA:team

#6618 [full-ci] Multiple fixes
  changelog/unreleased/enhancement-editor-role
  changelog/unreleased/enhancement-optional-ui-elements
  packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkEdit.vue
  packages/web-app-files/src/components/SideBar/Shares/InviteCollaborator/InviteCollaboratorForm.vue
  packages/web-app-files/src/components/SideBar/Shares/RoleDropdown.vue
  packages/web-app-files/src/helpers/resources.js
  packages/web-app-files/src/helpers/share/role.ts
  packages/web-app-files/src/mixins/actions/delete.js
  packages/web-app-files/src/mixins/actions/emptyTrashBin.js
  packages/web-app-files/src/mixins/actions/rename.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/RoleDropdown.spec.js
  packages/web-app-files/tests/unit/helpers/share/role.spec.ts
  packages/web-app-files/tests/unit/mixins/actions/delete.spec.js
Labels: Early-Adopter:CERN

#6656 Use oC10 navigation entry names
  changelog/unreleased/bugfix-oc10-navigation-entry-names
  packages/web-integration-oc10/lib/Controller/ConfigController.php
Labels: Type:Bug, Status:Needs-Review

#6666 [full-ci] [tests-only] Bump ocis commit id
  .drone.env
Labels: QA:team

#6608 [tests-only][full-ci] Flaky private link acceptance tests
  tests/acceptance/customCommands/isAnyElementVisible.js
  tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
Labels: QA:team

#6595 [full-ci][tests-only] Fix waitForFileVisible function
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
Labels: QA:team

#6642 Adjust the topbar layout on the spaces overview
  changelog/unreleased/enhancement-spaces-overview-topbar
  packages/web-app-files/src/components/AppBar/AppBar.vue
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/src/components/AppBar/CreateSpace.vue
  packages/web-app-files/src/components/AppBar/ViewOptions.vue
  packages/web-app-files/src/router/spaces.ts
  packages/web-app-files/src/views/spaces/Projects.vue
  packages/web-app-files/tests/unit/components/AppBar/CreateSpace.spec.js
  packages/web-app-files/tests/unit/views/spaces/Projects.spec.js
  packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap
Labels: Topic:UX-Design

#6684 [tests-only] [full-ci] Bump OCIS_COMMITID
  .drone.env
Labels: QA:team
