Repository owncloud/web, pull requests merged in 2022-06, with the labels that each got.

#7065 [tests-only][full-ci]Test with middleware for web tests related to `dav.propfind.depth_infinity`
  .drone.star
  tests/drone/setup-server-and-app.sh
Labels: QA:team

#7083 [tests-only][full-ci] fixed expiration date related intermittent failure
  tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
Labels: QA:team

#6762 Style fixes for menus
  changelog/unreleased/enhancement-consistend-dropdows
  changelog/unreleased/enhancement-update-ods
  packages/web-app-files/src/components/ActionMenuItem.vue
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/src/components/AppBar/Upload/ResourceUpload.vue
  packages/web-app-files/src/components/ContextActionMenu.vue
  packages/web-app-files/tests/unit/components/AppBar/Upload/__snapshots__/ResourceUpload.spec.js.snap
  packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ContextActions.spec.js.snap
  packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceContextActions.spec.js.snap
  packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap
  packages/web-runtime/package.json
  yarn.lock
Labels: Early-Adopter:CERN

#7085 [full-ci][tests-only] Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#7067 [full-ci] Upload progress & overlay improvements
  changelog/unreleased/enhancement-upload-improvements
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/src/composables/upload/useUploadHelpers.ts
  packages/web-app-files/src/views/FilesDrop.vue
  packages/web-runtime/package.json
  packages/web-runtime/src/components/UploadInfo.vue
  packages/web-runtime/src/composables/upload/useUpload.ts
  packages/web-runtime/src/services/uppyService.ts
  packages/web-runtime/tests/unit/components/UploadInfo.spec.js
  packages/web-runtime/tests/unit/components/__snapshots__/UploadInfo.spec.js.snap
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
  tests/acceptance/pageObjects/filesDropPage.js
  tests/e2e/support/objects/app-files/page/public.ts
  yarn.lock
Labels: Status:Needs-Review

#7088 Upload progress estimation
  changelog/unreleased/enhancement-upload-time-estimation
  packages/web-runtime/src/components/UploadInfo.vue
  packages/web-runtime/src/services/uppyService.ts
  packages/web-runtime/tests/unit/components/UploadInfo.spec.js
Labels: Status:Needs-Review

#7100 Fix complete-state of the upload overlay
  changelog/unreleased/bugfix-upload-overlay-complete-state
  packages/web-runtime/src/components/UploadInfo.vue
Labels: Status:Needs-Review

#7104 Fix parent folder name in the upload overlay on public pages
  changelog/unreleased/bugfix-upload-overlay-public-parent-folder
  packages/web-runtime/src/components/UploadInfo.vue
Labels: Status:Needs-Review

#7115 [full-ci] [tests-only] Changed golang version 1.17 to 1.18
  .drone.star
Labels: QA:team

#7095 [full-ci][tests-only] Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#7111 Use 'uploadDataDuringCreation' option when uploading via tus
  changelog/unreleased/bugfix-upload-meta-serialization
  changelog/unreleased/enhancement-upload-data-during-creation
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/src/composables/upload/useUploadHelpers.ts
  packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.js
  packages/web-pkg/src/composables/capability/useCapability.ts
  packages/web-runtime/src/components/UploadInfo.vue
  packages/web-runtime/src/composables/upload/useUpload.ts
  packages/web-runtime/src/services/uppyService.ts
Labels: Status:Needs-Review

#7127 Upload (performance) improvements round 2
  changelog/unreleased/enhancement-upload-improvements
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/src/composables/upload/useUploadHelpers.ts
  packages/web-app-files/tests/unit/composables/upload/useUploadHelpers.spec.ts
  packages/web-runtime/src/components/UploadInfo.vue
  packages/web-runtime/src/composables/upload/useUpload.ts
  packages/web-runtime/src/services/uppyService.ts
  packages/web-runtime/tests/unit/components/UploadInfo.spec.js
Labels: Status:Needs-Review

#7144 [tests-only][full-ci] Wait for upload success message
  tests/acceptance/pageObjects/personalPage.js
Labels: QA:team

#7155 [tests-only][full-ci] Bump ocis commit id for the tests
  .drone.env
Labels: QA:team

#7118 [tests-only] Add e2e tests for participant management(spaces)
  tests/e2e/cucumber/environment/index.ts
  tests/e2e/cucumber/features/integrations/spaces/participantManagement.ocis.feature
  tests/e2e/cucumber/steps/app-files/page/public.ts
  tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts
  tests/e2e/cucumber/steps/app-files/resource.ts
  tests/e2e/support/objects/app-files/page/public.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
  tests/e2e/support/objects/app-files/share/actions.ts
  tests/e2e/support/objects/app-files/spaces/actions.ts
  tests/e2e/support/objects/app-files/spaces/index.ts
Labels: QA:team

#7173 Continue external apps fix
  changelog/unreleased/bugfix-external-app-title
  changelog/unreleased/bugfix-external-apps
  packages/web-app-external/src/App.vue
  packages/web-app-external/tests/unit/app.spec.js
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-pkg/src/composables/appDefaults/useAppDefaults.ts
  packages/web-pkg/src/composables/appDefaults/useAppDocumentTitle.ts
  packages/web-pkg/src/composables/appDefaults/useAppNavigation.ts
Labels: Early-Adopter:CERN

#7112 E2e test. set space image
  tests/e2e/cucumber/features/integrations/spaces/project.ocis.feature
  tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts
  tests/e2e/support/objects/app-files/spaces/actions.ts
  tests/e2e/support/objects/app-files/spaces/index.ts
Labels: Status:Needs-Review

#7188 Improve performance of share indicators
  changelog/unreleased/enhancement-share-indicators-performance
  packages/web-app-files/src/services/folder/legacy/loaderPersonal.ts
  packages/web-app-files/src/services/folder/spaces/loaderPersonal.ts
  packages/web-app-files/src/services/folder/spaces/loaderProject.ts
  packages/web-app-files/src/store/actions.js
  packages/web-app-files/src/store/mutations.js
  packages/web-app-files/tests/unit/views/spaces/Project.spec.js
Labels: Status:Needs-Review, Topic:Performance
