Repository owncloud/web, pull requests merged in 2022-01, with the labels that each got.

#6179 [unit-tests] make use of mocked router rather using vue router
  packages/web-app-files/tests/unit/views/Personal.spec.js
  packages/web-app-files/tests/unit/views/PublicFiles.spec.ts
  packages/web-app-files/tests/unit/views/views.setup.js
  packages/web-app-files/tests/unit/views/views.shared.ts
Labels: QA:team

#6211 [tests-only] Change smoke test to e2e test in .drone.star
  .drone.star
Labels: QA:team

#6210 [tests-only][full-ci]Remove and refactor tests present in middleware in publicLink context
  tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
  tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/features/webUISharingPublicManagement/sharingPublicSession.feature
  tests/acceptance/stepDefinitions/middlewareContext.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
Labels: QA:team

#6204 [full-ci] enable lazy table cells and fix tests
  changelog/unreleased/enhancement-lazy-resource-table
  dev/docker/oc10.web.config.json
  dev/docker/ocis.web.config.json
  packages/web-app-files/src/components/FilesList/ResourceTable.vue
  packages/web-app-files/tests/integration/specs/pagination.spec.js
  packages/web-app-files/tests/unit/components/FilesList/ResourceTable.spec.js
  packages/web-app-files/tests/unit/views/views.setup.js
  packages/web-runtime/src/store/config.js
  rollup.config.js
  tests/drone/config-oc10-integration-app-oauth.json
  tests/drone/config-oc10-oauth.json
  tests/drone/config-oc10-openid.json
  tests/drone/config-ocis.json
  tests/unit/config/jest.config.js
Labels: Status:Needs-Review

#6105 [full-ci] [tests-only]Adds tests related to batch action menu
  tests/acceptance/features/webUIFiles/batchAction.feature
  tests/acceptance/pageObjects/appBarActions.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team

#6235 [tests-only][not-for-merge] test middleware v1.0.0
  .drone.star
Labels: QA:team

#6237 [tests-only] [full-ci] allow only one space before "in the server"
  tests/acceptance/features/webUIFiles/batchAction.feature
  tests/acceptance/stepDefinitions/middlewareContext.js
Labels: QA:team

#6216 [full-ci][tests-only] bump middleware version to v1.1.0
  .drone.star
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
  tests/acceptance/stepDefinitions/generalContext.js
  tests/e2e/config.js
  tests/e2e/cucumber/kindergarten.feature
  tests/e2e/cucumber/step_definitions/middlewareContext.ts
  tests/e2e/support/store/user.ts
Labels: QA:team

#6245 [tests-only][full-ci]Refactor config.js to make use of middleware's functions
  tests/acceptance/helpers/config.js
Labels: QA:team

#6236 [tests-only][full-ci]Refactor files related to renaming and locking to match the steps of middleware
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIWebdavLockProtection/delete.feature
  tests/acceptance/features/webUIWebdavLockProtection/move.feature
  tests/acceptance/features/webUIWebdavLockProtection/upload.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team

#6262 Add default sorting to the spaces list
  changelog/unreleased/enhancement-spaces-default-sorting
  packages/web-app-files/src/views/spaces/Projects.vue
Labels: Category:Enhancement

#6244 [tests-only][full-ci] Fix screenshots
  .drone.star
  tests/acceptance/nightwatch.conf.js
  tests/acceptance/setup.js
  tests/acceptance/stepDefinitions/generalContext.js
Labels: QA:team

#6267 [tests-only][full-ci] Fix webUIPrivateLinks/accessingPrivateLinks.feature:17 test
  tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
Labels: QA:team

#6234 [tests-only][full-ci] Remove the tests already present in middleware from webdavContext
  tests/acceptance/features/webUICreateFilesFolders/createFolderEdgeCases.feature
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
  tests/acceptance/features/webUIFiles/batchAction.feature
  tests/acceptance/features/webUIFiles/download.feature
  tests/acceptance/features/webUIFilesCopy/copy.feature
  tests/acceptance/features/webUIFilesDetails/fileDetails.feature
  tests/acceptance/features/webUIFilesSearch/search.feature
  tests/acceptance/features/webUIMarkdownEditor/markdownFile.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/features/webUIResharing1/reshareUsers.feature
  tests/acceptance/features/webUIResharingToRoot/reshareUsers.feature
  tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
  tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFilePermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingPermissionToRoot/shareFileWithMultipleUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/shareFolderWithMultipleUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFileGroup.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFoldersGroup.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkPublicActions.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/features/webUITrashbinFilesFolders/trashbinFilesFolders.feature
  tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/stepDefinitions/webdavContext.js
Labels: QA:team

#6156 Move common app logic to useAppDefaults composable
  packages/web-app-draw-io/src/App.vue
  packages/web-app-draw-io/src/index.js
  packages/web-app-files/src/composables/usePagination/index.ts
  packages/web-app-files/src/composables/useSort/index.ts
  packages/web-app-files/src/composables/utils/index.ts
  packages/web-app-files/src/helpers/download/downloadAsArchive.ts
  packages/web-app-files/src/helpers/resource/index.ts
  packages/web-app-files/src/helpers/resource/privatePreviewBlob.ts
  packages/web-app-files/src/helpers/resource/publicPreviewUrl.ts
  packages/web-app-files/src/helpers/resource/resource.ts
  packages/web-app-files/src/helpers/user/avatarUrl.ts
  packages/web-app-files/src/mixins/fileActions.js
  packages/web-app-files/src/search/sdk/list.ts
  packages/web-app-files/src/search/sdk/preview.ts
  packages/web-app-files/src/services/index.ts
  packages/web-app-files/tests/unit/helpers/resource/sameResource.spec.ts
  packages/web-app-files/tests/unit/search/sdk.spec.ts
  packages/web-app-media-viewer/src/App.vue
  packages/web-pkg/src/composables/useAppDefaults/index.ts
  packages/web-pkg/src/composables/useAppDefaults/types.ts
  packages/web-pkg/src/composables/useAppDefaults/useAppConfig.ts
  packages/web-pkg/src/composables/useAppDefaults/useAppFileHandling.ts
  packages/web-pkg/src/composables/useAppDefaults/useAppFolderHandling.ts
  packages/web-pkg/src/composables/useAppDefaults/useAppNavigation.ts
  packages/web-pkg/src/services/client.ts
  packages/web-pkg/src/services/index.ts
  packages/web-pkg/src/utils/index.ts
  packages/web-pkg/src/utils/types.ts
  packages/web-pkg/tests/unit/services/client.spec.ts
  packages/web-runtime/src/plugins/web.js
Labels: Early-Adopter:CERN

#6125 Drawio improvements
  changelog/unreleased/enhancement-drawio
  packages/web-app-draw-io/src/App.vue
Labels: Early-Adopter:CERN

#6174 [unit-tests-only] Added unit tests for trashbin view
  packages/web-app-files/tests/unit/views/Trashbin.spec.js
  packages/web-app-files/tests/unit/views/__snapshots__/Trashbin.spec.js.snap
  packages/web-app-files/tests/unit/views/views.setup.js
Labels: QA:team

#6303 [tests-only][full-ci] Retry download if the resource is locked
  tests/acceptance/helpers/webdavHelper.js
Labels: QA:team

#6306 [tests-only][full-ci]Remove function present in middleware from sharingHelper
  tests/acceptance/helpers/sharingHelper.js
Labels: QA:team

#6307 [tests-only][full-ci]Remove function present in middleware from webDavHelper
  tests/acceptance/helpers/webdavHelper.js
Labels: QA:team

#6302 [tests-only][full-ci] Fix version download acceptance test
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
  tests/acceptance/pageObjects/webPage.js
  tests/acceptance/stepDefinitions/generalContext.js
Labels: QA:team

#6308 [tests-only][full-ci] Bump middleware image from 1.2.0 to 1.2.1
  .drone.star
Labels: QA:team

#6257 [tests-only][full-ci]Bump the commit id for tests
  .drone.env
  .drone.star
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/stepDefinitions/previewContext.js
Labels: QA:team

#6315 [full-ci][tests-only] bumped middleware version to v1.3.0
  .drone.star
Labels: QA:team

#6314 Context route auth redirect
  changelog/unreleased/enhancement-context-route-auth-redirect
  packages/web-app-external/src/components/LoadingScreen.vue
  packages/web-app-external/src/index.js
  packages/web-app-files/src/mixins/fileActions.js
  packages/web-runtime/src/router/index.js
Labels: Early-Adopter:CERN

#6319 [tests-only] [full-ci] Adjust test to avoid issue 6305
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
Labels: QA:team

#6320 Up performance simpler
  packages/web-app-files/src/views/Personal.vue
  packages/web-container/index.html.ejs
  rollup.config.js
Labels: Early-Adopter:CERN

#6254 Implement space actions
  changelog/unreleased/enhancement-add-spaces-actions
  packages/web-app-files/src/mixins/spaces/actions/delete.js
  packages/web-app-files/src/mixins/spaces/actions/rename.js
  packages/web-app-files/src/views/spaces/Projects.vue
  packages/web-app-files/tests/unit/mixins/spaces/delete.spec.js
  packages/web-app-files/tests/unit/mixins/spaces/rename.spec.js
  packages/web-app-files/tests/unit/views/spaces/Projects.spec.js
  packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap
  packages/web-client/src/index.ts
Labels: Status:Needs-Review

#6181 [unit-tests] added more unit tests for PublicFiles view
  packages/web-app-files/src/views/PublicFiles.vue
  packages/web-app-files/tests/unit/views/PublicFiles.spec.ts
  packages/web-app-files/tests/unit/views/__snapshots__/PublicFiles.spec.ts.snap
Labels: QA:team

#6175 [unit-tests-only] Added unit tests for shared with others view
  packages/web-app-files/tests/unit/views/SharedWithOthers.spec.js
  packages/web-app-files/tests/unit/views/__snapshots__/SharedWithOthers.spec.js.snap
Labels: QA:team

#5697 [unit-tests] added unit tests for LocationPicker view
  packages/web-app-files/src/views/LocationPicker.vue
  packages/web-app-files/tests/unit/views/LocationPicker.spec.js
  packages/web-app-files/tests/unit/views/__snapshots__/LocationPicker.spec.js.snap
  packages/web-app-files/tests/unit/views/views.setup.js
Labels: QA:team

#6281 [full-ci][tests-only] run acceptance tests using files for upload from the middleware
  .drone.star
  docker-compose.yml
  docs/testing-manual.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
  tests/acceptance/features/webUIUserJourney/journey1.feature
  tests/acceptance/nightwatch.conf.js
  tests/acceptance/stepDefinitions/filesContext.js
  tests/acceptance/stepDefinitions/generalContext.js
  tests/e2e/config.js
  tests/e2e/filesForUpload/'single'quotes.txt
  tests/e2e/filesForUpload/FOLDER/.gitkeep
  tests/e2e/filesForUpload/Folder,With,Comma/sunday,monday.txt
  tests/e2e/filesForUpload/PARENT/CHILD/child.txt
  tests/e2e/filesForUpload/PARENT/parent.txt
  tests/e2e/filesForUpload/data.tar.gz
  tests/e2e/filesForUpload/data.zip
  tests/e2e/filesForUpload/davtest.txt
  tests/e2e/filesForUpload/file,with,comma,.txt
  tests/e2e/filesForUpload/file_to_overwrite.txt
  tests/e2e/filesForUpload/lorem-big.txt
  tests/e2e/filesForUpload/lorem.txt
  tests/e2e/filesForUpload/new-'single'quotes.txt
  tests/e2e/filesForUpload/new-data.tar.gz
  tests/e2e/filesForUpload/new-data.zip
  tests/e2e/filesForUpload/new-lorem-big.txt
  tests/e2e/filesForUpload/new-lorem.txt
  tests/e2e/filesForUpload/new-strängé filename (duplicate #2 &).txt
  tests/e2e/filesForUpload/sampleGif.gif
  tests/e2e/filesForUpload/sampleOgg.ogg
  tests/e2e/filesForUpload/sampleWebm.webm
  tests/e2e/filesForUpload/simple.odt
  tests/e2e/filesForUpload/simple.pdf
  tests/e2e/filesForUpload/strängé filename (duplicate #2 &).txt
  tests/e2e/filesForUpload/test_video.mp4
  tests/e2e/filesForUpload/test_video0.mp4
  tests/e2e/filesForUpload/test_video1.mp4
  tests/e2e/filesForUpload/testavatar.jpeg
  tests/e2e/filesForUpload/testavatar.jpg
  tests/e2e/filesForUpload/testavatar.png
  tests/e2e/filesForUpload/testimage.mp3
  tests/e2e/filesForUpload/textfile.txt
  tests/e2e/filesForUpload/zzzz-must-be-last-file-in-folder.txt
  tests/e2e/filesForUpload/zzzz-zzzz-will-be-at-the-end-of-the-folder-when-uploaded.txt
Labels: QA:team

#6334 [tests-only] Refactor local file involving steps
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
  tests/acceptance/features/webUIUserJourney/journey1.feature
  tests/acceptance/stepDefinitions/middlewareContext.js
Labels: QA:team
