Repository owncloud/web, pull requests merged in 2022-07, with the labels that each got.

#7086 [full-ci] Resharing for ocis
  .drone.env
  .drone.star
  changelog/unreleased/enhancement-ocis-resharing
  docker-compose.yml
  packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
  packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
  packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
  packages/web-app-files/src/components/SideBar/Shares/SharesPanel.vue
  packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
  packages/web-app-files/src/helpers/share/role.ts
  packages/web-app-files/src/helpers/statusIndicators.js
  packages/web-app-files/src/services/folder/legacy/loaderPersonal.ts
  packages/web-app-files/src/services/folder/spaces/loaderPersonal.ts
  packages/web-app-files/src/services/folder/spaces/loaderProject.ts
  packages/web-app-files/src/services/folder/spaces/loaderShare.ts
  packages/web-app-files/src/store/actions.js
  packages/web-app-files/src/store/mutations.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/RoleDropdown.spec.js.snap
  packages/web-app-files/tests/unit/components/SideBar/Shares/FileLinks.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/SharesPanel.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.js.snap
  packages/web-app-files/tests/unit/store/actions.spec.js
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
  tests/acceptance/stepDefinitions/debugContext.js
  tests/e2e/cucumber/steps/app-files/resource.ts
  tests/e2e/support/api/graph/user.ts
  tests/e2e/support/environment/actor/shared.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
Labels: Category:Enhancement

#7209 [full-ci] [tests-only] Using `plugins/s3-cache:1` instead of `meltwater/drone-cache:v1`
  .drone.star
Labels: QA:team

#7243 fix quicklink action storageid retrieval
  changelog/unreleased/enhancement-ocis-resharing
  packages/web-app-files/src/mixins/actions/createQuicklink.js
Labels: Type:Bug

#7231 [full-ci] [tests-only] Used `filename` properties for unique cache name
  .drone.star
Labels: QA:team

#7246 [tests-only][full-ci]Skip test on OCIS related to sharing
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIResharing1/reshareUsers.feature
  tests/acceptance/features/webUIResharing2/reshareUsers.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
Labels: QA:team

#7275 [tests-only] Updated expected to failure as the tests is passing on OCIS
  .drone.env
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
Labels: QA:team

#7279 [tests-only][full-ci] Check share permissions in the webUI after changing
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
Labels: QA:team

#7281 [tests-only] skip the scenario related to ocis issue 2249 with ocis backend
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
Labels: QA:team

#7282 [tests-only][full-ci]Skip tests related to issue-ocis-1310 on ocis
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
Labels: QA:team

#7278 [full-ci] [tests-only] Refactored promise on edit description of space
  tests/e2e/support/objects/app-files/spaces/actions.ts
Labels: QA:team

#7277 [full-ci] [tests-only] Refactored promise on deleting resource
  tests/e2e/support/objects/app-files/resource/actions.ts
Labels: QA:team

#7290 [tests-only][full-ci] Fix expiration date picker element selector
  tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
  tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
Labels: QA:team

#7300 [tests-only][full-ci]Bump OCIS commit id for tests
  .drone.env
Labels: QA:team

#7312 Improve table lazy loading performance
  changelog/unreleased/bugfix-remove-lazy-table-loading-delay
  changelog/unreleased/bugfix-table-lazy-loading-performance
  changelog/unreleased/enhancement-update-ods
  packages/web-app-files/src/components/FilesList/ResourceTable.vue
  packages/web-runtime/package.json
  yarn.lock
Labels: Topic:Performance
