Repository owncloud/web, pull requests merged in 2022-05, with the labels that each got.

#6694 Reset store on logout
  changelog/unreleased/bugfix-resetting-store-on-logout
  packages/web-runtime/src/store/navigation.js
  packages/web-runtime/src/store/user.js
Labels: Early-Adopter:CERN

#6853 Use our EventBus for upload related actions
  changelog/unreleased/enhancement-uppy-service-event-bus
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/src/views/FilesDrop.vue
  packages/web-app-files/tests/unit/views/FilesDrop.spec.js
  packages/web-runtime/src/components/UploadInfo.vue
  packages/web-runtime/src/composables/upload/uppyPlugins/customDropTarget.ts
  packages/web-runtime/src/services/uppyService.ts
Labels: Status:Needs-Review

#6846 Fix root folder links in the upload overlay
  changelog/unreleased/bugfix-upload-overlay-links
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/src/views/FilesDrop.vue
  packages/web-runtime/src/components/UploadInfo.vue
Labels: Status:Needs-Review

#6825 [full-ci] Remove the upload progress bar and its related states
  changelog/unreleased/enhancement-remove-upload-progress-component
  packages/web-app-files/src/App.vue
  packages/web-app-files/src/components/Upload/DetailsWidget.vue
  packages/web-app-files/src/components/Upload/ProgressBar.vue
  packages/web-app-files/src/composables/fileListHeaderPosition/useFileListHeaderPosition.ts
  packages/web-app-files/src/store/getters.js
  packages/web-app-files/src/store/state.js
  packages/web-app-files/src/views/Personal.vue
  packages/web-app-files/src/views/PublicFiles.vue
  packages/web-app-files/src/views/spaces/Project.vue
  packages/web-app-files/tests/unit/components/Search/List.spec.js
  packages/web-app-files/tests/unit/components/Upload/DetailsWidget.spec.js
  packages/web-app-files/tests/unit/components/Upload/ProgressBar.spec.js
  packages/web-app-files/tests/unit/components/Upload/__snapshots__/ProgressBar.spec.js.snap
  packages/web-app-files/tests/unit/components/components.setup.js
  packages/web-app-files/tests/unit/composables/fileListHeaderPosition/spec/index.ts
  packages/web-app-files/tests/unit/composables/fileListHeaderPosition/useFileListHeaderPosition.spec.ts
  packages/web-app-files/tests/unit/views/Personal.spec.js
  packages/web-app-files/tests/unit/views/spaces/Project.spec.js
  packages/web-app-files/tests/unit/views/spaces/__snapshots__/Project.spec.js.snap
  packages/web-app-files/tests/unit/views/views.setup.js
  packages/web-app-files/tests/unit/views/views.shared.ts
  packages/web-runtime/src/container/bootstrap.ts
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
  tests/acceptance/pageObjects/personalPage.js
Labels: QA:team, QA:p2

#6869 [full-ci][tests-only]Refactor test related to public link edit
  tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
  tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
Labels: QA:team

#6876 [tests-only] [full-ci] Bump OCIS_COMMITID
  .drone.env
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
Labels: QA:team

#6871 [tests-only] Add unit tests for the uppy implementation
  packages/web-app-files/tests/unit/composables/upload/spec/index.ts
  packages/web-app-files/tests/unit/composables/upload/useUploadHelpers.spec.ts
  packages/web-runtime/src/composables/upload/useUpload.ts
  packages/web-runtime/tests/unit/components/UploadInfo.spec.js
  packages/web-runtime/tests/unit/components/__snapshots__/UploadInfo.spec.js.snap
  packages/web-runtime/tests/unit/composables/upload/spec/index.ts
  packages/web-runtime/tests/unit/composables/upload/useUpload.spec.ts
Labels: Status:Needs-Review

#6862 cleanup FileLinks component unit test run warnings
  packages/web-app-files/src/components/SideBar/Shares/Links/CreateForm.vue
  packages/web-app-files/tests/unit/components/SideBar/Shares/FileLinks.spec.js
Labels: QA:team

#6879 Install make library
  dev/docker/oc10.Dockerfile
Labels: QA:team

#6557 [tests-only] Adds e2e test for changing public link role
  tests/e2e/cucumber/features/integrations/link.feature
  tests/e2e/cucumber/features/integrations/link.ocis.feature
  tests/e2e/cucumber/steps/app-files/link.ts
  tests/e2e/cucumber/steps/app-files/resource.ts
  tests/e2e/support/objects/app-files/link/actions.ts
  tests/e2e/support/objects/app-files/link/index.ts
Labels: QA:team

#6890 Enable tus upload for password protected public links
  .drone.env
  changelog/unreleased/enhancement-tus-uploads-on-public-pages
  packages/web-runtime/src/composables/upload/useUpload.ts
Labels: Status:Needs-Review

#6898 Fix several issues when setting image and readme for spaces
  changelog/unreleased/bugfix-set-space-image-and-readme
  packages/web-app-files/src/mixins/spaces/actions/setImage.js
  packages/web-app-files/src/mixins/spaces/actions/setReadme.js
  packages/web-app-files/src/services/folder/spaces/loaderProject.ts
  packages/web-app-files/src/store/getters.js
  packages/web-app-files/src/store/mutations.js
  packages/web-app-files/src/views/spaces/Project.vue
  packages/web-app-files/tests/unit/mixins/spaces/setImage.spec.js
  packages/web-app-files/tests/unit/mixins/spaces/setReadme.spec.js
  packages/web-app-files/tests/unit/views/spaces/Project.spec.js
Labels: Status:Needs-Review

#6906 [tests-only][full-ci]Refactor tests related to public link
  tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
  tests/acceptance/stepDefinitions/publicLinkContext.js
Labels: QA:team

#6927 [tests-only] unskip tests to batch delete files from trashbin
  tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
Labels: QA:team

#6951 Remove federated sharing hint if federation is disabled
  changelog/unreleased/bugfix-share-hint-with-disabled-federation
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.spec.js
Labels: Status:Needs-Review

#6957 Remove invalid commas at the end of the config dist files
  config/config.json.dist
  config/config.json.sample-oc10
  config/config.json.sample-ocis
Labels: Type:Technical-Debt

#6923 fix account-info quota rendering
  __fixtures__/users.js
  changelog/unreleased/bugfix-respect-unlimited-quota
  packages/web-runtime/src/components/Topbar/UserMenu.vue
  packages/web-runtime/src/store/user.js
  packages/web-runtime/tests/unit/components/Topbar/UserMenu.spec.js
  packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.js.snap
Labels: Type:Bug

#6759 Sentry as option
  changelog/unreleased/enhancement-add-sentry-support
  docs/getting-started.md
  packages/web-runtime/package.json
  packages/web-runtime/src/container/bootstrap.ts
  packages/web-runtime/src/index.ts
  packages/web-runtime/src/store/user.js
  yarn.lock
Labels: Early-Adopter:CERN

#6982 [tests-only][full-ci] Use webUI steps after the server setup steps
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
Labels: QA:team

#6954 Multiple fixes
  changelog/unreleased/bugfix-text-color-application-menu-item
  changelog/unreleased/enhancement-sort-default-action-first-context-menu
  packages/web-app-files/src/components/FilesList/ContextActions.vue
  packages/web-app-text-editor/src/App.vue
  packages/web-pkg/src/components/sidebar/SideBar.vue
  packages/web-runtime/src/components/Topbar/ApplicationsMenu.vue
Labels: Early-Adopter:CERN

#6915 [tests-only] Refactored e2e test to move selector name to constant [Part 1]
  tests/e2e/support/objects/app-files/page/public.ts
  tests/e2e/support/objects/app-files/page/shares/withMe.ts
  tests/e2e/support/objects/app-files/page/spaces/personal.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/utils.ts
  tests/e2e/support/objects/app-files/share/actions.ts
Labels: QA:team

#6983 [tests-only][full-ci]Added function to close the filesFolderUploadProgress on each upload
  tests/acceptance/pageObjects/FilesPageElement/filesList.js
  tests/acceptance/pageObjects/personalPage.js
  tests/acceptance/stepDefinitions/filesContext.js
Labels: QA:team

#6941 [tests-only] Refactored e2e test to move selector name to constant [Part 2]
  tests/e2e/support/objects/app-files/spaces/actions.ts
Labels: QA:team

#6987 [tests-only][full-ci] Use webUI steps after the server setup steps (remaining files)
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
Labels: QA:team

#6981 [tests-only] Refactored e2e test to move selector name to constant [Part 3]
  tests/e2e/support/objects/runtime/application.ts
Labels: QA:team

#6889 [tests-only] E2e test public link
  tests/e2e/cucumber/features/integrations/link.feature
  tests/e2e/cucumber/steps/app-files/link.ts
  tests/e2e/cucumber/steps/app-files/page/public.ts
  tests/e2e/cucumber/steps/app-files/resource.ts
  tests/e2e/support/environment/link.ts
  tests/e2e/support/objects/app-files/link/actions.ts
  tests/e2e/support/objects/app-files/link/index.ts
  tests/e2e/support/objects/app-files/page/public.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
Labels: QA:team

#6959 Changes to links in sidebar, fix tooltips
  changelog/unreleased/enhancement-changes-to-links-in-sidebar
  docs/getting-started.md
  packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
  packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.js.snap
  packages/web-runtime/src/store/config.js
Labels: Early-Adopter:CERN

#7010 [tests-only][full-ci]Bump ocis commit id for tests
  .drone.env
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFilesSearch/search.feature
Labels: QA:team

#7004 [full-ci] Fix breadcrumb auto focus
  changelog/unreleased/bugfix-breadcrumb-focus
  packages/web-app-files/src/mixins/accessibleBreadcrumb.js
Labels: Status:Needs-Review

#7020 [full-ci][tests-only] pin owncloud 10 to 10.10.0 for tests
  .drone.star
  tests/drone/setup-server-and-app.sh
Labels: QA:team

#6991 Use new WebDAV endpoints for uploads when spaces are enabled
  changelog/unreleased/enhancement-new-webdav-endpoints-for-uploads
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/src/composables/upload/useUploadHelpers.ts
Labels: Status:Needs-Review

#7031 [full-ci][tests-only] run tests with latest oC10
  .drone.star
Labels: QA:team

#7050 [docs-only][skip-ci] fix URL to the docs folder
  README.md
Labels: QA:team

#7033 [tests-only][full-ci]Update expected to fail file
  tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFilesSearch/search.feature
  tests/acceptance/features/webUIPreview/mediaPreview.feature
  tests/acceptance/features/webUIResharing1/reshareUsers.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
  tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature
  tests/acceptance/features/webUISharingNotifications/notificationLink.feature
  tests/acceptance/features/webUISharingNotificationsToRoot/notificationLink.feature
Labels: QA:team

#7057 [tests-only] tidy up the unit tests logs
  packages/web-app-files/tests/unit/components/SideBar/Shares/Links/NameAndCopy.spec.js
Labels: QA:team

#7022 Config option for hoverable quick actions
  changelog/unreleased/enhancement-add-config-option-hoverable-quick-actions
  docs/getting-started.md
  packages/web-app-files/src/components/FilesList/ResourceTable.vue
  packages/web-runtime/src/store/config.js
Labels: Early-Adopter:CERN

#7074 [tests-only][full-ci] Wait for file container to load after login
  tests/acceptance/helpers/loginHelper.js
Labels: QA:team
