Repository owncloud/web, pull requests merged in 2022-02, with the labels that each got.

#6346 [tests-only] Update local file create scenario using v1.3.1 middleware
  .drone.star
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/stepDefinitions/middlewareContext.js
Labels: QA:team

#6352 [tests-only][full-ci] Bump oCIS commit id for the tests
  .drone.env
Labels: QA:team

#6188 [tests-only][full-ci] Remove unused step definitions from generalContext
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
  tests/acceptance/features/webUIFiles/batchAction.feature
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
  tests/acceptance/features/webUIFilesCopy/copy.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
  tests/acceptance/features/webUIResharing1/reshareUsers.feature
  tests/acceptance/features/webUIResharing2/reshareUsers.feature
  tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
  tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFilePermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
  tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
  tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
  tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersBlacklisted/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersCollaborator/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootBlacklisted/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootCollaborator/shareWithUsers.feature
  tests/acceptance/features/webUISharingNotifications/notificationLink.feature
  tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature
  tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
  tests/acceptance/features/webUISharingNotificationsToRoot/notificationLink.feature
  tests/acceptance/features/webUISharingNotificationsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingNotificationsToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
  tests/acceptance/features/webUISharingPublicManagement/publicLinkShareByEmail.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/stepDefinitions/generalContext.js
Labels: QA:team

#6332 [tests-only][full-ci] Refactor tests to use middleware's functions
  tests/acceptance/features/webUISharingInternalUsersBlacklisted/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootBlacklisted/shareWithUsers.feature
  tests/acceptance/helpers/backendHelper.js
  tests/acceptance/helpers/httpHelper.js
  tests/acceptance/helpers/webdavHelper.js
  tests/acceptance/stepDefinitions/sharingContext.js
Labels: QA:team

#6355 [tests-only] [full-ci] Fix expected-failures references
  tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
Labels: QA:team

#6357 [tests-only] [full-ci] Adjust CI pipelines to reduce acceptance test elapsed time
  .drone.star
Labels: QA:team

#6375 [tests-only][full-ci] Remove duplicate functions to use middleware's
  tests/acceptance/helpers/userSettings.js
Labels: QA:team

#6384 Add vscode folder to the gitignore list
  .gitignore
Labels: Type:Technical-Debt

#6392 [tests-only][full-ci]Bump the commit id for tests
  .drone.env
Labels: QA:team

#6398 [tests-only] mock setModalInputErrorMessage in Projects.spec.js
  packages/web-app-files/tests/unit/views/spaces/Projects.spec.js
Labels: QA:team

#6395 [tests-only][full-ci] Create report directory if not exists
  tests/acceptance/setup.js
Labels: QA:team

#6407 [tests-only] use jest.mocked instead of mocked from ts-jest/utils
  packages/web-runtime/tests/unit/container/bootstrap.spec.ts
Labels: QA:team

#6406 [tests-only] stub oc-list element in ApplicationsMenu unit tests
  packages/web-runtime/tests/unit/components/Topbar/ApplicationsMenu.spec.js
  packages/web-runtime/tests/unit/components/Topbar/__snapshots__/ApplicationsMenu.spec.js.snap
Labels: QA:team

#6408 [tests-only] mock date/time functions in FileInfo unit test
  packages/web-app-files/tests/unit/components/SideBar/FileInfo.spec.js
  packages/web-app-files/tests/unit/components/SideBar/__snapshots__/FileInfo.spec.js.snap
Labels: QA:team

#6409 [tests-only] mock files-spaces-personal-home route in SharedViaLink unit tests
  packages/web-app-files/tests/unit/views/SharedViaLink.spec.js
Labels: QA:team

#6405 [tests-only] reduce log output when running unit tests of SideBar
  packages/web-app-files/tests/unit/components/SideBar/SideBar.spec.js
Labels: QA:team

#6413 fix variable name in error object
  changelog/unreleased/bugfix-error-message-move
  packages/web-app-files/src/views/Personal.vue
  packages/web-app-files/tests/unit/views/Personal.spec.js
Labels: QA:team

#6415 [tests-only] throw an exception on uhandled exception in unit tests
  package.json
  packages/web-app-files/tests/unit/composables/pagination/usePagination.spec.ts
  packages/web-app-files/tests/unit/views/spaces/Project.spec.js
  tests/unit/config/jest.init.js
Labels: QA:team

#6404 [tests-only] remove language related log outputs in unit-tests
  packages/web-app-files/tests/unit/views/LocationPicker.spec.js
  packages/web-app-files/tests/unit/views/__snapshots__/SharedViaLink.spec.js.snap
  packages/web-app-files/tests/unit/views/spaces/Project.spec.js
  packages/web-app-files/tests/unit/views/spaces/Projects.spec.js
  packages/web-app-files/tests/unit/views/spaces/__snapshots__/Project.spec.js.snap
  packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap
  packages/web-app-files/tests/unit/views/views.setup.js
  tests/unit/config/jest.init.js
Labels: QA:team

#6435 [tests-only] [full-ci] Bump oCIS commit id
  .drone.env
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
Labels: QA:team

#6442 [tests-only] Bumped test middleware version to v1.4.0
  .drone.star
Labels: QA:team

#6449 Fix file creation
  packages/web-app-files/src/components/AppBar/AppBar.vue
Labels: Early-Adopter:CERN

#6376 [tests-only] Added implementation for file old version restore, check file is restored
  tests/e2e/cucumber/shareFolderJourney.feature
  tests/e2e/cucumber/step_definitions/app.files.ts
  tests/e2e/filesForUpload/PARENT/simple.pdf
  tests/e2e/support/page/files/version.ts
Labels: QA:team

#6363 [full-ci] ADD VUE history mode
  .drone.star
  changelog/unreleased/enhancement-history-mode
  changelog/unreleased/enhancement-sidecar-mode
  config/config.json.sample-oc10
  dev/docker/oc10.Dockerfile
  dev/docker/oc10.entrypoint.sh
  docker-compose.yml
  packages/web-container/oidc-callback.html
  packages/web-container/oidc-silent-redirect.html
  packages/web-runtime/src/defaults/index.ts
  packages/web-runtime/src/index.ts
  packages/web-runtime/src/router/index.js
  packages/web-runtime/src/services/auth.js
  packages/web-runtime/src/services/clientRegistration.js
  packages/web-runtime/src/store/user.js
  packages/web-runtime/tests/unit/router/index.spec.ts
  tests/acceptance/features/webUILogin/oauthLogin.feature
  tests/acceptance/helpers/loginHelper.js
  tests/acceptance/pageObjects/accountPage.js
  tests/acceptance/pageObjects/ownCloudAuthorizePage.js
  tests/acceptance/pageObjects/webPage.js
  tests/acceptance/stepDefinitions/loginContext.js
Labels: QA:team

#6422 [tests-only] Add e2e test for creating public link
  tests/e2e/cucumber/publicLinkToFolderJourney.feature
  tests/e2e/cucumber/step_definitions/app.files.ts
  tests/e2e/support/page/files/index.ts
  tests/e2e/support/page/files/publicLink.ts
  tests/e2e/support/utils/datePicker.ts
Labels: QA:team

#6467 revert all files breadcrumb link to /
  changelog/unreleased/bugfix-breadcrumb-root-path
  packages/web-app-files/src/components/AppBar/AppBar.vue
  packages/web-app-files/src/views/Personal.vue
Labels: Early-Adopter:CERN

#6447 Do not load files from cache
  changelog/unreleased/bugfix-do-not-load-from-cache
  packages/web-app-draw-io/src/App.vue
  packages/web-pkg/src/composables/appDefaults/useAppFileHandling.ts
Labels: Early-Adopter:CERN

#6483 [test-only] check in shared with me page first after unsharing
  tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature
Labels: QA:team

#6464 [tests-only] updated artifact upload location to `cache_public_s3`
  .drone.star
Labels: QA:team

#6490 [docs] add unit test spec file structure information
  docs/testing/testing.md
Labels: QA:team

#6489 [unit-tests] Refactor unit test specs to follow the general pattern
  packages/web-app-files/tests/unit/components/AppBar/Upload/FileUpload.spec.js
  packages/web-app-files/tests/unit/components/FilesList/ListInfo.spec.js
  packages/web-app-files/tests/unit/components/FilesList/NoContentMessage.spec.js
  packages/web-app-files/tests/unit/components/FilesList/NotFoundMessage.spec.js
  packages/web-app-files/tests/unit/components/FilesList/Pagination.spec.js
  packages/web-app-files/tests/unit/components/FilesList/QuickActions.spec.js
  packages/web-app-files/tests/unit/components/Search/List.spec.js
  packages/web-app-files/tests/unit/components/Search/Preview.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Details/SpaceDetails.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Links/CopyToClipboardButton.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkActions.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkEdit.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkInfo.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/ListItem.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Shares/InviteCollaborator/ExpirationDatepicker.spec.ts
  packages/web-app-files/tests/unit/components/SideBar/Shares/InviteCollaborator/RecipientContainer.spec.js
  packages/web-app-files/tests/unit/components/SideBar/SideBar.spec.js
  packages/web-app-files/tests/unit/components/SideBar/Versions/FileVersions.spec.js
  packages/web-app-files/tests/unit/helpers/user/avatarUrl.spec.ts
  packages/web-app-files/tests/unit/mixins/actions/delete.spec.js
  packages/web-app-files/tests/unit/mixins/actions/rename.spec.js
  packages/web-app-files/tests/unit/mixins/deleteResources.spec.js
  packages/web-app-files/tests/unit/mixins/resources.spec.js
  packages/web-app-files/tests/unit/mixins/spaces/delete.spec.js
  packages/web-app-files/tests/unit/mixins/spaces/disable.spec.js
  packages/web-app-files/tests/unit/mixins/spaces/editDescription.spec.js
  packages/web-app-files/tests/unit/mixins/spaces/rename.spec.js
  packages/web-app-files/tests/unit/mixins/spaces/restore.spec.js
  packages/web-app-files/tests/unit/mixins/spaces/showDetails.spec.js
  packages/web-runtime/tests/unit/components/SidebarNav/SidebarNav.spec.js
  packages/web-runtime/tests/unit/components/Topbar/Notification.spec.js
  packages/web-runtime/tests/unit/components/Topbar/TopBar.spec.js
Labels: QA:team
