Repository owncloud/web, pull requests merged in 2022-11, with the labels that each got.

#7767 [full-ci][tests-only]Skip scenario related to occ command in ocis
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsersBlacklisted/shareWithUsers.feature
Labels: QA:team

#7897 [full-ci] [tests-only] Refactored inter scenarios space
  tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
  tests/acceptance/features/webUIFilesActionMenu/fileFolderActionMenu.feature
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
  tests/acceptance/features/webUIFilesDetails/fileDetails.feature
  tests/acceptance/features/webUIFilesList/fileList.feature
  tests/acceptance/features/webUIFilesList/sort.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
  tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/features/webUIResharing1/reshareUsers.feature
  tests/acceptance/features/webUIResharingToRoot/reshareUsers.feature
  tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsToRootEdgeCases/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootCollaborator/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootPreviews/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersToRootShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkPublicActions.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
  tests/acceptance/features/webUISharingPublicManagement/publicLinkIndicator.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
Labels: QA:team

#7895 [tests-only][full-ci]Skip Shares folder related tests on ocis of moveFiles.feature
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
Labels: QA:team

#7909 [full-ci] [tests-only] Bump ocis commit id to latest
  .drone.env
Labels: QA:team

#7904 [full-ci] Hide batch actions if only 1 resource has been selected
  packages/web-app-files/src/components/AppBar/AppBar.vue
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/tests/unit/components/AppBar/AppBar.spec.js
  packages/web-app-files/tests/unit/components/AppBar/__snapshots__/AppBar.spec.js.snap
  tests/acceptance/features/webUIFiles/batchAction.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/utils/sidebar.ts
Labels: Category:Enhancement, Topic:UX-Design

#7912 Increase default XHR timeout and make it configurable
  changelog/unreleased/enhancement-xhr-timeout
  config/config.json.sample-oc10
  config/config.json.sample-ocis
  docs/getting-started.md
  packages/web-runtime/src/composables/upload/useUpload.ts
  packages/web-runtime/src/services/uppyService.ts
Labels: Category:Enhancement

#7953 [tests-only][full-ci]Bump `OCIS` latest commit
  .drone.env
Labels: QA:team

#7992 [tests-only][full-ci]Bump ocis latest commit-id
  .drone.env
Labels: QA:team

#7975 Prevent file upload when folder creation failed
  changelog/unreleased/bugfix-file-upload-with-failed-folder-creation
  packages/web-app-files/src/helpers/resource/actions/upload.ts
  packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.js
  packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.ts
  packages/web-app-files/tests/unit/helpers/resource/actions/upload.spec.ts
  packages/web-client/src/helpers/resource/types.ts
  packages/web-runtime/src/components/UploadInfo.vue
  packages/web-runtime/src/composables/upload/useUpload.ts
  packages/web-runtime/tests/unit/composables/upload/useUpload.spec.ts
Labels: Type:Bug

#7984 [tests-only][full-ci]Remove check for expiration date in december month
  tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
  tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
Labels: QA:team

#7989 Fix file versions on 'Shared with me'-page
  changelog/unreleased/bugfix-versions-on-shared-with-me-page
  packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
  packages/web-runtime/src/plugins/web.js
Labels: Status:Needs-Review

#8002 [tests-only] Add unit tests for the text editor
  packages/web-app-text-editor/package.json
  packages/web-app-text-editor/tests/unit/app.spec.ts
  packages/web-client/src/webdav/getFileContents.ts
  packages/web-test-helpers/src/mocks/defaultStubs.ts
  packages/web-test-helpers/src/mocks/useAppDefaultsMock.ts
  pnpm-lock.yaml
Labels: Status:Needs-Review

#8015 Fix quota check when replacing files
  changelog/unreleased/bugfix-quota-check-when-replacing-files
  packages/web-app-files/src/helpers/resource/actions/upload.ts
  packages/web-app-files/tests/unit/helpers/resource/actions/upload.spec.ts
Labels: Status:Needs-Review

#8009 Prevent shares from disappearing after sharing with groups
  changelog/unreleased/bugfix-disappearing-shares
  packages/web-app-files/src/store/actions.ts
  packages/web-app-files/tests/unit/store/actions.spec.js
  packages/web-app-files/tests/unit/store/actions.spec.ts
  packages/web-client/src/types.ts
Labels: Status:Needs-Review

#8019 [tests-only][full-ci]Bump commit id for tests
  .drone.env
Labels: QA:team

#8006 [full-ci] Fix public link loading on role change
  changelog/unreleased/bugfix-public-link-load-on-role-change
  packages/web-app-files/src/views/spaces/DriveResolver.vue
  packages/web-app-files/tests/unit/composables/composables.setup.ts
  packages/web-app-files/tests/unit/composables/driveResolver/useDriveResolver.spec.ts
  packages/web-app-files/tests/unit/views/spaces/DriveResolver.spec.ts
  packages/web-pkg/src/composables/driveResolver/useDriveResolver.ts
Labels: Status:Needs-Review

#7983 [full-ci] Improve UX of the conflict dialog
  changelog/unreleased/enhancement-conflict-dialog-ux
  packages/web-app-files/src/helpers/resource/actions/transfer.ts
  packages/web-app-files/src/helpers/resource/actions/upload.ts
  packages/web-app-files/src/helpers/resource/conflictHandling/conflictDialog.ts
  packages/web-app-files/tests/unit/helpers/resource/actions/upload.spec.ts
  packages/web-app-files/tests/unit/helpers/resource/conflictHandling/conflictDialog.spec.ts
  packages/web-app-files/tests/unit/helpers/resource/resourcesTransfer.spec.ts
  tests/acceptance/features/webUIFilesCopy/copy.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
Labels: Status:Needs-Review
