Repository owncloud/web, pull requests merged in 2023-12, with the labels that each got.

#10103 [docs-only] docs: add hint not to pass bearer string in embed mode access token
  docs/embed-mode/_index.md
Labels: Status:Needs-Review, Topic:Documentation, Category:Nonfunctional

#10113 fix: skip reusing old token in embed mode with delegated auth
  changelog/unreleased/enhancement-add-auth-delegation
  packages/web-runtime/src/pages/oidcCallback.vue
  packages/web-runtime/src/services/auth/authService.ts
  packages/web-runtime/tests/unit/services/auth/authService.spec.ts
Labels: Status:Needs-Review, Category:Defect

#9949 [tests-only][full-ci] use nats registry in ocis
  .drone.star
Labels: QA:team

#10119 [tests-only][full-ci]assign role to user through keycloak
  tests/e2e/cucumber/steps/api.ts
  tests/e2e/support/api/keycloak/user.ts
  tests/e2e/support/api/provision/user.ts
  tests/e2e/support/objects/runtime/session.ts
Labels: QA:team

#10147 [tests-only][full-ci]tests: bump ocis commit id for tests
  .drone.env
  .drone.star
  tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkPublicActions.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
  tests/acceptance/features/webUISharingPublicManagement/sharingPublicSession.feature
  tests/acceptance/features/webUIUpload/upload.feature
Labels: QA:team

#10167 [tests-only][full-ci]change the `mdns` registry for app provider to `natsjs`
  docker-compose.yml
Labels: QA:team

#10136 [tests-only]tests: add e2e tests for url stability
  tests/e2e/cucumber/features/smoke/spaces/project.feature
  tests/e2e/cucumber/features/smoke/urlJourneys.feature
  tests/e2e/cucumber/steps/ui/navigateByUrl.ts
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/cucumber/steps/ui/shares.ts
  tests/e2e/support/environment/file.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/share/actions.ts
  tests/e2e/support/objects/index.ts
  tests/e2e/support/objects/url-navigation/actions.ts
  tests/e2e/support/objects/url-navigation/index.ts
Labels: QA:team

#10190 Typo: WebDAV + URL with uppercase characters
  deployments/examples/ocis_web/docker-compose.yml
  packages/web-pkg/src/components/SideBar/WebDavDetails.vue
  packages/web-runtime/src/pages/account.vue
Labels: Status:Needs-Review, Category:Nonfunctional

#10203 [tests-only] test: add missed logout step
  tests/e2e/cucumber/features/smoke/urlJourneys.feature
Labels: QA:team

#10204 [tests-only] test: add missed logout step
  tests/e2e/cucumber/features/smoke/urlJourneys.feature
Labels: QA:team

#10174 [tests-only] e2e tests for url stability open file directly in the web
  tests/e2e/cucumber/features/smoke/urlJourneys.feature
  tests/e2e/cucumber/steps/ui/navigateByUrl.ts
  tests/e2e/support/api/davSpaces/spaces.ts
  tests/e2e/support/objects/url-navigation/actions.ts
  tests/e2e/support/objects/url-navigation/index.ts
Labels: QA:team

#10202 [tests-only] test: add e2e test for directly opening project space through url
  tests/e2e/cucumber/features/smoke/urlJourneys.feature
  tests/e2e/cucumber/steps/ui/navigateByUrl.ts
  tests/e2e/support/objects/url-navigation/actions.ts
  tests/e2e/support/objects/url-navigation/index.ts
Labels: QA:team

#10211 [tests-only][full-ci] test: add e2e test for directly opening project space through url
  tests/e2e/cucumber/features/smoke/urlJourneys.feature
  tests/e2e/cucumber/steps/ui/navigateByUrl.ts
  tests/e2e/support/objects/url-navigation/actions.ts
  tests/e2e/support/objects/url-navigation/index.ts
Labels: QA:team

#10228 [tests-only][full-ci]Bump commit id for tests
  .drone.env
  tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
Labels: QA:team

#10229 [tests-only][full-ci]Bump ocis commit id for tests
  .drone.env
  tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
Labels: QA:team

#10219 [tests-only] test: add e2e url stability test for the file without editor
  tests/e2e/cucumber/features/smoke/urlJourneys.feature
Labels: QA:team

#10245 [tests-only][full-ci]Bump commit id for tests
  .drone.env
Labels: QA:team

#10244 [tests-only][full-ci] Bump ocis commit id for tests
  .drone.env
Labels: QA:team
