Repository owncloud/web, pull requests merged in 2023-11, with the labels that each got.

#9827 [tests-only][full-ci]Check for suite existence in the expected to failure files
  .drone.star
  tests/acceptance/check-deleted-suites-in-expected-failure.sh
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
Labels: QA:team

#9899 [tests-only][full-ci]Backport bash script to check deleted suites to `stable-7.1`
  .drone.star
  tests/acceptance/check-deleted-suites-in-expected-failure.sh
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
Labels: QA:team

#9901 [tests-only][full-ci] Bump ocis latest commit id
  .drone.env
Labels: QA:team

#9902 [tests-only][full-ci] Bump ocis latest commit id on stable
  .drone.env
Labels: QA:team

#9903 [tests-only][full-ci]implement separate step for dropdown-menu and batch-action for copy and move
  tests/e2e/cucumber/features/smoke/copyMove.feature
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
Labels: QA:team

#9909 [tests-only][full-ci]implement separate step for dropdown-menu and batch-action for copy and move
  tests/e2e/cucumber/features/smoke/copyMove.feature
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
Labels: QA:team

#9895 [tests-only][full-ci]add test for copy and move multiple files at once
  tests/e2e/cucumber/features/smoke/copyMove.feature
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: QA:team

#9914 [tests-only][full-ci]add test for copy and move multiple files at once
  tests/e2e/cucumber/features/smoke/copyMove.feature
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: QA:team

#9928 [tests-only][full-ci] Bump ocis latest commit id
  .drone.env
Labels: QA:team

#9929 [tests-only][full-ci] Bump ocis stable commit
  .drone.env
Labels: QA:team

#9933 [tests-only][full-ci]fix ocis-cache-build
  tests/drone/check-oCIS-cache.sh
Labels: QA:team

#9981 Use postMessage in embed mode instead of custom events
  changelog/unreleased/enhancement-embed-mode-actions
  changelog/unreleased/enhancement-location-picker
  docs/embed-mode/_index.md
  packages/web-app-files/src/components/EmbedActions/EmbedActions.vue
  packages/web-app-files/tests/unit/components/EmbedActions/EmbedActions.spec.ts
  packages/web-app-files/tests/unit/views/spaces/GenericSpace.spec.ts
  packages/web-pkg/src/composables/embedMode/useEmbedMode.ts
  packages/web-pkg/src/configuration/types.ts
  packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
  packages/web-runtime/src/container/bootstrap.ts
  packages/web-runtime/src/store/config.ts
  packages/web-runtime/tests/unit/components/Topbar/TopBar.spec.ts
  packages/web-runtime/tests/unit/container/bootstrap.spec.ts
Labels: Category:Change

#10051 [full-ci] chore: bump pnpm to version 8.10.5
  .drone.star
  Makefile
  Makefile.release
  package.json
  pnpm-lock.yaml
  tests/e2e/cucumber/environment/index.ts
  tests/e2e/cucumber/environment/shared.ts
  tests/e2e/cucumber/steps/ui/public.ts
  tests/e2e/support/environment/actor/actor.ts
  tests/e2e/support/environment/actor/actors.ts
  tests/e2e/support/environment/actor/shared.ts
  tests/e2e/support/objects/account/actions.ts
  tests/e2e/support/objects/account/index.ts
  tests/e2e/support/objects/app-admin-settings/general/index.ts
  tests/e2e/support/objects/app-admin-settings/groups/actions.ts
  tests/e2e/support/objects/app-admin-settings/groups/index.ts
  tests/e2e/support/objects/app-admin-settings/page/general.ts
  tests/e2e/support/objects/app-admin-settings/page/groups.ts
  tests/e2e/support/objects/app-admin-settings/page/spaces.ts
  tests/e2e/support/objects/app-admin-settings/page/users.ts
  tests/e2e/support/objects/app-admin-settings/spaces/actions.ts
  tests/e2e/support/objects/app-admin-settings/spaces/index.ts
  tests/e2e/support/objects/app-admin-settings/users/actions.ts
  tests/e2e/support/objects/app-admin-settings/users/index.ts
  tests/e2e/support/objects/app-files/link/actions.ts
  tests/e2e/support/objects/app-files/link/index.ts
  tests/e2e/support/objects/app-files/page/public.ts
  tests/e2e/support/objects/app-files/page/shares/withMe.ts
  tests/e2e/support/objects/app-files/page/spaces/personal.ts
  tests/e2e/support/objects/app-files/page/spaces/projects.ts
  tests/e2e/support/objects/app-files/page/trashbin/overview.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
  tests/e2e/support/objects/app-files/resource/utils.ts
  tests/e2e/support/objects/app-files/search/actions.ts
  tests/e2e/support/objects/app-files/search/index.ts
  tests/e2e/support/objects/app-files/share/actions.ts
  tests/e2e/support/objects/app-files/share/collaborator.ts
  tests/e2e/support/objects/app-files/share/index.ts
  tests/e2e/support/objects/app-files/share/utils.ts
  tests/e2e/support/objects/app-files/spaces/actions.ts
  tests/e2e/support/objects/app-files/spaces/index.ts
  tests/e2e/support/objects/app-files/spaces/utils.ts
  tests/e2e/support/objects/app-files/trashbin/actions.ts
  tests/e2e/support/objects/app-files/trashbin/index.ts
  tests/e2e/support/objects/app-files/utils/editor.ts
  tests/e2e/support/objects/app-files/utils/sidebar.ts
  tests/e2e/support/objects/runtime/application.ts
  tests/e2e/support/objects/runtime/session.ts
  tests/e2e/support/types.ts
  tests/e2e/support/utils/dragDrop.ts
Labels: QA:team

#10032 [full-ci] [tests-only] Bump ocis commit id stable
  .drone.env
Labels: QA:team

#10058 [test-only] create e2e test for shortcut feature
  tests/e2e/cucumber/features/smoke/shortcut.feature
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: Status:Needs-Review

#10068 [tests-only][full-ci]Down grade the `wopiserver` version for `app-provider` e2e tests
  .drone.star
Labels: QA:team

#10082 feat: delegate auth in embed mode
  changelog/unreleased/enhancement-add-auth-delegation
  docs/embed-mode/_index.md
  packages/web-app-files/tests/unit/components/EmbedActions/EmbedActions.spec.ts
  packages/web-app-files/tests/unit/views/spaces/GenericSpace.spec.ts
  packages/web-pkg/src/composables/embedMode/useEmbedMode.ts
  packages/web-pkg/src/configuration/manager.ts
  packages/web-pkg/src/configuration/types.ts
  packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
  packages/web-pkg/tests/unit/composables/embedMode/useEmbedMode.spec.ts
  packages/web-runtime/src/container/bootstrap.ts
  packages/web-runtime/src/pages/oidcCallback.vue
  packages/web-runtime/src/router/setupAuthGuard.ts
  packages/web-runtime/src/services/auth/authService.ts
  packages/web-runtime/src/services/auth/userManager.ts
  packages/web-runtime/src/store/config.ts
  packages/web-runtime/tests/unit/components/Topbar/TopBar.spec.ts
  packages/web-runtime/tests/unit/pages/oidcCallback.spec.ts
  packages/web-runtime/tests/unit/services/auth/authService.spec.ts
Labels: Category:Enhancement, Status:Needs-Review
