Repository owncloud/web, pull requests merged in 2023-02, with the labels that each got.

#8260 [full-ci][tests-only]Add internal link related e2e tests
  tests/e2e/cucumber/features/smoke/internalLink.ocis.feature
  tests/e2e/cucumber/steps/api.ts
  tests/e2e/cucumber/steps/ui/links.ts
  tests/e2e/cucumber/steps/ui/session.ts
  tests/e2e/support/api/share/share.ts
  tests/e2e/support/environment/actor/actor.ts
  tests/e2e/support/objects/app-files/page/shares/withMe.ts
  tests/e2e/support/types.ts
Labels: QA:team

#8353 [tests-only][full-ci] Add e2e tests related to internal link in personal space (port)
  tests/e2e/cucumber/features/smoke/internalLink.ocis.feature
  tests/e2e/cucumber/steps/api.ts
  tests/e2e/cucumber/steps/ui/links.ts
  tests/e2e/cucumber/steps/ui/session.ts
  tests/e2e/support/api/share/share.ts
  tests/e2e/support/environment/actor/actor.ts
  tests/e2e/support/objects/app-files/page/shares/withMe.ts
  tests/e2e/support/types.ts
Labels: QA:team

#8359 [tests-only][full-ci]Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#8358 [tests-only][full-ci]Bump commit id for tests in stable branch
  .drone.env
Labels: QA:team

#8348 [tests-only][full-ci]Expand kinder garden feature to delete serveral `objects/resources`
  tests/e2e/cucumber/features/journeys/kindergarten.oc10.feature
  tests/e2e/cucumber/features/journeys/kindergarten.ocis.feature
  tests/e2e/cucumber/features/smoke/share.oc10.feature
  tests/e2e/cucumber/features/smoke/share.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature
  tests/e2e/cucumber/steps/ui/public.ts
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: QA:team

#8385 [tests-only][full-ci]Forward port to delete serveral `(objects|resources)`
  tests/e2e/cucumber/features/journeys/kindergarten.oc10.feature
  tests/e2e/cucumber/features/journeys/kindergarten.ocis.feature
  tests/e2e/cucumber/features/smoke/share.oc10.feature
  tests/e2e/cucumber/features/smoke/share.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature
  tests/e2e/cucumber/steps/ui/public.ts
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: QA:team

#8394 [tests-only][full-ci] Confirm context save completion
  tests/acceptance/pageObjects/textEditorPage.js
Labels: QA:team

#8396 [tests-only][full-ci] Wait until file saving is finished (forward port)
  tests/acceptance/pageObjects/textEditorPage.js
Labels: QA:team

#8401 [tests-only][full-ci]Bump commit id for tests
  .drone.env
Labels: QA:team

#8402 [tests-only][full-ci]Bump commit id for tests in stable-6.0
  .drone.env
Labels: QA:team

#7596 [full-ci] Performance improvements
  packages/web-runtime/src/index.ts
  packages/web-runtime/src/services/auth/userManager.ts
Labels: Early-Adopter:CERN

#8393 [tests-only][full-ci] Fix upload success check
  tests/acceptance/pageObjects/personalPage.js
Labels: QA:team

#8408 [tests-only][full-ci] Forward port fix upload success check
  tests/acceptance/pageObjects/personalPage.js
Labels: QA:team

#8382 [tests-only][full-ci]Assign role using graph api
  tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
  tests/e2e/cucumber/features/smoke/searchProjectSpace.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/internalLink.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/memberExpiry.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature
  tests/e2e/cucumber/steps/api.ts
  tests/e2e/support/api/graph/index.ts
  tests/e2e/support/api/graph/userManagement.ts
  tests/e2e/support/api/graph/utils.ts
  tests/e2e/support/store/index.ts
  tests/e2e/support/store/role.ts
Labels: QA:team

#8398 cleanup sidebar actions (fileinfo + spaces)
  changelog/unreleased/enhancement-fix-action-list-layout
  packages/web-app-admin-settings/src/components/Spaces/SideBar/ActionsPanel.vue
  packages/web-app-files/src/components/SideBar/Actions/FileActions.vue
  packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue
  packages/web-app-files/src/components/SideBar/FileInfo.vue
  packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceContextActions.spec.ts.snap
  packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap
  packages/web-pkg/src/components/ContextActions/ActionMenuItem.vue
  packages/web-pkg/src/components/sideBar/Spaces/SpaceInfo.vue
  packages/web-pkg/tests/unit/components/sidebar/Spaces/__snapshots__/SpaceInfo.spec.ts.snap
Labels: Status:Needs-Review, Category:Nonfunctional

#7965 Up roles defaults
  changelog/unreleased/enhancement-optional-roles
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
  packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
  packages/web-app-files/src/store/actions.ts
  packages/web-app-files/tests/unit/components/SideBar/Shares/Links/DetailsAndEdit.spec.ts
  packages/web-client/src/helpers/share/role.ts
  packages/web-client/tests/unit/helpers/share/role.spec.ts
  packages/web-pkg/src/composables/capability/useCapability.ts
Labels: Early-Adopter:CERN

#8449 Up configurable topbar
  changelog/unreleased/enhancement-configurable-topbar
  packages/web-runtime/src/components/Topbar/TopBar.vue
  packages/web-runtime/tests/unit/components/Topbar/__snapshots__/TopBar.spec.ts.snap
Labels: Early-Adopter:CERN

#8463 [full-ci] [tests-only] Bump ocis master commit id to latest
  .drone.env
Labels: QA:team

#8464 [full-ci] [tests-only] Bump ocis commit id stable
  .drone.env
Labels: QA:team

#8500 [tests-only][full-ci]Bump commit id for tests
  .drone.env
Labels: QA:team

#8501 [tests-only][full-ci]Bump commit id for tests in stable
  .drone.env
Labels: QA:team

#8498 PDFViewer / CSP - frame-src object-src blob:
  changelog/unreleased/bugfix-oc10-pdf-display
  packages/web-integration-oc10/lib/Controller/FilesController.php
Labels: Status:Needs-Review
