Repository owncloud/web, pull requests merged in 2023-03, with the labels that each got.

#8499 [tests-only][full-ci] Add a e2e test for quick link
  tests/e2e/cucumber/features/smoke/link.feature
  tests/e2e/support/environment/actor/shared.ts
  tests/e2e/support/objects/app-files/share/actions.ts
Labels: QA:team

#8504 [full-ci] style file versions list
  changelog/unreleased/enhancement-re-style-file-versions
  packages/design-system/changelog/unreleased/enhancement-add-font-weight-classes
  packages/design-system/changelog/unreleased/enhancement-add-font-weight-variables
  packages/design-system/changelog/unreleased/enhancement-add-negative-margin
  packages/design-system/src/styles/styles.scss
  packages/design-system/src/styles/theme/_variables.scss
  packages/design-system/src/styles/theme/oc-card.scss
  packages/design-system/src/styles/theme/oc-spacing-negative.scss
  packages/design-system/src/styles/theme/oc-text.scss
  packages/design-system/src/tokens/ods/font.yaml
  packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
  packages/web-app-files/src/components/SideBar/Details/FileDetailsMultiple.vue
  packages/web-app-files/src/components/SideBar/FileInfo.vue
  packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
  packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.ts.snap
  packages/web-app-files/tests/unit/components/SideBar/Versions/FileVersions.spec.ts
  packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetails.vue
  packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetailsMultiple.vue
  packages/web-pkg/src/components/sideBar/Spaces/SpaceInfo.vue
  packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/__snapshots__/SpaceDetails.spec.ts.snap
  packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/__snapshots__/SpaceDetailsMultiple.spec.ts.snap
  packages/web-pkg/tests/unit/components/sidebar/Spaces/__snapshots__/SpaceInfo.spec.ts.snap
  tests/acceptance/pageObjects/FilesPageElement/versionsDialog.js
Labels: Category:Enhancement, Status:Needs-Review

#8522 add dark ownCloud logo
  changelog/unreleased/enhancement-add-dark-owncloud-logo
  packages/web-runtime/themes/owncloud/assets/logo_dark.svg
Labels: Status:Waiting-for-Feedback

#8473 Update CERN links
  changelog/unreleased/enhancement-cern-links
  packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
  packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.ts
Labels: Early-Adopter:CERN

#8530 [tests-only][full-ci] Add a e2e test for quick link (#8499)
  tests/e2e/cucumber/features/smoke/link.feature
  tests/e2e/support/environment/actor/shared.ts
  tests/e2e/support/objects/app-files/share/actions.ts
Labels: QA:team

#8531 [tests-only][full-ci] Refactor e2e test for quick link
  tests/e2e/support/environment/actor/shared.ts
  tests/e2e/support/objects/app-files/share/actions.ts
Labels: QA:team

#8569 [full-ci] [tests-only] Bump ocis-master commit id to latest `master`
  .drone.env
Labels: QA:team

#8568 [full-ci] [tests-only] Bump ocis stable commit `stable-6.0`
  .drone.env
Labels: QA:team

#8632 [tests-only][full-ci]Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#8637 [tests-only]Fix formatting of feature files
  tests/e2e/cucumber/features/smoke/notifications.oc10.feature
  tests/e2e/cucumber/features/smoke/notifications.ocis.feature
  tests/e2e/cucumber/features/smoke/search.feature
  tests/e2e/cucumber/features/smoke/spaces/internalLink.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature
  tests/e2e/cucumber/features/smoke/tags.ocis.feature
  tests/e2e/cucumber/features/smoke/tiles.feature
  tests/e2e/cucumber/features/smoke/upload.feature
Labels: QA:team

#8636 [tests-only][full-ci]Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#8631 [tests-only]Fix flaky login e2e test
  tests/e2e/cucumber/features/smoke/admin-settings/general.ocis.feature
  tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature
  tests/e2e/cucumber/features/smoke/notifications.oc10.feature
Labels: QA:team

#8619 [test-only] delete users test
  tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/support/objects/app-admin-settings/users/actions.ts
  tests/e2e/support/objects/app-admin-settings/users/index.ts
Labels: Status:Needs-Review

#8615 [tests-only] Adds e2e tests for managing space admin settings via context menu
  tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
  tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/support/objects/app-admin-settings/spaces/actions.ts
  tests/e2e/support/objects/app-admin-settings/spaces/index.ts
Labels: QA:team

#8629 [tests-only] Adds e2e tests for enabling and setting quota of spaces with batch-action
  tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/support/objects/app-admin-settings/spaces/actions.ts
  tests/e2e/support/objects/app-admin-settings/spaces/index.ts
Labels: QA:team

#8651 [test-only] get group test
  tests/e2e/cucumber/features/smoke/admin-settings/groups.ocis.feature
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/support/api/graph/userManagement.ts
  tests/e2e/support/objects/app-admin-settings/groups/actions.ts
  tests/e2e/support/objects/app-admin-settings/groups/index.ts
  tests/e2e/support/types.ts
Labels: Status:Needs-Review

#8674 [tests-only][full-ci] Added e2e tests for filtering users list by role
  tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature
Labels: QA:team

#8673 [tests-only]Add tests for opening edit panel via quick action and context menu
  tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/support/objects/app-admin-settings/users/actions.ts
  tests/e2e/support/objects/app-admin-settings/users/index.ts
Labels: QA:team

#8683 [tests-only][full-ci]Bump ocis commit id
  .drone.env
Labels: QA:team

#8661 [tests-only][full-ci]Add test to check the list of members in a space in the admin settings via sidebar panel
  packages/web-app-admin-settings/src/components/Spaces/SideBar/MembersPanel.vue
  packages/web-app-admin-settings/src/components/Spaces/SideBar/MembersRoleSection.vue
  tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
  tests/e2e/cucumber/steps/api.ts
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/support/api/davSpaces/index.ts
  tests/e2e/support/api/davSpaces/spaces.ts
  tests/e2e/support/api/share/index.ts
  tests/e2e/support/api/share/share.ts
  tests/e2e/support/objects/app-admin-settings/spaces/actions.ts
  tests/e2e/support/objects/app-admin-settings/spaces/index.ts
Labels: QA:team

#8687 [tests-only][full-ci] Check multiple response
  tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/support/objects/app-admin-settings/spaces/actions.ts
  tests/e2e/support/objects/app-admin-settings/spaces/index.ts
Labels: QA:team

#8696 [tests-only]Add assertion in a e2e tests
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/support/objects/app-admin-settings/spaces/actions.ts
Labels: QA:team

#8697 [full-ci][tests-only] Added wait for responses after batch actions
  tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/support/objects/app-admin-settings/groups/actions.ts
  tests/e2e/support/objects/app-admin-settings/groups/index.ts
  tests/e2e/support/objects/app-admin-settings/spaces/index.ts
  tests/e2e/support/objects/app-admin-settings/users/actions.ts
  tests/e2e/support/objects/app-admin-settings/users/index.ts
Labels: QA:team

#8635 [full-ci] [tests-only] Fixes for e2e test failure
  tests/e2e/support/objects/app-files/utils/sidebar.ts
Labels: QA:team

#8608 [full-ci] Slightly update modal layout
  packages/design-system/changelog/unreleased/enhancement-beautify-modals
  packages/design-system/src/components/OcModal/OcModal.vue
  packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap
  packages/web-app-admin-settings/src/composables/actions/groups/useGroupActionsDelete.ts
  packages/web-app-admin-settings/src/composables/actions/users/useUserActionsDelete.ts
  packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
  packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
  packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
  packages/web-app-files/src/composables/actions/files/useFileActionsEmptyTrashBin.ts
  packages/web-app-files/src/composables/actions/helpers/useFileActionsDeleteResources.ts
  packages/web-app-files/src/helpers/resource/conflictHandling/conflictDialog.ts
  packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDelete.ts
  packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDisable.ts
  packages/web-pkg/src/composables/actions/spaces/useSpaceActionsRestore.ts
Labels: Status:Needs-Review

#8723 [full-ci][tests-only] Logout user properly at the end of the scenario
  tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
Labels: QA:team

#8724 fix nooptions select option
  changelog/unreleased/bugfix-dropdown-nooptions-height
  packages/design-system/src/components/OcSelect/OcSelect.vue
Labels: Status:Needs-Review

#8711 FilterItem filter: Add label and make label and placeholder customizable
  changelog/unreleased/enhancement-itemfilter-add-customizable-label-and-placeholder
  packages/web-app-admin-settings/src/views/Users.vue
  packages/web-pkg/src/components/ItemFilter.vue
  packages/web-pkg/tests/unit/components/ItemFilter.spec.ts
Labels: Status:Needs-Review

#8760 [tests-only][full-ci]Bump commit id for tests
  .drone.env
Labels: QA:team
