Repository owncloud/web, pull requests merged in 2023-06, with the labels that each got.

#9126 [tests-only][full-ci]Refactor Share-role name in feature file according to webUI
  tests/e2e/cucumber/features/journeys/kindergarten.oc10.feature
  tests/e2e/cucumber/features/journeys/kindergarten.ocis.feature
  tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
  tests/e2e/cucumber/features/smoke/internalLink.ocis.feature
  tests/e2e/cucumber/features/smoke/link.feature
  tests/e2e/cucumber/features/smoke/notifications.oc10.feature
  tests/e2e/cucumber/features/smoke/notifications.ocis.feature
  tests/e2e/cucumber/features/smoke/reshare.feature
  tests/e2e/cucumber/features/smoke/search.feature
  tests/e2e/cucumber/features/smoke/share.oc10.feature
  tests/e2e/cucumber/features/smoke/share.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/internalLink.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/memberExpiry.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature
  tests/e2e/cucumber/features/smoke/tags.ocis.feature
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/support/api/share/share.ts
  tests/e2e/support/objects/app-files/link/actions.ts
  tests/e2e/support/objects/app-files/link/index.ts
  tests/e2e/support/objects/app-files/share/collaborator.ts
Labels: QA:team

#9149 [tests-only] Split ocis e2e tests pipeline
  .drone.star
Labels: QA:team

#9156 [tests-only] Split ocis e2e tests into smoke and spaces (#9149)
  .drone.star
Labels: QA:team

#9132 [tests-only][full-ci]Added e2e test admin manage space created by other space admin
  tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
Labels: QA:team

#9170 [tests-only][full-ci]Backport admin manage space
  tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
Labels: QA:team

#9163 [ci] Update plugins/docker image to 20.14
  .drone.star
Labels: QA:team

#9154 [full-ci] [tests-only] Refactored steps order
  tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature
Labels: QA:team

#9185 [full-ci] [tests-only] Refactor steps order
  tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature
  tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature
Labels: QA:team

#9175 [ci] update docker image
  .drone.star
Labels: QA:team

#9171 [tests-only][full-ci]Bump latest ocis commit on web
  .drone.env
Labels: QA:team

#9172 [tests-only][full-ci]Bump latest ocis commit on web `stable-7.0`
  .drone.env
Labels: QA:team

#9190 [tests-only][full-ci]Uncomment steps for resume upload and fix test code
  tests/e2e/cucumber/features/smoke/uploadResumable.ocis.feature
  tests/e2e/support/objects/app-files/resource/actions.ts
Labels: QA:team

#9176 [tests-only][full-ci]Add e2e tests for space download
  tests/e2e/cucumber/features/smoke/spaces/downloadSpace.ocis.feature
  tests/e2e/cucumber/steps/ui/accountMenu.ts
  tests/e2e/cucumber/steps/ui/spaces.ts
  tests/e2e/support/objects/account/actions.ts
  tests/e2e/support/objects/account/index.ts
  tests/e2e/support/objects/app-files/spaces/actions.ts
  tests/e2e/support/objects/app-files/spaces/index.ts
Labels: QA:team

#9252 [tests-only][full-ci]Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#9116 [tests-only] Make proper use of Promise.all
  tests/e2e/support/objects/app-admin-settings/groups/actions.ts
  tests/e2e/support/objects/app-admin-settings/users/actions.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/share/actions.ts
  tests/e2e/support/objects/app-files/share/collaborator.ts
  tests/e2e/support/objects/app-files/spaces/actions.ts
  tests/e2e/support/objects/runtime/application.ts
Labels: QA:team

#9253 [tests-only][full-ci]Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#9272 [tests-only] Make proper use of Promise.all (#9116)
  tests/e2e/support/objects/app-admin-settings/groups/actions.ts
  tests/e2e/support/objects/app-admin-settings/users/actions.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/share/actions.ts
  tests/e2e/support/objects/app-files/share/collaborator.ts
  tests/e2e/support/objects/app-files/spaces/actions.ts
  tests/e2e/support/objects/runtime/application.ts
Labels: QA:team

#9276 [tests-only][full-ci]Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#9286 [tests-only][full-ci]Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#9287 [tests-only][full-ci]Bump commit id for tests
  .drone.env
Labels: QA:team

#9292 [tests-only][full-ci]Uncomment steps for pause and resume upload
  tests/e2e/cucumber/features/smoke/uploadResumable.ocis.feature
  tests/e2e/support/objects/app-files/resource/actions.ts
Labels: QA:team

#9297 [docs-only] Update getting-started.md
  docs/getting-started.md
Labels: Topic:Documentation

#9238 [full-ci] [tests-only] [E2E] full text search tests added
  .drone.star
  docker-compose.yml
  tests/e2e/cucumber/features/smoke/fullTextSearch.ocis.feature
  tests/e2e/cucumber/steps/ui/search.ts
  tests/e2e/support/objects/app-files/index.ts
  tests/e2e/support/objects/app-files/search/actions.ts
  tests/e2e/support/objects/app-files/search/index.ts
Labels: QA:team

#9305 [tests-only][full-ci] Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#9306 [tests-only][full-ci] Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#9316 [tests-only][full-ci]Fix e2e flaky tests for searching
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/search/actions.ts
Labels: QA:team

#9320 "Shared with me" view: switch columns displayed on small screens
  packages/design-system/changelog/unreleased/bugfix-switch-columns-shared-with-me-view
  packages/web-app-files/src/components/FilesList/ResourceTable.vue
Labels: Status:Needs-Review, Category:Change
