Repository owncloud/web, pull requests merged in 2023-10, with the labels that each got.

#9761 [tests-only][full-ci] Remove scenario which tries to update web config File
  tests/acceptance/features/webUIFiles/breadcrumb.feature
  tests/acceptance/stepDefinitions/generalContext.js
Labels: QA:team

#9759 [full-ci] [tests-only] Bump ocis stable commit id to latest
  .drone.env
Labels: QA:team

#9758 [tests-only] [full-ci] adding e2e test for opening a public link for shared file by authenticated user
  tests/e2e/cucumber/features/smoke/link.feature
  tests/e2e/cucumber/steps/ui/public.ts
  tests/e2e/support/objects/app-files/link/actions.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: QA:team

#9740 [tests-only][full-ci]bump latest commit id
  .drone.env
  .drone.star
  tests/drone/identifier-registration.yml
Labels: QA:team

#9760 [tests-only][full-ci] adding e2e test for opening a public link of files inside the project space in authenticated context
  tests/e2e/cucumber/features/smoke/spaces/publicLink.feature
Labels: QA:team

#9774 [tests-only] [full-ci] bump latest stable commit id of ocis
  .drone.env
Labels: QA:team

#9772 [tests-only] [full-ci] bump latest commit ocis id master
  .drone.env
Labels: QA:team

#9777 [tests-only][full-ci] adding e2e test for opening a public link of files inside the project space in authenticated context
  tests/e2e/cucumber/features/smoke/spaces/publicLink.feature
Labels: QA:team

#9801 [tests-only][full-ci]bump latest commit id
  .drone.env
Labels: QA:team

#9803 [tests-only][full-ci] bump latest commit id
  .drone.env
Labels: QA:team

#9798 [tests-only][full-ci] added e2e test for adding banned password for public link
  .drone.star
  tests/drone/banned-passwords.txt
  tests/e2e/cucumber/features/smoke/spaces/publicLink.feature
  tests/e2e/cucumber/steps/ui/links.ts
  tests/e2e/support/objects/app-files/link/actions.ts
  tests/e2e/support/objects/app-files/link/index.ts
Labels: QA:team

#9813 [tests-only] bump ocis commit-id
  .drone.env
Labels: QA:team

#9826 [tests-only][full-ci] Bump ocis commit-id
  .drone.env
Labels: QA:team

#9830 [tests-only][full-ci] Bump ocis commit id for tests
  .drone.env
Labels: QA:team

#9820 [tests-only][full-ci]added e2e test for show password, copy password and generate password buttons
  tests/e2e/cucumber/features/smoke/spaces/publicLink.feature
  tests/e2e/cucumber/steps/ui/links.ts
  tests/e2e/cucumber/steps/ui/public.ts
  tests/e2e/support/objects/app-files/link/actions.ts
  tests/e2e/support/objects/app-files/link/index.ts
Labels: QA:team

#9844 fix: space image upload
  changelog/unreleased/bugfix-space-image
  packages/web-app-files/src/composables/actions/spaces/useSpaceActionsUploadImage.ts
  packages/web-app-files/tests/unit/composables/actions/spaces/useSpaceActionsUploadImage.spec.ts
  tests/e2e/support/objects/app-files/spaces/actions.ts
Labels: Type:Bug, Status:Needs-Review

#9861 fix: duplicated file search request
  changelog/unreleased/bugfix-duplicated-file-search-request
  packages/web-app-files/src/components/Search/List.vue
Labels: Status:Needs-Review

#9874 [full-ci][tests-only] bump ocis commit id
  .drone.env
Labels: QA:team

#9875 [tests-only][full-ci] bump ocis commit-id
  .drone.env
Labels: QA:team

#9854 enhancement: search query term linking
  changelog/unreleased/enhancement-search-term-linking
  packages/web-app-files/src/components/Search/List.vue
  packages/web-app-files/tests/unit/components/Search/List.spec.ts
Labels: Category:Enhancement, Status:Needs-Review, Estimation:S(2), feature:files, Category:Change

#9880 chore: change to the search query triggers only one request
  changelog/unreleased/bugfix-duplicated-file-search-request
  packages/web-app-files/tests/unit/components/Search/List.spec.ts
Labels: Status:Needs-Review, Type:CI

#9881 fix: rendering of old/wrong set of resources in search list
  changelog/unreleased/bugfix-search-list-result-rendering
  packages/web-app-files/src/components/Search/List.vue
  packages/web-app-files/tests/unit/components/Search/List.spec.ts
  packages/web-app-search/src/views/List.vue
  packages/web-app-search/tests/unit/views/List.spec.ts
Labels: Type:Bug, Status:Needs-Review
