Repository owncloud/web, pull requests merged in 2024-01, with the labels that each got.

#10254 [full-ci] [tests-only] Bump ocis commit id to latest
  .drone.env
Labels: QA:team

#10255 [full-ci] [tests-only] Bump ocis commit id to stable 5.0
  .drone.env
Labels: QA:team

#10311 [full-ci] [tests-only] Bump ocis commit id to latest
  .drone.env
  .drone.star
Labels: QA:team

#10314 [full-ci] [tests-only] Bump ocis commit-id to include fix for ocis build pipeline
  .drone.env
Labels: QA:team

#10326 refactor: remove left sidebar nav state from vuex store
  packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
  packages/web-runtime/src/layouts/Application.vue
  packages/web-runtime/src/store/navigation.ts
  packages/web-runtime/tests/unit/components/SidebarNav/SidebarNav.spec.ts
  packages/web-test-helpers/src/mocks/store/defaultStoreMockOptions.ts
Labels: Status:Needs-Review

#10329 refactor: register nav items via extension registry
  packages/web-runtime/src/components/Topbar/TopBar.vue
  packages/web-runtime/src/container/api.ts
  packages/web-runtime/src/container/application/classic.ts
  packages/web-runtime/src/container/bootstrap.ts
  packages/web-runtime/src/helpers/navItems.ts
  packages/web-runtime/src/index.ts
  packages/web-runtime/src/layouts/Application.vue
  packages/web-runtime/src/store/index.ts
  packages/web-runtime/src/store/navigation.ts
  packages/web-test-helpers/src/mocks/store/defaultStoreMockOptions.ts
Labels: Status:Needs-Review

#10310 Release 8.0.0 rc.2
  package.json
  packages/web-app-admin-settings/l10n/translations.json
  packages/web-app-files/l10n/translations.json
  packages/web-pkg/l10n/translations.json
  packages/web-runtime/l10n/translations.json
  sonar-project.properties
Labels: Status:Needs-Review

#10355 [tests-only][ci][port] split e2e test suites
  .drone.star
  tests/e2e/cucumber/features/smoke/search/fullTextSearch.feature
  tests/e2e/cucumber/features/smoke/search/search.feature
  tests/e2e/cucumber/features/smoke/search/searchProjectSpace.feature
  tests/e2e/cucumber/features/smoke/shares/denyShareAccess.feature
  tests/e2e/cucumber/features/smoke/shares/internalLink.feature
  tests/e2e/cucumber/features/smoke/shares/link.feature
  tests/e2e/cucumber/features/smoke/shares/reshare.feature
  tests/e2e/cucumber/features/smoke/shares/share.feature
Labels: QA:team

#10243 chore: migrate design system docs to Vue 3
  package.json
  packages/design-system/build/build-tokens.js
  packages/design-system/build/build-tokens/transform-namespace.js
  packages/design-system/build/utils.js
  packages/design-system/build/webpack.base.conf.js
  packages/design-system/changelog/unreleased/bugfix-docs-build
  packages/design-system/config/docs.config.js
  packages/design-system/docs/components.md
  packages/design-system/docs/components/Preview.js
  packages/design-system/docs/components/tokens/AllTokens.spec.js
  packages/design-system/docs/components/tokens/ColorTokens.spec.js
  packages/design-system/docs/components/tokens/FontSize.spec.js
  packages/design-system/docs/components/tokens/SpacingTokens.spec.js
  packages/design-system/docs/docs.helper.js
  packages/design-system/docs/docs.spacing.scss
  packages/design-system/docs/docs.styles.scss
  packages/design-system/docs/getting-started.md
  packages/design-system/docs/icons.md
  packages/design-system/docs/tokens.md
  packages/design-system/package.json
  packages/design-system/src/components/OcApplicationIcon/OcApplicationIcon.vue
  packages/design-system/src/components/OcAvatars/__snapshots__/OcAvatars.spec.ts.snap
  packages/design-system/src/components/OcModal/OcModal.vue
  packages/design-system/src/components/OcSearchBar/OcSearchBar.vue
  packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
  packages/design-system/src/components/_DocsAllTokens/_DocsAllTokens.vue
  packages/design-system/src/components/_DocsColorTokens/_DocsColorTokens.vue
  packages/design-system/src/components/_DocsComponentsList/_DocsComponentsList.vue
  packages/design-system/src/components/_DocsFontSize/_DocsFontSize.vue
  packages/design-system/src/components/_DocsHighlightedText/_DocsHighlightedText.vue
  packages/design-system/src/components/_DocsSpacingTokens/_DocsSpacingTokens.vue
  packages/design-system/src/components/_docsIconList/_DocsIconList.vue
  packages/extension-sdk/package.json
  packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
  packages/web-app-files/tests/unit/components/AppBar/Upload/__snapshots__/ResourceUpload.spec.ts.snap
  packages/web-app-files/tests/unit/components/AppBar/__snapshots__/CreateAndUpload.spec.ts.snap
  packages/web-app-files/tests/unit/components/AppBar/__snapshots__/CreateSpace.spec.ts.snap
  packages/web-app-files/tests/unit/components/AppBar/__snapshots__/SharesNavigation.spec.ts.snap
  packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ResourceDetails.spec.ts.snap
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/__snapshots__/RecipientContainer.spec.ts.snap
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/RoleDropdown.spec.ts.snap
  packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/NameAndCopy.spec.ts.snap
  packages/web-app-files/tests/unit/components/SideBar/__snapshots__/PrivateLinkItem.spec.ts.snap
  packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap
  packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
  packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ContextMenuQuickAction.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceIcon.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceListItem.spec.ts.snap
  packages/web-pkg/tests/unit/components/__snapshots__/AppTopBar.spec.ts.snap
  packages/web-pkg/tests/unit/components/__snapshots__/ItemFilter.spec.ts.snap
  packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNav.spec.ts.snap
  packages/web-runtime/tests/unit/components/Topbar/__snapshots__/SidebarToggle.spec.ts.snap
  packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.ts.snap
  pnpm-lock.yaml
Labels: Topic:Dependencies, Status:In-Progress, Topic:Documentation

#10360 [tests-only][full-ci]update compose make image versions consistent in CI and compose
  .drone.star
  docker-compose.yml
Labels: QA:team

#10364 [tests-only][full-ci]update compose make image versions consistent in CI and compose
  .drone.star
  docker-compose.yml
Labels: QA:team

#10365 [full-ci] [tests-only] Bump ocis commit id
  .drone.env
Labels: QA:team

#10352 [docs-only] update documentation of visibility classes
  packages/design-system/docs/visibility.md
Labels: Topic:Documentation, Category:Nonfunctional, Status:Needs-Revision

#10367 [full-ci] [tests-only] Bump ocis stable-4.0 commit id
  .drone.env
Labels: QA:team

#10366 [full-ci] [tests-only] Bump ocis stable-5.0 commit id
  .drone.env
  .drone.star
Labels: QA:team

#10379 [full-ci] [tests-only] Bump ocis stable 5.0 commit
  .drone.env
Labels: QA:team

#10374 [tests-only] test: add design system docs tests
  .drone.star
  .gitignore
  packages/design-system/docs/components/Preview.js
  packages/design-system/docs/utils/tabs.js
  packages/design-system/package.json
  packages/design-system/src/components/_DocsComponentsList/_DocsComponentsList.vue
  packages/design-system/tests/e2e/playwright.config.ts
  packages/design-system/tests/e2e/specs/component-example.spec.ts
  packages/design-system/tests/e2e/specs/components-list.spec.ts
  tests/unit/config/jest.config.ts
Labels: Status:Needs-Review, Type:CI, Category:Technical

#10172 icon and color definitions for dicom-viewer .dcm filetype
  changelog/unreleased/enhancement-medical-icon
  packages/design-system/src/assets/icons/resource-type-medical-fill.svg
  packages/design-system/src/tokens/ods/color.yaml
  packages/web-runtime/themes/owncloud/theme.json
Labels: Category:Enhancement, Status:Needs-Review, Topic:UX-Design, Category:Nonfunctional

#10409 [full-ci] [tests-only] Bump ocis commit id
  .drone.env
Labels: QA:team

#10410 [full-ci] [tests-only] Bump ocis stable-5.0 commit id
  .drone.env
Labels: QA:team

#10416 [tests-only][full-ci] Remove acceptance tests skipped in ocis
  .drone.star
  tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
  tests/acceptance/features/webUIFilesActionMenu/fileFolderActionMenu.feature
  tests/acceptance/features/webUIFilesActionMenu/versions.feature
  tests/acceptance/features/webUIFilesCopy/copy.feature
  tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature
  tests/acceptance/features/webUIResharing1/reshareUsers.feature
  tests/acceptance/features/webUIResharing2/reshareUsers.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
  tests/acceptance/features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
  tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
  tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
  tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
  tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
  tests/acceptance/features/webUISharingPublicManagement/publicLinkIndicator.feature
  tests/acceptance/features/webUITrashbinFilesFolders/trashbinFilesFolders.feature
  tests/acceptance/package.json
Labels: QA:team
