Repository owncloud/web, pull requests merged in 2024-06, with the labels that each got.

#10998 fix: viewer light role permission loading
  packages/web-runtime/src/index.ts
Labels: Type:Bug, Status:Needs-Review

#11005 [tests-only][full-ci] bump ocis commit id - master
  .drone.env
Labels: QA:team

#10389 chore: replace easygettext with scripts from vue3 gettext
  gettext.config.cjs
  packages/design-system/docs/i18n.md
  packages/design-system/l10n/.tx/config
  packages/design-system/src/components/OcEmojiPicker/OcEmojiPicker.vue
  packages/web-app-admin-settings/l10n/.tx/config
  packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
  packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
  packages/web-app-draw-io/l10n/.tx/config
  packages/web-app-external/l10n/.tx/config
  packages/web-app-external/src/App.vue
  packages/web-app-files/l10n/.tx/config
  packages/web-app-files/src/components/EmbedActions/EmbedActions.vue
  packages/web-app-files/src/components/SideBar/Exif/ExifPanel.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
  packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
  packages/web-app-files/src/views/spaces/Projects.vue
  packages/web-app-importer/l10n/.tx/config
  packages/web-app-ocm/l10n/.tx/config
  packages/web-app-pdf-viewer/l10n/.tx/config
  packages/web-app-preview/l10n/.tx/config
  packages/web-app-search/l10n/.tx/config
  packages/web-app-text-editor/l10n/.tx/config
  packages/web-app-webfinger/l10n/.tx/config
  packages/web-client/l10n/.tx/config
  packages/web-pkg/l10n/.tx/config
  packages/web-pkg/src/components/CreateLinkModal.vue
  packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetailsMultiple.vue
  packages/web-pkg/src/components/TextEditor.vue
  packages/web-pkg/src/composables/links/useExpirationRules.ts
  packages/web-pkg/src/composables/requestHeaders/useRequestHeaders.ts
  packages/web-runtime/l10n/.tx/config
  packages/web-runtime/l10n/Makefile
  packages/web-runtime/package.json
  packages/web-runtime/src/components/Account/GdprExport.vue
  packages/web-runtime/src/components/Topbar/Notifications.vue
  packages/web-runtime/src/container/sse/files.ts
  packages/web-runtime/src/container/sse/shares.ts
  pnpm-lock.yaml
Labels: Status:Needs-Review, Category:Technical

#11027 [tests-only][ci] split e2e smoke tests into separate suites
  .drone.star
  tests/e2e/cucumber/features/file-action/copyMove.feature
  tests/e2e/cucumber/features/file-action/download.feature
  tests/e2e/cucumber/features/file-action/groupActions.feature
  tests/e2e/cucumber/features/file-action/rename.feature
  tests/e2e/cucumber/features/navigation/applicationMenu.feature
  tests/e2e/cucumber/features/navigation/breadcrumb.feature
  tests/e2e/cucumber/features/navigation/personalSpacePagination.feature
  tests/e2e/cucumber/features/navigation/shortcut.feature
  tests/e2e/cucumber/features/navigation/urlJourneys.feature
  tests/e2e/cucumber/features/spaces/createSpaceFromSelection.feature
  tests/e2e/cucumber/features/user-settings/gdprExport.feature
  tests/e2e/cucumber/features/user-settings/languageChange.feature
  tests/e2e/cucumber/features/user-settings/notifications.feature
  tests/e2e/cucumber/features/user-settings/tiles.feature
Labels: QA:team

#11023 [full-ci][tests-only] fix flaky onlyoffice test scenario
  .drone.env
  tests/e2e/cucumber/features/app-provider/officeSuites.feature
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/share/collaborator.ts
  tests/e2e/support/objects/app-files/utils/sidebar.ts
Labels: QA:team

#11043 [tests-only][full-ci] bump ocis commit id - master
  .drone.env
Labels: QA:team

#11015 [full-ci][tests-only]Trigger tracing step pipeline when e2e tests run on CI
  .drone.star
Labels: QA:team

#11044 [tests-only][full-ci] bump ocis commit id - stable
  .drone.env
Labels: QA:team

#11003 [tests-only][full-ci]: use graph endpoint to do the share in API steps
  tests/e2e/cucumber/features/admin-settings/spaces.feature
  tests/e2e/cucumber/features/file-action/download.feature
  tests/e2e/cucumber/features/file-action/groupActions.feature
  tests/e2e/cucumber/features/smoke/sse.feature
  tests/e2e/cucumber/features/spaces/internalLink.feature
  tests/e2e/cucumber/features/spaces/publicLink.feature
  tests/e2e/cucumber/steps/api.ts
  tests/e2e/support/api/davSpaces/index.ts
  tests/e2e/support/api/davSpaces/spaces.ts
  tests/e2e/support/api/graph/index.ts
  tests/e2e/support/api/graph/spaces.ts
  tests/e2e/support/api/share/index.ts
  tests/e2e/support/api/share/share.ts
  tests/e2e/support/types.ts
Labels: QA:team

#10895 [tests-only] [full-ci] Restructure e2e tests data storage for keycloak
  .drone.star
  tests/e2e/cucumber/environment/index.ts
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/support/api/graph/userManagement.ts
  tests/e2e/support/api/keycloak/user.ts
  tests/e2e/support/api/provision/user.ts
  tests/e2e/support/environment/userManagement.ts
  tests/e2e/support/objects/app-admin-settings/users/index.ts
  tests/e2e/support/store/index.ts
  tests/e2e/support/store/keycloak.ts
Labels: QA:team

#11066 [tests-only][full-ci] wait for transition to end before picking a date
  tests/e2e/support/objects/app-files/share/actions.ts
  tests/e2e/support/objects/app-files/share/collaborator.ts
Labels: QA:team

#11071 chore: use ocis-rolling docker image for development
  docker-compose.yml
Labels: QA:team

#11070 [tests-only][full-ci] properly close the sse connections
  tests/e2e/cucumber/environment/index.ts
  tests/e2e/support/environment/sse.ts
Labels: QA:team

#11067 [full-ci][tests-only] regenerate the access token for web-ocis while running with keycloak
  .drone.star
  tests/e2e/cucumber/environment/index.ts
Labels: QA:team

#11081 [tests-only][full-ci] Bump latest commit id
  .drone.env
Labels: QA:team

#11082 [tests-only][full-ci] Bump latest commit id
  .drone.env
Labels: QA:team

#11104 [tests-only][full-ci] wait until the GDPR report is ready for download
  .drone.env
  tests/e2e/support/objects/account/actions.ts
Labels: QA:team

#11110 [tests-only][full-ci] bump ocis commit id-stable5.0
  .drone.env
Labels: QA:team
