Repository owncloud/web, pull requests merged in 2024-12, with the labels that each got.

#11958 [tests-only][full-ci]Cache playwright chromium
  .drone.star
  tests/drone/script.sh
Labels: QA:team

#11998 fix: do not load version when sidebar is closed
  changelog/unreleased/bugfix-do-not-load-versions-when-sidebar-is-closed
  packages/web-pkg/src/components/SideBar/FileSideBar.vue
  packages/web-pkg/tests/unit/components/sidebar/FileSideBar.spec.ts
Labels: Type:Bug

#12000 fix: pass only space as space prop to sidebar
  changelog/unreleased/bugfix-use-only-space-as-space-into-sidebar
  packages/web-app-files/src/views/spaces/Projects.vue
  packages/web-app-files/tests/unit/views/spaces/Projects.spec.ts
Labels: Type:Bug

#12020 [full-ci][tests-only] Adjust federated share step based on current behavior
  tests/e2e/support/objects/federation/actions.ts
Labels: QA:team

#12032 [tests-only][full-ci] Bump ocis master latest commit id
  .drone.env
Labels: QA:team

#12033 [tests-only][full-ci] Bump ocis master latest commit id
  .drone.env
Labels: QA:team

#12038 [tests-only][full-ci] Bump ocis latest commit id
  .drone.env
Labels: QA:team

#12010 feat: add notifications settings
  changelog/unreleased/enhancement-add-notifications-settings
  packages/web-client/src/ocs/capabilities.ts
  packages/web-runtime/src/components/Account/AccountTable.vue
  packages/web-runtime/src/composables/notificationsSettings/index.ts
  packages/web-runtime/src/composables/notificationsSettings/useNotificationsSettings.ts
  packages/web-runtime/src/helpers/settings.ts
  packages/web-runtime/src/pages/account.vue
  packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
  packages/web-runtime/tests/unit/pages/account.spec.ts
Labels: Category:Enhancement

#12049 [tests-only][full-ci]Bump ocis master commit id
  .drone.env
Labels: QA:team

#12048 [tests-only][full-ci]Bump stable7.0 ocis commit id on web stable11.0
  .drone.env
Labels: QA:team

#12046 feat: add delete queue
  changelog/unreleased/enhancement-disable-resources-in-delete-queue.md
  packages/web-pkg/src/components/FilesList/ResourceTable.vue
  packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
  packages/web-pkg/src/composables/piniaStores/resources.ts
  packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
  packages/web-pkg/tests/unit/composables/actions/helpers/useFileActionsDeleteResources.spec.ts
  packages/web-test-helpers/src/mocks/pinia.ts
Labels: Category:Enhancement

#12044 fix: disable paste button in same folder
  changelog/unreleased/bugfix-disable-paste-action-in-same-folder.md
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
Labels: Type:Bug

#12045 fix: handle sidebar resizing
  changelog/unreleased/bugfix-do-not-push-sidebar-close-action-away.md
  changelog/unreleased/bugfix-update-sidebar-width-on-resize.md
  changelog/unreleased/bugfix-use-correct-breakpoints-in-sidebar.md
  packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
  packages/web-pkg/src/components/SideBar/SideBar.vue
Labels: Type:Bug

#12050 fix: show indirect shares in search results
  changelog/unreleased/bugfix-show-indirect-shares-on-search-page.md
  packages/web-pkg/src/components/SideBar/FileSideBar.vue
  packages/web-pkg/tests/unit/components/sidebar/FileSideBar.spec.ts
Labels: Type:Bug

#12054 feat: use more generic private link error message
  changelog/unreleased/enhancement-use-generic-private-link-error.md
  packages/web-runtime/src/pages/resolvePrivateLink.vue
Labels: Category:Enhancement

#12056 [tests-only][full-ci] bump latest ocis master commit id
  .drone.env
Labels: QA:team

#12057 [tests-only][full-ci] bump ocis stable 7.0 commit
  .drone.env
Labels: QA:team

#12052 refactor: switch to upstream uppy
  package.json
  packages/web-app-files/package.json
  packages/web-app-files/src/HandleUpload.ts
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/src/helpers/resource/actions/upload.ts
  packages/web-app-files/tests/unit/HandleUpload.spec.ts
  packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.ts
  packages/web-app-files/tests/unit/helpers/resource/actions/upload.spec.ts
  packages/web-pkg/package.json
  packages/web-pkg/src/composables/upload/useUpload.ts
  packages/web-pkg/src/services/uppy/index.ts
  packages/web-pkg/src/services/uppy/types.ts
  packages/web-pkg/src/services/uppy/uppyService.ts
  packages/web-runtime/package.json
  packages/web-runtime/src/components/UploadInfo.vue
  packages/web-runtime/tests/unit/components/UploadInfo.spec.ts
  pnpm-lock.yaml
Labels: Topic:Dependencies

#12059 fix: reload sidebar preloaded resource
  changelog/unreleased/bugfix-reload-preloaded-resource-in-sidebar.md
  packages/web-pkg/src/components/FilesList/ResourceTable.vue
  packages/web-pkg/src/components/SideBar/FileSideBar.vue
  packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
Labels: Type:Bug

#12063 fix: lower disabled checkbox opacity
  changelog/unreleased/bugfix-change-opacity-of-disabled-checkboxes.md
  packages/design-system/src/components/OcCheckbox/OcCheckbox.vue
Labels: Type:Bug
