Repository owncloud/web, pull requests merged in 2025-02, with the labels that each got.

#12145 feat(password-protected-folders): hide extension and actions
  changelog/unreleased/enhancement-display-default-actions-in-context-menu.md
  changelog/unreleased/enhancement-hide-password-protected-folders-actions.md
  changelog/unreleased/enhancement-hide-password-protected-folders-extension.md
  packages/web-app-password-protected-folders/src/composables/useExtensions.ts
  packages/web-client/package.json
  packages/web-client/src/helpers/resource/functions.ts
  packages/web-client/tests/unit/helpers/resource/functions.spec.ts
  packages/web-pkg/src/components/FilesList/ContextActions.vue
  packages/web-pkg/src/components/FilesList/ResourceListItem.vue
  packages/web-pkg/src/components/SideBar/Files/FileInfo.vue
  packages/web-pkg/src/composables/actions/files/useFileActions.ts
  packages/web-pkg/src/composables/actions/files/useFileActionsCreateSpaceFromResource.ts
  packages/web-pkg/src/constants.ts
  packages/web-pkg/tests/unit/components/FilesList/ResourceListItem.spec.ts
  pnpm-lock.yaml
Labels: Category:Enhancement

#12148 [tests-only][full-ci] test: bump latest ocis master commit id
  .drone.env
Labels: QA:team

#12147 [tests-only][full-ci] test: bump latest ocis master commit id
  .drone.env
Labels: QA:team

#12156 feat: replace toustui editor with md editor
  .npmrc
  changelog/unreleased/bugfix-replace-text-editor.md
  package.json
  packages/web-app-files/src/components/Spaces/SpaceHeader.vue
  packages/web-pkg/package.json
  packages/web-pkg/src/components/TextEditor/TextEditor.vue
  packages/web-pkg/src/components/TextEditor/l18n.ts
  pnpm-lock.yaml
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/spaces/actions.ts
Labels: Type:Bug

#12172 [tests-only][full-ci] test: bump latest ocis stable7.0 commit id in stable 11.0
  .drone.env
Labels: QA:team

#12152 feat(password-protected-folders): delete protected folder
  changelog/unreleased/enhancement-delete-password-protected-folders.md
  packages/web-app-password-protected-folders/src/index.ts
  packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
  packages/web-pkg/src/composables/webWorkers/deleteWorker/worker.ts
  packages/web-pkg/src/constants.ts
  packages/web-pkg/tests/unit/composables/actions/helpers/useFileActionsDeleteResources.spec.ts
Labels: Category:Enhancement

#12175 fix: do not render default actions in context menu
  changelog/unreleased/bugfix-do-not-render-default-actions-in-context-menu.md
  packages/web-app-password-protected-folders/src/composables/useExtensions.ts
  packages/web-app-password-protected-folders/src/composables/useOpenFolderAction.ts
  packages/web-pkg/src/components/FilesList/ContextActions.vue
Labels: Type:Bug

#12146 fix(password-protected-folders): create folder in the personal space
  changelog/unreleased/bugfix-create-password-protected-folder-in-personal-space.md
  changelog/unreleased/enhancement-recursive-folder-creation.md
  packages/web-app-password-protected-folders/src/components/CreateFolderModal.vue
  packages/web-app-password-protected-folders/src/composables/useCreateFileHandler.ts
  packages/web-app-password-protected-folders/tests/unit/components/CreateFolderModal.spec.ts
  packages/web-app-password-protected-folders/tests/unit/composables/useCreateFileHandler.spec.ts
  packages/web-client/src/webdav/createFolder.ts
  packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
Labels: Type:Bug

#12171 [tests-only][full-ci] test: bump latest ocis master commit id
  .drone.env
Labels: QA:team

#12177 fix: open password protected folder when clicking its name
  changelog/unreleased/bugfix-open-password-protected-folder-when-clicking-on-its-name.md
  packages/web-client/src/helpers/resource/functions.ts
  packages/web-pkg/src/components/FilesList/ResourceTable.vue
  packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
Labels: Type:Bug

#12179 fix(files): check files view presence in upload dropzone init
  changelog/unreleased/bugfix-skip-upload-dropzone-init-when-files-view-is-missing.md
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.ts
Labels: Type:Bug

#12188 feat(external): allow camera
  changelog/unreleased/enhancement-allow-camera-in-external-app-iframe.md
  packages/web-app-external/src/App.vue
  packages/web-app-external/tests/unit/__snapshots__/app.spec.ts.snap
Labels: Category:Enhancement

#12202 [tests-only][full-ci] test: bump ocis commit id
  .drone.env
Labels: QA:team

#12203 [tests-only][full-ci] test: bump ocis stable-7.0 commit id
  .drone.env
Labels: QA:team

#12200 deps: bump pnpm to 10.4.1
  package.json
  pnpm-lock.yaml
Labels: Topic:Dependencies

#12205 fix(pkg): prevent move of psec files
  changelog/unreleased/bugfix-prevent-password-protected-folder-move.md
  packages/web-pkg/src/helpers/permissions.ts
  packages/web-pkg/tests/unit/composables/actions/files/useFileActionsMove.spec.ts
  packages/web-pkg/tests/unit/helpers/permissions.spec.ts
Labels: Type:Bug

#12206 fix: preserve language in password protected folders
  changelog/unreleased/bugfix-preserve-current-language-in-password-protected-folder-view.md
  changelog/unreleased/enhancement-add-lang-url-query-parameter.md
  packages/web-app-password-protected-folders/src/components/FolderViewModal.vue
  packages/web-app-password-protected-folders/tests/unit/components/FolderViewModal.spec.ts
  packages/web-pkg/src/composables/piniaStores/config/types.ts
  packages/web-runtime/src/container/bootstrap.ts
  packages/web-runtime/src/index.ts
  packages/web-runtime/tests/unit/container/bootstrap.spec.ts
Labels: Type:Bug

#12194 fix: display shared file versions
  changelog/unreleased/bugfix-display-shared-file-versions.md
  packages/web-client/src/helpers/share/functions.ts
  packages/web-client/src/helpers/share/types.ts
  packages/web-pkg/src/composables/resources/useCanListVersions.ts
  packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
  packages/web-pkg/tests/unit/composables/resources/useCanListVersions.spec.ts
Labels: Type:Bug

#12189 [tests-only][full-ci] added test for disabling notifications
  .drone.star
  docker-compose.yml
  docs/testing/testing.md
  tests/e2e/cucumber/features/user-settings/notifications.feature
  tests/e2e/cucumber/steps/ui/accountMenu.ts
  tests/e2e/support/objects/account/actions.ts
  tests/e2e/support/objects/account/index.ts
Labels: QA:team

#12192 [tests-only][full-ci] added test for password protected folder
  tests/drone/config-ocis.json
  tests/e2e/cucumber/features/file-action/passswordProtectedFolder.feature
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
Labels: QA:team

#12221 [tests-only][full-ci] bump ocis commit id
  .drone.env
Labels: QA:team

#12222 [tests-only][full-ci] bump ocis stable-7.0 commit id
  .drone.env
Labels: QA:team

#12211 [tests-only][full-ci] retry logon until timeout if the server responds with 502
  tests/e2e/cucumber/environment/index.ts
  tests/e2e/cucumber/features/admin-settings/users.feature
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/support/api/graph/userManagement.ts
  tests/e2e/support/api/keycloak/user.ts
  tests/e2e/support/api/token/index.ts
  tests/e2e/support/api/token/utils.ts
Labels: QA:team

#12226 fix: disable psec creation in public links
  changelog/unreleased/bugfix-disable-password-protected-folders-creation-inside-public-links.md
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/tests/unit/components/AppBar/__snapshots__/CreateAndUpload.spec.ts.snap
  packages/web-app-password-protected-folders/src/composables/useApplicationFileExtensions.ts
  packages/web-app-password-protected-folders/src/index.ts
  packages/web-app-password-protected-folders/tests/unit/composables/useApplicationFileExtensions.spec.ts
  packages/web-pkg/src/apps/types.ts
  packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewFile.ts
  packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateNewFile.spec.ts
Labels: Type:Bug

#12230 [tests-only][full-ci] bump ocis commit id
  .drone.env
Labels: QA:team

#12231 Update / fix the password protected folders readme
  packages/web-app-password-protected-folders/README.md
Labels: Topic:Documentation
