Repository owncloud/web, pull requests merged in 2025-08, with the labels that each got.

#12880 [tests-only][full-ci] Bump latest ocis commit id on stable-11.0 branch
  .drone.env
Labels: QA:team

#12954 fix(web-app-external): add clipboard permissions
  changelog/unreleased/bugfix-add-clipboard-permissions.md
  packages/web-app-external/src/App.vue
  packages/web-app-external/tests/unit/__snapshots__/app.spec.ts.snap
Labels: Type:Bug

#12973 feat: [OCISDEV-269] Add GeoGebra pinboard icon
  changelog/unreleased/enhancement-add-geogebra-pinboard-icon.md
  packages/design-system/src/assets/icons/resource-type-pinboard-beta-fill.svg
  packages/web-pkg/src/helpers/resource/icon.ts
Labels: Category:Enhancement

#12943 fix: [OCISDEV-147] sign public link archiver download URL
  changelog/unreleased/bugfix-sign-public-link-archiver-download-url.md
  packages/web-app-files/src/helpers/user/avatarUrl.ts
  packages/web-app-files/tests/unit/helpers/user/avatarUrl.spec.ts
  packages/web-client/src/ocs/index.ts
  packages/web-client/src/ocs/urlSign.ts
  packages/web-client/src/webdav/getFileUrl.ts
  packages/web-pkg/src/composables/actions/files/useFileActionsDownloadArchive.ts
  packages/web-pkg/src/services/archiver.ts
  packages/web-pkg/src/services/client/client.ts
  packages/web-pkg/tests/unit/services/archiver.spec.ts
  packages/web-runtime/src/index.ts
Labels: Type:Bug
