Repository owncloud/web, pull requests merged in 2025-01, with the labels that each got.

#12058 fix: use local state in sidebar in embed mode
  changelog/unreleased/bugfix-use-local-state-in-sidebar-in-embed-mode.md
  packages/web-pkg/src/composables/sideBar/useSideBar.ts
  packages/web-pkg/tests/unit/composables/sideBar/useSideBar.spec.ts
Labels: Type:Bug

#12072 [tests-only] [full-ci] bump ocis master commit id
  .drone.env
Labels: QA:team

#12074 fix: refetch settings bundle on locale change
  changelog/unreleased/bugfix-refetch-notifications-settings-on-locale-change.md
  packages/web-runtime/src/pages/account.vue
  packages/web-runtime/tests/unit/pages/account.spec.ts
Labels: Type:Bug

#12075 [tests-only][full-ci]Bump ocis to web
  .drone.env
Labels: QA:team

#12076 [tests-only][full-ci]Bump ocis stable to web stable
  .drone.env
Labels: QA:team

#12077 Update account.vue: fix gettext values
  packages/web-runtime/src/pages/account.vue
Labels: Topic:Documentation

#12081 deps(design-system): drop npm package
  packages/design-system/package.json
  pnpm-lock.yaml
Labels: Topic:Dependencies

#12092 [tests-only][full-ci]Bump latest ocis commit id
  .drone.env
Labels: QA:team

#12093 [tests-only][full-ci]Bump latest ocis stable-7.0 commit id
  .drone.env
Labels: QA:team

#12101 fix: add missing User Light role translations definition
  changelog/unreleased/bugfix-missing-user-light-translations.md
  packages/web-runtime/src/helpers/additionalTranslations.ts
Labels: Type:Bug

#12102 [tests-only][full-ci] Bump ocis commit id
  .drone.env
Labels: QA:team

#12107 [tests-only][full-ci]commit ocis master
  .drone.env
Labels: QA:team

#12104 feat: add psec file icon
  changelog/unreleased/enhancement-add-psec-file-icon.md
  packages/design-system/src/assets/icons/file-psec-fill.svg
  packages/web-pkg/src/helpers/resource/icon.ts
Labels: Category:Enhancement

#12112 fix(web-app-preview): optionally access route query
  changelog/unreleased/bugfix-optionally-access-preview-app-route-query.md
  packages/web-app-preview/src/App.vue
  packages/web-app-preview/tests/unit/app.spec.ts
Labels: Type:Bug

#12118 fix(design-system): use earth icon for federated shares
  changelog/unreleased/bugfix-change-federated-share-icon.md
  changelog/unreleased/bugfix-improve-federated-share-icon-contrast.md
  packages/design-system/src/components/OcAvatarFederated/OcAvatarFederated.vue
Labels: Type:Bug

#12119 fix(web-app-files): show external shares indicator
  changelog/unreleased/bugfix-show-external-share-indicator.md
  packages/design-system/src/styles/theme/oc-flex.scss
  packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
Labels: Type:Bug

#12127 test: convert report generator to mjs
  tests/e2e/cucumber/report/index.mjs
Labels: QA:team

#12109 feat(web-pkg): add file extension custom handler
  changelog/unreleased/enhancement-add-custom-handler-to-file-extensions.md
  docs/extension-system/viewer-editor-apps.md
  packages/web-pkg/src/apps/types.ts
  packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewFile.ts
  packages/web-pkg/src/composables/piniaStores/apps.ts
  packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateNewFile.spec.ts
Labels: Category:Enhancement

#12105 feat: handle editor-less extensions
  changelog/unreleased/enhancement-handle-extensions-without-editor.md
  packages/web-pkg/src/apps/types.ts
  packages/web-pkg/src/composables/actions/files/useFileActions.ts
  packages/web-pkg/tests/unit/composables/actions/files/useFileActions.spec.ts
  packages/web-runtime/src/container/application/classic.ts
Labels: Category:Enhancement

#12135 [tests-only][full-ci] test: bump latest ocis master commit id
  .drone.env
Labels: QA:team

#12137 feat(password-protected-folders): add password protected folders app
  changelog/unreleased/enhancement-add-pasword-protected-folders-app.md
  dev/docker/ocis.web.config.json
  packages/web-app-password-protected-folders/README.md
  packages/web-app-password-protected-folders/l10n/.tx/config
  packages/web-app-password-protected-folders/l10n/translations.json
  packages/web-app-password-protected-folders/package.json
  packages/web-app-password-protected-folders/public/manifest.json
  packages/web-app-password-protected-folders/src/components/CreateFolderModal.vue
  packages/web-app-password-protected-folders/src/composables/useCreateFileHandler.ts
  packages/web-app-password-protected-folders/src/composables/useCustomHandler.ts
  packages/web-app-password-protected-folders/src/composables/useExtensions.ts
  packages/web-app-password-protected-folders/src/composables/useOpenFolderAction.ts
  packages/web-app-password-protected-folders/src/index.ts
  packages/web-app-password-protected-folders/tests/unit/components/CreateFolderModal.spec.ts
  packages/web-app-password-protected-folders/tests/unit/composables/useCreateFileHandler.spec.ts
  pnpm-lock.yaml
Labels: Category:Enhancement

#12141 feat(password-protected-folders): add permissions dropdown
  changelog/unreleased/enhancement-password-protected-folder-permissions.md
  packages/web-app-password-protected-folders/src/components/CreateFolderModal.vue
  packages/web-app-password-protected-folders/src/composables/useCreateFileHandler.ts
  packages/web-app-password-protected-folders/tests/unit/components/CreateFolderModal.spec.ts
  packages/web-app-password-protected-folders/tests/unit/composables/useCreateFileHandler.spec.ts
Labels: Category:Enhancement

#12142 feat(password-protected-folders): open folder in an iframe
  changelog/unreleased/enhancement-add-password-protected-folders-handler.md
  changelog/unreleased/enhancement-control-more-elements-visibility-via-url-query.md
  dev/docker/ocis/csp.yaml
  packages/web-app-password-protected-folders/src/components/FolderViewModal.vue
  packages/web-app-password-protected-folders/src/composables/useCreateFileHandler.ts
  packages/web-app-password-protected-folders/src/composables/useOpenFolderAction.ts
  packages/web-app-password-protected-folders/tests/unit/components/FolderViewModal.spec.ts
  packages/web-app-password-protected-folders/tests/unit/composables/useCreateFileHandler.spec.ts
  packages/web-app-password-protected-folders/tests/unit/composables/useOpenFolderAction.spec.ts
  packages/web-pkg/src/composables/piniaStores/config/types.ts
  packages/web-runtime/src/components/Topbar/TopBar.vue
  packages/web-runtime/src/container/bootstrap.ts
  packages/web-runtime/src/layouts/Application.vue
  packages/web-runtime/tests/unit/components/Topbar/TopBar.spec.ts
Labels: Category:Enhancement
