Repository owncloud/web, pull requests merged in 2025-06, with the labels that each got.

#12648 feat(web-runtime): add login error
  changelog/unreleased/enhancement-add-login-error.md
  packages/web-runtime/src/pages/login.vue
Labels: Category:Enhancement

#12663 [tests-only][full-ci] Bump ocis latest commit id
  .drone.env
Labels: QA:team

#12664 [tests-only][full-ci] Bump latest commit id of ocis
  .drone.env
Labels: QA:team

#12672 Fix the global owncloud.dev build process
  .drone.star
  docs/Makefile
Labels: Topic:Documentation

#12686 [full-ci] feat!: drop deprecated code
  changelog/unreleased/bugfix-allow-email-address-as-user-name-in-the-user-creation-form.md
  changelog/unreleased/bugfix-order-spaces-in-project-view.md
  changelog/unreleased/bugfix-preview-app-flat-file-lists.md
  changelog/unreleased/bugfix-show-progress-bar-when-emptying-trash-bin.md
  changelog/unreleased/change-remove-deprecated-applicationMenu.md
  changelog/unreleased/change-remove-deprecated-applicationQuickAction.md
  changelog/unreleased/change-remove-deprecated-client-init-method.md
  changelog/unreleased/change-remove-deprecated-isFileEditor.md
  changelog/unreleased/change-remove-deprecated-ocsUserContext-and-ocsPublicLinkContext.md
  changelog/unreleased/change-remove-deprecated-type-prop.md
  changelog/unreleased/enhancement-accessibility-improvements.md
  changelog/unreleased/enhancement-add-cataln-to-supported-languages-list.md
  changelog/unreleased/enhancement-create-spaces-via-admin-settings.md
  changelog/unreleased/enhancement-disable-space-membership-management-when-its-server-managed.md
  packages/web-app-files/src/helpers/user/avatarUrl.ts
  packages/web-app-files/tests/unit/helpers/user/avatarUrl.spec.ts
  packages/web-client/src/index.ts
  packages/web-pkg/src/apps/types.ts
  packages/web-pkg/src/composables/piniaStores/apps.ts
  packages/web-pkg/src/services/client/client.ts
  packages/web-pkg/tests/unit/services/archiver.spec.ts
  packages/web-runtime/src/components/Topbar/TopBar.vue
  packages/web-runtime/src/services/auth/publicLinkManager.ts
  packages/web-runtime/src/services/auth/userManager.ts
  packages/web-runtime/tests/unit/components/Topbar/TopBar.spec.ts
Labels: Topic:Deprecation

#12703 [docs-only] Update the make docs-clean command
  docs/Makefile
Labels: Topic:Documentation

#12705 [tests-only][full-ci] Bump ocis latest commit id
  .drone.env
Labels: QA:team

#12695 [docs-only] docs: add deprecations
  docs/building.md
  docs/releasing/_index.md
  docs/releasing/deprecations.md
  docs/releasing/releasing.md
Labels: Topic:Documentation

#12733 [tests-only][full-ci] Bump latest ocis commit id on stable-11.0 branch
  .drone.env
Labels: QA:team

#12731 [tests-only][full-ci] Bump latest ocis commit id
  .drone.env
Labels: QA:team
