Repository owncloud/web, pull requests merged in 2025-04, with the labels that each got.

#12382 [tests-only][full-ci] update golang version to 1.22.4
  .drone.star
Labels: QA:team

#12385 fix: scroll to resource on share notification click
  changelog/unreleased/bugfix-use-resource-id-in-share-notifications.md
  changelog/unreleased/bugfix-watch-scroll-target-in-shared-list.md
  packages/web-app-files/src/views/shares/SharedWithMe.vue
  packages/web-runtime/src/components/Topbar/Notifications.vue
  packages/web-runtime/tests/unit/components/Topbar/Notifications.spec.ts
Labels: Type:Bug

#12155 [tests-only] accessibility test for basic functionalities of file view
  package.json
  pnpm-lock.yaml
  tests/e2e/cucumber/features/a11y/a11y.feature
  tests/e2e/cucumber/steps/ui/a11y.ts
  tests/e2e/support/objects/a11y/actions.ts
  tests/e2e/support/objects/a11y/index.ts
  tests/e2e/support/objects/index.ts
Labels: Status:Needs-Review

#12400 [tests-only][full-ci] bump ocis commit id
  .drone.env
Labels: QA:team

#12401 [tests-only][full-ci] bump ocis stable-7.1 commit id
  .drone.env
Labels: QA:team

#12406 fix(web-pkg): download archives directly
  changelog/unreleased/bugfix-download-archives-directly.md
  changelog/unreleased/bugfix-request-archive-as-blob.md
  packages/web-pkg/src/services/archiver.ts
  packages/web-pkg/tests/unit/services/archiver.spec.ts
Labels: Type:Bug

#12408 chore(web-pkg): drop oC10 archiver handling
  packages/web-pkg/package.json
  packages/web-pkg/src/services/archiver.ts
  packages/web-pkg/tests/unit/composables/actions/files/useFileActionsDownloadArchive.spec.ts
  packages/web-pkg/tests/unit/services/archiver.spec.ts
  pnpm-lock.yaml
Labels: Category:Technical

#12441 [tests-only][full-ci] update playwright version to 1.51.1
  package.json
  pnpm-lock.yaml
Labels: QA:team

#12437 [tests-only][full-ci] bump ocis commit id
  .drone.env
Labels: QA:team

#12460 fix(web-pkg): address user feedback in markdown editor
  changelog/unreleased/bugfix-add-missing-dependencies-to-markdown-editor.md
  changelog/unreleased/bugfix-hide-image-upload-in-markdown-editor.md
  changelog/unreleased/bugfix-hide-save-in-markdown-editor.md
  package.json
  packages/web-pkg/package.json
  packages/web-pkg/src/components/TextEditor/TextEditor.vue
  pnpm-lock.yaml
Labels: Type:Bug

#12468 chore: bump @playwright/test to 1.51.1
  package.json
  pnpm-lock.yaml
Labels: QA:team

#12474 feat: limit tag chars
  changelog/unreleased/enhancement-add-tag-characters-limit.md
  packages/web-app-admin-settings/tests/unit/components/Users/SideBar/EditPanel.spec.ts
  packages/web-app-files/src/components/SideBar/Details/TagsSelect.vue
  packages/web-app-files/tests/unit/components/SideBar/TagsSelect.spec.ts
  packages/web-client/src/ocs/capabilities.ts
  packages/web-pkg/src/composables/piniaStores/capabilities.ts
  packages/web-runtime/tests/unit/pages/account.spec.ts
  packages/web-test-helpers/src/mocks/pinia.ts
Labels: Category:Enhancement

#12481 fix: use plural form of tags in chars limit message
  packages/web-app-files/src/components/SideBar/Details/TagsSelect.vue
Labels: Type:Bug

#12488 feat(web-app-ocm): add explanatory tooltips
  changelog/unreleased/enhancement-add-ocm-explanatory-tooltips.md
  packages/web-app-ocm/src/views/ConnectionsPanel.vue
Labels: Category:Enhancement

#12489 [full-ci][tests-only] check domain detail of external collaborator
  tests/e2e/cucumber/features/ocm/ocm.feature
  tests/e2e/cucumber/steps/ui/shares.ts
Labels: QA:team

#12511 [tests-only][full-ci] removing space id from request body when creating space
  tests/e2e/support/api/graph/spaces.ts
Labels: QA:team

#12512 fix: rename languages link in md editor
  packages/web-pkg/src/components/TextEditor/TextEditor.vue
Labels: Type:Bug

#12508 feat(web-pkg): add duplicate resource action
  changelog/unreleased/enhancement-add-duplicate-action.md
  packages/web-pkg/src/components/AppBar/AppBar.vue
  packages/web-pkg/src/components/FilesList/ContextActions.vue
  packages/web-pkg/src/composables/actions/files/index.ts
  packages/web-pkg/src/composables/actions/files/useFileActions.ts
  packages/web-pkg/src/composables/actions/files/useFileActionsDuplicate.ts
  packages/web-pkg/src/composables/webWorkers/pasteWorker/worker.ts
  packages/web-pkg/src/helpers/resource/conflictHandling/transfer.ts
  packages/web-pkg/src/helpers/resource/conflictHandling/types.ts
  packages/web-pkg/tests/unit/composables/actions/files/useFileActionsDuplicate.spec.ts
Labels: Category:Enhancement

#12473 [tests-only][full-ci] use predefined users with web e2e tests
  tests/e2e/config.js
  tests/e2e/cucumber/environment/index.ts
  tests/e2e/cucumber/features/app-provider/officeSuites.feature
  tests/e2e/cucumber/features/app-provider/secureView.feature
  tests/e2e/cucumber/features/app-provider/urlJourneys.feature
  tests/e2e/cucumber/features/file-action/copyMove.feature
  tests/e2e/cucumber/features/file-action/download.feature
  tests/e2e/cucumber/features/file-action/passwordProtectedFolder.feature
  tests/e2e/cucumber/features/file-action/rename.feature
  tests/e2e/cucumber/features/navigation/applicationMenu.feature
  tests/e2e/cucumber/features/navigation/breadcrumb.feature
  tests/e2e/cucumber/features/navigation/pageNotFoud.feature
  tests/e2e/cucumber/features/navigation/personalSpacePagination.feature
  tests/e2e/cucumber/features/navigation/shortcut.feature
  tests/e2e/cucumber/features/ocm/ocm.feature
  tests/e2e/cucumber/features/search/search.feature
  tests/e2e/cucumber/features/shares/denyShareAccess.feature
  tests/e2e/cucumber/features/shares/internalLink.feature
  tests/e2e/cucumber/features/shares/link.feature
  tests/e2e/cucumber/features/shares/share.feature
  tests/e2e/cucumber/features/smoke/activity.feature
  tests/e2e/cucumber/features/smoke/sse.feature
  tests/e2e/cucumber/features/smoke/tags.feature
  tests/e2e/cucumber/features/smoke/trashbinDelete.feature
  tests/e2e/cucumber/features/smoke/upload.feature
  tests/e2e/cucumber/features/smoke/uploadResumable.feature
  tests/e2e/cucumber/features/user-settings/gdprExport.feature
  tests/e2e/cucumber/features/user-settings/languageChange.feature
  tests/e2e/cucumber/features/user-settings/notifications.feature
  tests/e2e/cucumber/features/user-settings/tiles.feature
  tests/e2e/cucumber/steps/api.ts
  tests/e2e/cucumber/steps/ui/accountMenu.ts
  tests/e2e/cucumber/steps/ui/application.ts
  tests/e2e/cucumber/steps/ui/federation.ts
  tests/e2e/cucumber/steps/ui/notifications.ts
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/cucumber/steps/ui/shares.ts
  tests/e2e/cucumber/steps/ui/spaces.ts
  tests/e2e/support/api/davSpaces/index.ts
  tests/e2e/support/api/davSpaces/spaces.ts
  tests/e2e/support/api/graph/userManagement.ts
  tests/e2e/support/api/http.ts
  tests/e2e/support/api/keycloak/user.ts
  tests/e2e/support/api/keycloak/utils.ts
  tests/e2e/support/api/share/share.ts
  tests/e2e/support/api/token/utils.ts
  tests/e2e/support/api/userSettings/index.ts
  tests/e2e/support/api/userSettings/settings.ts
  tests/e2e/support/environment/sse.ts
  tests/e2e/support/environment/userManagement.ts
  tests/e2e/support/objects/app-admin-settings/users/index.ts
  tests/e2e/support/store/user.ts
  tests/e2e/support/types.ts
  tests/e2e/support/utils/index.ts
  tests/e2e/support/utils/locator.ts
  tests/e2e/support/utils/substitute.ts
Labels: QA:team

#12520 docs: add docs about running e2e tests with predefined users
  docs/testing/testing.md
Labels: QA:team
