Repository owncloud/web, pull requests merged in 2025-07, with the labels that each got.

#12780 fix(web-app-admin-settings): [OCISDEV-138] handle direct admin settings access
  changelog/unreleased/bugfix-handle-direct-admin-settings-access.md
  packages/web-app-admin-settings/src/index.ts
  packages/web-app-admin-settings/tests/unit/index.spec.ts
Labels: Type:Bug

#12821 [tests-only][full-ci] Bump latest ocis commit id on master branch
  .drone.env
Labels: QA:team

#12839 [tests-only][full-ci] Bump latest ocis commit id on stable-12 branch
  .drone.env
Labels: QA:team

#12841 [tests-only][full-ci] Chore(ci):skip clone step in notification pipeline
  .drone.star
Labels: QA:team

#12842 [tests-only][full-ci] Backport/disable clone on notification
  .drone.star
Labels: QA:team

#12860 [tests-only][full-ci] Bump latest ocis commit id on master branch
  .drone.env
Labels: QA:team

#12788 feat: [OCISDEV-142] add export as PDF file action
  changelog/unreleased/enhancement-add-markdown-to-pdf-export.md
  package.json
  packages/web-pkg/package.json
  packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
  packages/web-pkg/src/components/Modals/ExportAsPdfModal.vue
  packages/web-pkg/src/composables/actions/files/index.ts
  packages/web-pkg/src/composables/actions/files/useFileActionsExportAsPdf.ts
  packages/web-pkg/src/composables/webWorkers/exportAsPdfWorker/helpers.ts
  packages/web-pkg/src/composables/webWorkers/exportAsPdfWorker/index.ts
  packages/web-pkg/src/composables/webWorkers/exportAsPdfWorker/markedExtensions.ts
  packages/web-pkg/src/composables/webWorkers/exportAsPdfWorker/pdfConfig.ts
  packages/web-pkg/src/composables/webWorkers/exportAsPdfWorker/renderer.ts
  packages/web-pkg/src/composables/webWorkers/exportAsPdfWorker/useImages.ts
  packages/web-pkg/src/composables/webWorkers/exportAsPdfWorker/useKaTeX.ts
  packages/web-pkg/src/composables/webWorkers/exportAsPdfWorker/useMermaid.ts
  packages/web-pkg/src/composables/webWorkers/exportAsPdfWorker/worker.ts
  packages/web-pkg/tests/unit/composables/webWorkers/exportAsPdfWorker/helpers.spec.ts
  packages/web-pkg/tests/unit/composables/webWorkers/exportAsPdfWorker/markedExtensions.spec.ts
  packages/web-pkg/tests/unit/composables/webWorkers/exportAsPdfWorker/renderer.spec.ts
  packages/web-pkg/tests/unit/composables/webWorkers/exportAsPdfWorker/useImages.spec.ts
  packages/web-pkg/tests/unit/composables/webWorkers/exportAsPdfWorker/useKaTeX.spec.ts
  packages/web-pkg/tests/unit/composables/webWorkers/exportAsPdfWorker/useMermaid.spec.ts
  packages/web-pkg/tests/unit/composables/webWorkers/exportAsPdfWorker/worker.spec.ts
  pnpm-lock.yaml
  tests/unit/config/vitest.init.ts
Labels: Category:Enhancement
