Repository owncloud/web, pull requests merged in 2025-05, with the labels that each got.

#12528 [tests-only][full-ci] bump latest ocis commit id
  .drone.env
Labels: QA:team

#12529 [test-only][full-ci] bump ocis stable-7.1 commit id
  .drone.env
Labels: QA:team

#12524 [tests-only][ci] use cache server and bucket variables
  .drone.star
Labels: QA:team

#12519 feat: improve files drop view UI
  changelog/unreleased/enhancement-improve-file-drop-view-ui.md
  packages/design-system/src/styles/theme/background.scss
  packages/design-system/src/styles/theme/helper.scss
  packages/design-system/src/styles/theme/oc-text.scss
  packages/web-app-files/src/components/AppBar/Upload/ResourceUpload.vue
  packages/web-app-files/src/views/FilesDrop.vue
  packages/web-app-files/tests/unit/views/FilesDrop.spec.ts
  packages/web-client/src/helpers/space/functions.ts
  packages/web-client/src/helpers/space/types.ts
  packages/web-pkg/src/router/public.ts
  packages/web-pkg/src/services/uppy/uppyService.ts
  packages/web-runtime/src/components/UploadBar.vue
  packages/web-runtime/src/components/UploadInfo.vue
  packages/web-runtime/src/layouts/Application.vue
  packages/web-runtime/tests/unit/components/UploadBar.spec.ts
  tests/e2e/support/objects/app-files/page/public.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
Labels: Category:Enhancement

#12534 chore(design-system): drop npm-run-all2 dependency
  packages/design-system/package.json
  pnpm-lock.yaml
Labels: Topic:Dependencies

#12540 [full-ci][tests-only] add test to upload folder via drag-n-drop
  tests/e2e/cucumber/features/smoke/upload.feature
  tests/e2e/support/utils/dragDrop.ts
Labels: QA:team

#12547 [tests-only][full-ci] bump lastest ocis commit id
  .drone.env
Labels: QA:team

#12535 [full-ci][tests-only] adding test for flat list
  tests/e2e/cucumber/features/spaces/pagination.feature
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: QA:team

#12546 [full-ci][tests-only]Add tests for duplicating resources
  tests/e2e/cucumber/features/file-action/copyMove.feature
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: QA:team

#12548 [full-ci][tests-only] add test for tag feature
  tests/e2e/cucumber/features/smoke/tags.feature
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: QA:team

#12555 [full-ci][tests-only]add tests for duplicating multiple resource at once using batch-action
  tests/e2e/cucumber/features/file-action/copyMove.feature
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: QA:team

#12567 feat(web-pkg)!: remove CERN's collapsible table
  changelog/unreleased/change-remove-cerns-collapsible-table.md
  packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
  packages/web-pkg/src/cern/components/CollapsibleOcTable.vue
  packages/web-pkg/src/components/FilesList/ResourceTable.vue
Labels: Category:Change

#12570 [tests-only][full-ci] bump latest ocis commit id
  .drone.env
Labels: QA:team

#12571 [test-only][full-ci] bump ocis stable-7.1 commit id
  .drone.env
Labels: QA:team

#12553 [tests-only][full-ci] set configs based on browser support
  tests/e2e/cucumber/environment/index.ts
  tests/e2e/support/environment/actor/shared.ts
Labels: QA:team

#12584 feat: add configurable space members management
  changelog/unreleased/enhancement-disable-space-membership-management-when-its-server-managed
  packages/web-client/src/ocs/capabilities.ts
  packages/web-pkg/src/composables/piniaStores/capabilities.ts
  packages/web-pkg/src/composables/shares/useCanShare.ts
Labels: Category:Enhancement

#12588 [full-ci] use same hostname for both ocis instances in docker compose setup
  dev/docker/ocis.idp.config.yaml
  dev/docker/ocis.storage.ocmproviders.json
  dev/docker/ocis.web-federated.config.json
  docker-compose.yml
  tests/e2e/config.js
Labels: QA:team

#12594 ci: make .drone.star docker images accessible by renovate
  .drone.star
Labels: QA:team

#12599 [tests-only][full-ci] bump ocis latest commit id
  .drone.env
Labels: QA:team

#12600 [tests-only][full-ci] bump ocis latest commit id of ocis stable branch
  .drone.env
Labels: QA:team

#12608 fix(web-pkg): do not crash when TUS is unsupported
  changelog/unreleased/bugfix-do-not-crash-when-tus-is-unsupported.md
  packages/web-pkg/src/composables/piniaStores/capabilities.ts
Labels: Type:Bug, Category:Defect

#12597 [full-ci] make .drone.star images accessible by renovate
  .drone.env
  .drone.star
  tests/drone/script.sh
Labels: QA:team

#12611 [full-ci] Send build notification to matrix
  .drone.star
  tests/drone/notifcation.sh
Labels: QA:team

#12572 [tests-only][full-ci] run tests with predefined users
  docs/testing/testing.md
  tests/e2e/cucumber/features/app-provider/lock.feature
  tests/e2e/cucumber/features/app-provider/secureView.feature
  tests/e2e/cucumber/features/file-action/copyMove.feature
  tests/e2e/cucumber/features/file-action/download.feature
  tests/e2e/cucumber/features/file-action/fileViewer.feature
  tests/e2e/cucumber/features/file-action/groupActions.feature
  tests/e2e/cucumber/features/file-action/rename.feature
  tests/e2e/cucumber/features/navigation/personalSpacePagination.feature
  tests/e2e/cucumber/features/navigation/shortcut.feature
  tests/e2e/cucumber/features/search/fullTextSearch.feature
  tests/e2e/cucumber/features/search/search.feature
  tests/e2e/cucumber/features/shares/denyShareAccess.feature
  tests/e2e/cucumber/features/shares/internalLink.feature
  tests/e2e/cucumber/features/shares/link.feature
  tests/e2e/cucumber/features/shares/share.feature
  tests/e2e/cucumber/features/smoke/activity.feature
  tests/e2e/cucumber/features/smoke/sse.feature
  tests/e2e/cucumber/features/smoke/tags.feature
  tests/e2e/cucumber/features/smoke/trashbinDelete.feature
  tests/e2e/cucumber/features/smoke/upload.feature
  tests/e2e/cucumber/features/user-settings/languageChange.feature
  tests/e2e/cucumber/steps/api.ts
  tests/e2e/cucumber/steps/ui/accountMenu.ts
  tests/e2e/cucumber/steps/ui/links.ts
  tests/e2e/cucumber/steps/ui/public.ts
  tests/e2e/cucumber/steps/ui/session.ts
  tests/e2e/cucumber/steps/ui/shares.ts
  tests/e2e/cucumber/steps/ui/spaces.ts
  tests/e2e/support/api/graph/index.ts
  tests/e2e/support/api/graph/userManagement.ts
  tests/e2e/support/api/share/share.ts
  tests/e2e/support/api/token/utils.ts
  tests/e2e/support/api/userSettings/index.ts
  tests/e2e/support/api/userSettings/settings.ts
  tests/e2e/support/environment/sse.ts
  tests/e2e/support/environment/userManagement.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/share/collaborator.ts
  tests/e2e/support/objects/app-files/utils/editor.ts
  tests/e2e/support/objects/runtime/session.ts
  tests/e2e/support/store/link.ts
  tests/e2e/support/types.ts
  tests/e2e/support/utils/substitute.ts
Labels: QA:team

#12110 fix(web-pkg): hide sidebar editor action when the editor is already opened
  changelog/unreleased/enhancement-hide-active-editor-action.md
  packages/web-pkg/src/composables/actions/files/useFileActions.ts
  packages/web-pkg/tests/unit/composables/actions/files/useFileActions.spec.ts
Labels: Category:Enhancement

#12640 [full-ci][tests-only] Bump ocis latest commit id
  .drone.env
Labels: QA:team

#12641 [full-ci][tests-only] Bump latest commit id ocis stable
  .drone.env
Labels: QA:team
