Repository owncloud/web, pull requests merged in 2025-03, with the labels that each got.

#12240 fix: add password policies to psec
  changelog/unreleased/bugfix-add-password-policies-to-password-protected-folders.md
  packages/web-app-password-protected-folders/src/components/CreateFolderModal.vue
  packages/web-app-password-protected-folders/tests/unit/components/CreateFolderModal.spec.ts
Labels: Type:Bug

#12227 fix(pkg): make psec files clickable
  changelog/unreleased/bugfix-make-password-protected-folder-tile-clickable.md
  packages/web-pkg/src/components/FilesList/ResourceTiles.vue
  packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
Labels: Type:Bug

#12244 Typo fix, update PPF README.md
  packages/web-app-password-protected-folders/README.md
Labels: Topic:Documentation

#12246 [test-only][full-ci] test: exit retry loop on success
  tests/e2e/support/api/token/utils.ts
Labels: QA:team

#12242 docs: update release process and add oCIS Web update steps
  docs/releasing.md
Labels: Topic:Documentation

#12239 feat: add maintenance banner
  changelog/unreleased/enhancement-add-maintenance-banner.md
  packages/web-client/src/helpers/index.ts
  packages/web-client/src/helpers/maintenance.ts
  packages/web-client/src/index.ts
  packages/web-client/src/webdav/client/dav.ts
  packages/web-client/src/webdav/index.ts
  packages/web-pkg/src/composables/piniaStores/config/config.ts
  packages/web-pkg/src/composables/webWorkers/deleteWorker/worker.ts
  packages/web-pkg/src/composables/webWorkers/pasteWorker/worker.ts
  packages/web-pkg/src/composables/webWorkers/restoreWorker/worker.ts
  packages/web-pkg/src/http/client.ts
  packages/web-pkg/src/services/client/client.ts
  packages/web-pkg/tests/unit/services/client-maintenance-mode.spec.ts
  packages/web-pkg/tests/unit/services/client.spec.ts
  packages/web-runtime/src/App.vue
  packages/web-runtime/src/components/MaintenanceBanner/MaintenanceBanner.vue
  packages/web-runtime/src/components/MaintenanceBanner/MaintenanceDetailsModal.vue
  packages/web-runtime/src/components/MaintenanceBanner/index.ts
  packages/web-runtime/src/composables/maintenanceMode/index.ts
  packages/web-runtime/src/composables/maintenanceMode/useMaintenanceMode.ts
  packages/web-runtime/src/layouts/Application.vue
Labels: Category:Enhancement

#12266 fix(web-pkg): pass generate link password method as callback
  changelog/unreleased/bugfix-generate-public-link-password-on-click.md
  packages/web-pkg/src/components/CreateLinkModal.vue
Labels: Type:Bug

#12269 chore: update readme file to include correct oCIS demo page link
  README.md
Labels: Topic:Documentation

#12270 fix(web-app-password-protected-folders): add password generator
  changelog/unreleased/bugfix-add-password-generator-into-password-protected-folders.md
  packages/web-app-password-protected-folders/src/components/CreateFolderModal.vue
Labels: Type:Bug

#12237 [tests-only][full-ci] harden weboffice tests
  tests/e2e/cucumber/steps/ui/public.ts
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/environment/actor/actor.ts
  tests/e2e/support/objects/app-files/page/public.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
  tests/e2e/support/objects/app-files/resource/webOffice.ts
Labels: QA:team

#12292 Just a small source text fix for translations
  packages/web-runtime/src/components/MaintenanceBanner/MaintenanceBanner.vue
  packages/web-runtime/src/components/MaintenanceBanner/MaintenanceDetailsModal.vue
Labels: Topic:Documentation

#12214 [tests-only][full-ci] Test for deleting password protected folder
  tests/e2e/cucumber/features/file-action/passwordProtectedFolder.feature
Labels: QA:team

#12277 [full-ci] Fix failing E2E tests
  .drone.env
  tests/e2e/cucumber/features/app-provider/officeSuites.feature
  tests/e2e/cucumber/features/file-action/groupActions.feature
  tests/e2e/cucumber/features/journeys/kindergarten.feature
  tests/e2e/cucumber/features/ocm/ocm.feature
  tests/e2e/cucumber/features/shares/share.feature
  tests/e2e/cucumber/features/smoke/activity.feature
  tests/e2e/cucumber/features/smoke/sse.feature
  tests/e2e/cucumber/features/smoke/tags.feature
  tests/e2e/cucumber/features/smoke/trashbinDelete.feature
  tests/e2e/cucumber/features/spaces/project.feature
  tests/e2e/cucumber/features/user-settings/notifications.feature
  tests/e2e/support/api/share/share.ts
Labels: QA:team

#12310 [full-ci] Update Drone config file for branch `stable-7.1`
  .drone.env
Labels: Status:Needs-Review, QA:team

#12311 [tests-only][full-ci] bump ocis commit id
  .drone.env
Labels: QA:team

#12326 fix: drop links advanced mode
  changelog/unreleased/bugfix-do-not-reveal-generated-password.md
  changelog/unreleased/bugfix-drop-advanced-mode-when-creating-links.md
  packages/design-system/src/components/OcTextInput/OcTextInput.spec.ts
  packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
  packages/design-system/src/components/_OcTextInputPassword/_OcTextInputPassword.vue
  packages/web-pkg/src/components/CreateLinkModal.vue
  packages/web-pkg/tests/unit/components/CreateLinkModal.spec.ts
  tests/e2e/support/objects/app-files/link/actions.ts
Labels: Type:Bug

#12325 [full-ci][tests-only] use manual elements drag-n-drop in the tests
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/utils/dragDrop.ts
Labels: QA:team

#12329 fix: delete psec file when deleting password protected folder
  changelog/unreleased/bugfix-delete-psec-file.md
  packages/web-app-password-protected-folders/README.md
  packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
  packages/web-pkg/src/composables/piniaStores/spaces.ts
  packages/web-pkg/tests/unit/composables/actions/helpers/useFileActionsDeleteResources.spec.ts
Labels: Type:Bug

#12336 fix: handle shares loading error
  changelog/unreleased/bugfix-handle-shares-loading-error.md
  packages/design-system/src/styles/theme/oc-text.scss
  packages/web-app-files/src/components/SideBar/Shares/SharesPanel.vue
  packages/web-pkg/src/components/SideBar/FileSideBar.vue
  packages/web-pkg/src/composables/piniaStores/shares/shares.ts
Labels: Type:Bug

#12344 [tests-only][full-ci] bump ocis stable-7.1 commit-id
  .drone.env
Labels: QA:team

#12343 [tests-only][full-ci] bump ocis commit id
  .drone.env
Labels: QA:team

#12356 fix(web-pkg): move path tooltip to parent folder
  changelog/unreleased/bugfix-show-path-tooltip-on-parent-folder.md
  packages/web-pkg/src/components/FilesList/ResourceListItem.vue
  packages/web-pkg/src/components/FilesList/ResourceName.vue
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceListItem.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceName.spec.ts.snap
Labels: Type:Bug

#12357 fix(web-pkg): display password screen when link auth fails in editors
  changelog/unreleased/bugfix-handle-changed-public-link-password-in-file-editors.md
  packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
Labels: Type:Bug

#12361 [tests-only][full-ci] Test coverage for bug #12273
  tests/e2e/cucumber/features/file-action/passwordProtectedFolder.feature
Labels: QA:team

#12366 [tests-only][full-ci] combine ocm provider configs using wildcards
  .drone.star
  tests/drone/config-ocis-federated.json
  tests/drone/providers.json
Labels: QA:team

#12369 [tests-only][full-ci] bump ocis commit id
  .drone.env
Labels: QA:team

#12274 [tests-only][full-ci] Test for opening password protected folder
  tests/e2e/cucumber/features/file-action/passwordProtectedFolder.feature
  tests/e2e/cucumber/steps/ui/application.ts
  tests/e2e/cucumber/steps/ui/links.ts
  tests/e2e/cucumber/steps/ui/public.ts
  tests/e2e/support/objects/app-files/link/actions.ts
  tests/e2e/support/objects/app-files/link/index.ts
  tests/e2e/support/objects/app-files/page/public.ts
  tests/e2e/support/objects/app-files/utils/sidebar.ts
Labels: QA:team

#12372 [tests-only][full-ci] check lock before opening word document file
  docker-compose.yml
  tests/e2e/cucumber/features/app-provider/officeSuites.feature
  tests/e2e/support/environment/actor/actor.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/webOffice.ts
Labels: QA:team

#12335 [tests-only][full-ci] Test for opening password protected folder with wrong password
  tests/e2e/cucumber/features/file-action/passwordProtectedFolder.feature
  tests/e2e/cucumber/steps/ui/public.ts
  tests/e2e/support/objects/app-files/link/actions.ts
  tests/e2e/support/objects/app-files/link/index.ts
  tests/e2e/support/objects/app-files/page/public.ts
Labels: QA:team
